apt: pkgAcqMetaBase Class Reference
pkgAcqMetaBase Class Reference
Acquire system {{{
the manager of a transaction
#include <apt-pkg/acquire-item.h>
Public Member Functions
virtual bool QueueURI (pkgAcquire::ItemDesc &Item) APT_OVERRIDE
Insert this item into its owner's queue.
virtual HashStringList GetExpectedHashes () const APT_OVERRIDE
virtual bool HashesRequired () const APT_OVERRIDE
void Add (pkgAcqTransactionItem *const I)
void AbortTransaction ()
bool TransactionHasError () const
void CommitTransaction ()
void TransactionStageCopy (pkgAcqTransactionItem *const I, const std::string &From, const std::string &To)
Stage (queue) a copy action when the transaction is committed.
void TransactionStageRemoval (pkgAcqTransactionItem *const I, const std::string &FinalFile)
Stage (queue) a removal action when the transaction is committed.
virtual std::string GetFinalFilename () const APT_OVERRIDE
Get the full pathname of the final file for the current URI.
pkgAcqMetaBase (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &DataTarget) APT_NONNULL(2
Public Member Functions inherited from pkgAcqTransactionItem
virtual std::string DescURI () const APT_OVERRIDE
A "descriptive" URI-like string.
virtual std::string GetMetaKey () const
virtual bool AcquireByHash () const
pkgAcqTransactionItem (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target) APT_NONNULL(2
Public Member Functions inherited from pkgAcquire::Item
APT_DEPRECATED_MSG ("Use the std::string member ActiveSubprocess instead") const char *Mode
If not NULL, contains the name of a subprocess that is operating on this object (for instance, "gzip" or "gpgv").
virtual void Failed (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf)
Invoked by the acquire worker when the object couldn't be fetched.
APT_HIDDEN void FailMessage (std::string const &Message)
virtual bool VerifyDone (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf)
Invoked by the acquire worker to check if the successfully fetched object is also the objected we wanted to have.
virtual void Done (std::string const &Message, HashStringList const &Hashes, pkgAcquire::MethodConfig const *const Cnf)
Invoked by the acquire worker when the object was fetched successfully.
virtual void Start (std::string const &Message, unsigned long long const Size)
Invoked when the worker starts to fetch this object.
APT_HIDDEN unsigned int & ModifyRetries ()
APT_HIDDEN std::unordered_map< std::string, std::string > & ModifyCustomFields ()
APT_HIDDEN bool PopAlternativeURI (std::string &NewURI)
APT_HIDDEN bool IsGoodAlternativeURI (std::string const &AltUri) const
APT_HIDDEN void PushAlternativeURI (std::string &&NewURI, std::unordered_map< std::string, std::string > &&fields, bool const at_the_back)
APT_HIDDEN void RemoveAlternativeSite (std::string &&OldSite)
virtual std::string ShortDesc () const
Short item description.
virtual void Finished ()
Invoked by the worker when the download is completely done.
std::string HashSum () const
pkgAcquire * GetOwner () const
pkgAcquire::ItemDesc & GetItemDesc ()
virtual bool IsTrusted () const
Item (pkgAcquire *const Owner)
Initialize an item.
virtual ~Item ()
Remove this item from its owner's queue by invoking pkgAcquire::Remove.
bool APT_HIDDEN IsRedirectionLoop (std::string const &NewURI)
int APT_HIDDEN Priority ()
The priority of the item, used for queuing.
Public Member Functions inherited from WeakPointable
void AddWeakPointer (WeakPointable **weakptr)
void RemoveWeakPointer (WeakPointable **weakptr)
~WeakPointable ()
Public Attributes
bool IMSHit
TransactionStates State
std::string BaseURI
Public Attributes inherited from pkgAcqTransactionItem
IndexTarget const Target
std::string PartialFile
storge name until a transaction is finished
pkgAcqMetaClearSig *const TransactionManager
TransactionManager.
Public Attributes inherited from pkgAcquire::Item
enum pkgAcquire::Item::ItemState Status
std::string ErrorText
Contains a textual description of the error encountered if ItemState is StatError or StatAuthError.
unsigned long long FileSize
The size of the object to fetch.
unsigned long long PartialSize
How much of the object was already fetched.
std::string ActiveSubprocess
contains the name of the subprocess that is operating on this object (for instance, "gzip", "rred" or "gpgv"). This is obsoleting #Mode from above as it can manage the lifetime of included string properly.
unsigned long ID
A client-supplied unique identifier.
bool Complete
If true, the entire object has been successfully fetched.
bool Local
If true, the URI of this object is "local".
std::string UsedMirror
unsigned int QueueCounter
The number of fetch queues into which this item has been inserted.
unsigned int ExpectedAdditionalItems
The number of additional fetch items that are expected once this item is done.
std::string DestFile
The name of the file into which the retrieved object will be written.
Protected Member Functions
bool CheckDownloadDone (pkgAcqTransactionItem *const I, const std::string &Message, HashStringList const &Hashes) const
Called when a file is finished being retrieved.
void QueueForSignatureVerify (pkgAcqTransactionItem *const I, std::string const &File, std::string const &Signature)
Queue the downloaded Signature for verification.
virtual std::string Custom600Headers () const APT_OVERRIDE
Custom headers to be sent to the fetch process.
bool CheckAuthDone (std::string const &Message)
Called when authentication succeeded.
bool CheckStopAuthentication (pkgAcquire::Item *const I, const std::string &Message)
bool VerifyVendor (std::string const &Message)
Check that the release file is a release file for the correct distribution.
virtual bool TransactionState (TransactionStates const state) APT_OVERRIDE
Protected Member Functions inherited from pkgAcqTransactionItem
HashStringList GetExpectedHashesFor (std::string const &MetaKey) const
Protected Member Functions inherited from pkgAcquire::Item
bool RenameOnError (RenameOnErrorState const state)
Rename failed file and set error.
void Dequeue ()
Remove this item from its owner's queue.
bool Rename (std::string const &From, std::string const &To)
Rename a file without modifying its timestamp.
Protected Attributes
std::vector< pkgAcqTransactionItem * > Transaction
bool AuthPass
If true, the index's signature is currently being verified.
Protected Attributes inherited from pkgAcquire::Item
pkgAcquire *const Owner
The acquire object with which this item is associated.
pkgAcquire::ItemDesc Desc
The item that is currently being downloaded.
Additional Inherited Members
Public Types inherited from pkgAcqTransactionItem
enum TransactionStates { TransactionStarted, TransactionCommit, TransactionAbort }
Public Types inherited from pkgAcquire::Item
enum ItemState {
StatIdle, StatFetching, StatDone, StatError,
StatAuthError, StatTransientNetworkError
}
The current status of this item.
Protected Types inherited from pkgAcquire::Item
enum RenameOnErrorState {
HashSumMismatch, SizeMismatch, InvalidFormat, SignatureError,
NotClearsigned, MaximumSizeExceeded, PDiffError
}
Detailed Description
the manager of a transaction
Member Function Documentation
CheckAuthDone()
bool CheckAuthDone (std::string const & Message) protected
Called when authentication succeeded.
Sanity-checks the authenticated file, queues up the individual index files for download, and saves the signature in the lists directory next to the authenticated list file.
Parameters
Message The message block received from the fetch subprocess.
References pkgAcquire::Item::ErrorText, pkgAcquire::Item::GetFinalFilename(), and pkgAcqMetaClearSig::MetaIndexParser.
Referenced by pkgAcqMetaSig::Done(), and pkgAcqMetaClearSig::Done().
CheckDownloadDone()
bool CheckDownloadDone (pkgAcqTransactionItem *const I, const std::string & Message, HashStringList const & Hashes) const protected
Called when a file is finished being retrieved.
If the file was not downloaded to DestFile, a copy process is set up to copy it to DestFile; otherwise, Complete is set to true and the file is moved to its final location.
Parameters
Message The message block received from the fetch subprocess.
References pkgAcquire::Item::Complete, pkgAcquire::Item::Desc, pkgAcquire::Item::DestFile, pkgAcquire::Item::GetFinalFilename(), pkgAcquire::Item::Local, pkgAcqTransactionItem::PartialFile, pkgAcqTransactionItem::QueueURI(), pkgAcquire::ItemDesc::URI, HashStringList::usable(), and HashStringList::VerifyFile().
Referenced by pkgAcqMetaIndex::Done(), pkgAcqMetaSig::Done(), and pkgAcqMetaClearSig::Done().
CheckStopAuthentication()
bool CheckStopAuthentication (pkgAcquire::Item *const I, const std::string & Message) protected
Check if the current item should fail at this point
References pkgAcquire::Item::Desc, pkgAcquire::ItemDesc::Description, pkgAcquire::Item::GetFinalFilename(), pkgAcquire::Item::StatAuthError, and pkgAcquire::Item::StatTransientNetworkError.
Referenced by pkgAcqMetaSig::Failed().
Custom600Headers()
string Custom600Headers () const protected virtual
Custom headers to be sent to the fetch process.
Returns
a string containing RFC822-style headers that are to be inserted into the 600 URI Acquire message sent to the fetch subprocess. The headers are inserted after a newline-less line, so they should (if nonempty) have a leading newline and no trailing newline.
Reimplemented from pkgAcquire::Item.
Reimplemented in pkgAcqMetaClearSig.
References pkgAcquire::Item::Custom600Headers(), and pkgAcquire::Item::GetFinalFilename().
Referenced by pkgAcqMetaClearSig::Custom600Headers().
GetExpectedHashes()
HashStringList GetExpectedHashes () const virtual
Returns
HashSums the DestFile is supposed to have in this stage
Reimplemented from pkgAcqTransactionItem.
HashesRequired()
APT_PURE bool HashesRequired () const virtual
Returns
if having no hashes is a hard failure or not
Idealy this is always true for every subclass, but thanks to historical grow we don't have hashes for all files in all cases in all steps, so it is slightly more complicated than it should be.
Reimplemented from pkgAcqTransactionItem.
QueueURI()
bool QueueURI (pkgAcquire::ItemDesc & Item) virtual
Insert this item into its owner's queue.
The method is designed to check if the request would end in an IMSHit and if it determines that it would, it isn't queueing the Item and instead sets it to completion instantly.
Parameters
Item Metadata about this item (its URI and description).
Returns
true if the item was inserted, false if IMSHit was detected
Reimplemented from pkgAcqTransactionItem.
References pkgAcquire::Item::QueueURI().
Referenced by pkgAcqMetaIndex::pkgAcqMetaIndex().
VerifyVendor()
bool VerifyVendor (std::string const & Message) protected
Check that the release file is a release file for the correct distribution.
Returns
true if no fatal errors were encountered.
References pkgAcquire::Item::Desc, pkgAcquire::ItemDesc::Description, pkgAcquire::Item::ErrorText, metaIndex::GetExpectedDist(), pkgAcquire::Item::GetFinalFilename(), pkgAcquire::Log, pkgAcqMetaClearSig::MetaIndexParser, pkgAcquireStatus::ReleaseInfoChanges(), and IndexTarget::URI.
The documentation for this class was generated from the following files:
apt-pkg/acquire-item.h
apt-pkg/acquire-item.cc