apt: pkgAcqMetaSig Class Reference
pkgAcqMetaSig Class Reference
Acquire system {{{
An acquire item that downloads the detached signature {{{ of a meta-index (Release) file, then queues up the release file itself.
#include <apt-pkg/acquire-item.h>
Public Member Functions
virtual bool HashesRequired () const APT_OVERRIDE
virtual void Failed (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf) APT_OVERRIDE
Invoked by the acquire worker when the object couldn't be fetched.
virtual void Done (std::string const &Message, HashStringList const &Hashes, pkgAcquire::MethodConfig const *const Cnf) APT_OVERRIDE
Invoked by the acquire worker when the object was fetched successfully.
virtual std::string Custom600Headers () const APT_OVERRIDE
Custom headers to be sent to the fetch process.
pkgAcqMetaSig (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target, pkgAcqMetaIndex *const MetaIndex) APT_NONNULL(2
Create a new pkgAcqMetaSig.
Public Member Functions inherited from pkgAcqTransactionItem
virtual bool TransactionState (TransactionStates const state)
virtual std::string DescURI () const APT_OVERRIDE
A "descriptive" URI-like string.
virtual HashStringList GetExpectedHashes () const APT_OVERRIDE
virtual std::string GetMetaKey () const
virtual bool AcquireByHash () const
pkgAcqTransactionItem (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target) APT_NONNULL(2
Public Member Functions inherited from pkgAcquire::Item
APT_DEPRECATED_MSG ("Use the std::string member ActiveSubprocess instead") const char *Mode
If not NULL, contains the name of a subprocess that is operating on this object (for instance, "gzip" or "gpgv").
APT_HIDDEN void FailMessage (std::string const &Message)
virtual bool VerifyDone (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf)
Invoked by the acquire worker to check if the successfully fetched object is also the objected we wanted to have.
virtual void Start (std::string const &Message, unsigned long long const Size)
Invoked when the worker starts to fetch this object.
APT_HIDDEN unsigned int & ModifyRetries ()
APT_HIDDEN std::unordered_map< std::string, std::string > & ModifyCustomFields ()
APT_HIDDEN bool PopAlternativeURI (std::string &NewURI)
APT_HIDDEN bool IsGoodAlternativeURI (std::string const &AltUri) const
APT_HIDDEN void PushAlternativeURI (std::string &&NewURI, std::unordered_map< std::string, std::string > &&fields, bool const at_the_back)
APT_HIDDEN void RemoveAlternativeSite (std::string &&OldSite)
virtual std::string ShortDesc () const
Short item description.
virtual void Finished ()
Invoked by the worker when the download is completely done.
std::string HashSum () const
pkgAcquire * GetOwner () const
pkgAcquire::ItemDesc & GetItemDesc ()
virtual bool IsTrusted () const
Item (pkgAcquire *const Owner)
Initialize an item.
virtual ~Item ()
Remove this item from its owner's queue by invoking pkgAcquire::Remove.
bool APT_HIDDEN IsRedirectionLoop (std::string const &NewURI)
int APT_HIDDEN Priority ()
The priority of the item, used for queuing.
Public Member Functions inherited from WeakPointable
void AddWeakPointer (WeakPointable **weakptr)
void RemoveWeakPointer (WeakPointable **weakptr)
~WeakPointable ()
Protected Member Functions
virtual std::string GetFinalFilename () const APT_OVERRIDE
Get the full pathname of the final file for the current URI.
Protected Member Functions inherited from pkgAcqTransactionItem
HashStringList GetExpectedHashesFor (std::string const &MetaKey) const
bool QueueURI (pkgAcquire::ItemDesc &Item) APT_OVERRIDE
Insert this item into its owner's queue.
Protected Member Functions inherited from pkgAcquire::Item
bool RenameOnError (RenameOnErrorState const state)
Rename failed file and set error.
void Dequeue ()
Remove this item from its owner's queue.
bool Rename (std::string const &From, std::string const &To)
Rename a file without modifying its timestamp.
Additional Inherited Members
Public Types inherited from pkgAcqTransactionItem
enum TransactionStates { TransactionStarted, TransactionCommit, TransactionAbort }
Public Types inherited from pkgAcquire::Item
enum ItemState {
StatIdle, StatFetching, StatDone, StatError,
StatAuthError, StatTransientNetworkError
}
The current status of this item.
Public Attributes inherited from pkgAcqTransactionItem
IndexTarget const Target
std::string PartialFile
storge name until a transaction is finished
pkgAcqMetaClearSig *const TransactionManager
TransactionManager.
Public Attributes inherited from pkgAcquire::Item
enum pkgAcquire::Item::ItemState Status
std::string ErrorText
Contains a textual description of the error encountered if ItemState is StatError or StatAuthError.
unsigned long long FileSize
The size of the object to fetch.
unsigned long long PartialSize
How much of the object was already fetched.
std::string ActiveSubprocess
contains the name of the subprocess that is operating on this object (for instance, "gzip", "rred" or "gpgv"). This is obsoleting #Mode from above as it can manage the lifetime of included string properly.
unsigned long ID
A client-supplied unique identifier.
bool Complete
If true, the entire object has been successfully fetched.
bool Local
If true, the URI of this object is "local".
std::string UsedMirror
unsigned int QueueCounter
The number of fetch queues into which this item has been inserted.
unsigned int ExpectedAdditionalItems
The number of additional fetch items that are expected once this item is done.
std::string DestFile
The name of the file into which the retrieved object will be written.
Protected Types inherited from pkgAcquire::Item
enum RenameOnErrorState {
HashSumMismatch, SizeMismatch, InvalidFormat, SignatureError,
NotClearsigned, MaximumSizeExceeded, PDiffError
}
Protected Attributes inherited from pkgAcquire::Item
pkgAcquire *const Owner
The acquire object with which this item is associated.
pkgAcquire::ItemDesc Desc
The item that is currently being downloaded.
Detailed Description
An acquire item that downloads the detached signature {{{ of a meta-index (Release) file, then queues up the release file itself.
Todo:
Why protected members?
See also
pkgAcqMetaIndex
Member Function Documentation
Custom600Headers()
std::string Custom600Headers () const virtual
Custom headers to be sent to the fetch process.
Returns
a string containing RFC822-style headers that are to be inserted into the 600 URI Acquire message sent to the fetch subprocess. The headers are inserted after a newline-less line, so they should (if nonempty) have a leading newline and no trailing newline.
Reimplemented from pkgAcquire::Item.
References pkgAcquire::Item::Custom600Headers(), and pkgAcqMetaClearSig::MetaIndexParser.
Done()
void Done (std::string const & Message, HashStringList const & Hashes, pkgAcquire::MethodConfig const *const Cnf) virtual
Invoked by the acquire worker when the object was fetched successfully.
Note that the object might not have been written to DestFile; check for the presence of an Alt-Filename entry in Message to find the file to which it was really written.
Done is often used to switch from one stage of the processing to the next (e.g. fetching, unpacking, copying). It is one branch of the continuation of the fetch process.
Parameters
Message Data from the acquire method. Use LookupTag() to parse it.
Hashes The HashSums of the object that was fetched.
Cnf The method via which the object was fetched.
See also
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References pkgAcqMetaBase::AuthPass, pkgAcqMetaBase::CheckAuthDone(), pkgAcqMetaBase::CheckDownloadDone(), pkgAcquire::Item::DestFile, pkgAcqMetaBase::GetFinalFilename(), GetFinalFilename(), pkgAcqMetaBase::QueueForSignatureVerify(), pkgAcquire::Item::StatAuthError, and pkgAcqMetaBase::TransactionStageCopy().
Failed()
void Failed (std::string const & Message, pkgAcquire::MethodConfig const *const Cnf) virtual
Invoked by the acquire worker when the object couldn't be fetched.
This is a branch of the continuation of the fetch process.
Parameters
Message An RFC822-formatted message from the acquire method describing what went wrong. Use LookupTag() to parse it.
Cnf The method via which the worker tried to fetch this object.
See also
pkgAcqMethod
Todo:
this is used often (e.g. in pkgAcqIndexTrans) so refactor
Reimplemented from pkgAcquire::Item.
References pkgAcqMetaBase::AuthPass, pkgAcqMetaBase::CheckStopAuthentication(), and pkgAcqMetaBase::TransactionStageRemoval().
HashesRequired()
virtual bool HashesRequired () const inline virtual
Returns
if having no hashes is a hard failure or not
Idealy this is always true for every subclass, but thanks to historical grow we don't have hashes for all files in all cases in all steps, so it is slightly more complicated than it should be.
Reimplemented from pkgAcqTransactionItem.
References pkgAcquire::Item::Custom600Headers(), pkgAcquire::Item::Done(), pkgAcquire::Item::Failed(), and pkgAcquire::Item::Owner.
The documentation for this class was generated from the following files:
apt-pkg/acquire-item.h
apt-pkg/acquire-item.cc