'\" t
.\"     Title: apt
.\"    Author: APT-team
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 20\ \&october\ \&2015
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT" "8" "20\ \&october\ \&2015" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt \- commandoregelinterface
.SH "SAMENVATTING"
.HP \w'\fBapt\fR\ 'u
\fBapt\fR [\fB\-h\fR] [\fB\-o=\fR\fB\fIconfiguratietekenreeks\fR\fR] [\fB\-c=\fR\fB\fIconfiguratiebestand\fR\fR] [\fB\-t=\fR\fB\fIdoelrelease\fR\fR] [\fB\-a=\fR\fB\fIarchitectuur\fR\fR] {list | search | show | update | install\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | remove\ \fIpakket\fR...  | upgrade | full\-upgrade | edit\-sources | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "OMSCHRIJVING"
.PP
\fBapt\fR
biedt een hogere commandoregelinterface voor het systeem van pakketbeheer\&. Het is bedoeld als een interface voor de eindgebruiker en standaard gebruikt het sommige opties op een manier die, vergeleken met meer gespecialiseerde APT\-hulpmiddelen zoals
\fBapt-get\fR(8)
en
\fBapt-cache\fR(8), beter aangepast is aan interactief gebruik\&.
.PP
Ook de man\-pagina is, in grote mate gelijk
\fBapt\fR
zelf, bedoeld als een interface voor de eindgebruiker\&. In die hoedanigheid vermeldt ze enkel de meest gebruikte commando\*(Aqs en opties\&. Deels is dit om niet op verschillende plaatsen met dezelfde informatie te komen en deels om te vermijden dat de lezer overstelpt zou worden door een overvloed aan opties en details\&.
.PP
\fBupdate\fR (\fBapt-get\fR(8))
.RS 4
\fBupdate\fR
wordt gebruikt om pakketinformatie op te halen vanuit alle ingestelde pakketbronnen\&. Andere commando\*(Aqs werken met deze gegevens om bijvoorbeeld opwaarderingen van pakketten uit te voeren of om informatie op te zoeken en weer te geven over alle pakketten die beschikbaar zijn voor installatie\&.
.RE
.PP
\fBupgrade\fR (\fBapt-get\fR(8))
.RS 4
upgrade
wordt gebruikt om voor alle pakketten die momenteel op het systeem ge\(:installeerd zijn, de opwaarderingen te installeren die beschikbaar zijn in de pakketbronnen die in het bestand
\fBsources.list\fR(5)
geconfigureerd werden\&. Nieuwe pakketten zullen ge\(:installeerd worden als dat noodzakelijk is om aan vereisten te voldoen, maar ge\(:installeerde pakketten zullen nooit verwijderd worden\&. Indien de opwaardering van een pakket vereist dat een ge\(:installeerd pakket verwijderd wordt, zal de opwaardering voor dat pakket niet uitgevoerd worden\&.
.RE
.PP
\fBfull\-upgrade\fR (\fBapt-get\fR(8))
.RS 4
full\-upgrade
vervult de functie van upgrade, maar zal ook momenteel ge\(:installeerde pakketten verwijderen als dat nodig is om het systeem volledig op te waarderen\&.
.RE
.PP
\fBinstall\fR, \fBremove\fR, \fBpurge\fR (\fBapt-get\fR(8))
.RS 4
Voert de gevraagde actie uit op een of meer pakketten die opgegeven werden aan de hand van een
\fBregex\fR(7), een
\fBglob\fR(7)
(expansie) of een exacte pakketnaam\&. De gevraagde actie kan voor een specifiek pakket gewijzigd worden door aan de naam van dat pakket een plusteken (+) toe te voegen als dat pakket ge\(:installeerd moet worden of een minteken (\-) als het verwijderd moet worden\&.
.sp
Een specifieke versie van een pakket kiezen voor installatie kan door de pakketnaam te laten volgen door een gelijkheidsteken (=) en de te selecteren versie van het pakket\&. Anderzijds kan de versie uit een specifieke distributie geselecteerd worden door de pakketnaam te laten volgen door een slash en de codenaam stretch, buster, sid \&...) of de suitenaam ervan (stable, testing, unstable)\&. Als om aan dit verzoek te kunnen voldoen, vereisten ge\(:installeerd moeten worden, zullen de daarvoor geselecteerde versies ook uit deze release afkomstig zijn\&.
.sp
Bij het verwijderen van een pakket worden alle verpakte gegevens verwijderd, maar de meestal kleine (aangepaste) gebruikersconfiguratiebestanden worden op het systeem achtergelaten voor het geval de verwijdering per ongeluk plaats vond\&. In dat geval volstaat het om een installatieverzoek uit te vaardigen voor het per ongeluk verwijderde pakket om zijn vroegere functionaliteit te herstellen\&. Daarentegen kunt u van deze restanten afraken door het commando
\fBpurge\fR
te gebruiken, zelfs bij reeds verwijderde pakketten\&. Merk op dat dit geen enkele invloed heeft op eventuele gegevens of configuratie\-instellingen die in uw thuismap opgeslagen zijn\&.
.RE
.PP
\fBautoremove\fR (\fBapt-get\fR(8))
.RS 4
autoremove
wordt gebruikt om pakketten te verwijderen die automatisch ge\(:installeerd werden om te voldoen aan de vereisten van andere pakketten en nu niet langer nodig zijn omdat de vereisten veranderden of omdat de pakketten die van die pakketten afhankelijk waren intussen verwijderd werden\&.
.sp
U zou moeten nagaan of de lijst geen toepassingen bevat die u leren waarderen heeft, ook al waren ze ooit enkel ge\(:installeerd als een vereiste voor een ander pakket\&. Een dergelijk pakket kunt u als handmatig ge\(:installeerd markeren met
\fBapt-mark\fR(8)\&. Voor pakketten die u expliciet via
\fBinstall\fR
ge\(:installeerd heeft, zal ook nooit voorgesteld worden om ze automatisch te verwijderderen\&.
.RE
.PP
\fBsearch\fR (\fBapt-cache\fR(8))
.RS 4
\fBsearch\fR
kan gebruikt worden om in de lijst van beschikbare pakketten te zoeken naar de opgegeven
\fBregex\fR(7)\-term(en) en de gevonden overeenkomsten te tonen\&. Dit kan bijvoorbeeld nuttig zijn als u op zoek bent naar pakketten met een specifieke functionaliteit\&. Indien u op zoek bent naar een pakket dat een specifiek bestand bevat, gebruikt u best
\fBapt-file\fR(1)\&.
.RE
.PP
\fBshow\fR (\fBapt-cache\fR(8))
.RS 4
Toont informatie over het/de opgegeven pakket(ten), onder meer welke zijn vereisten zijn, de installatie\- en downloadgrootte, de broncode waarvan het pakket afkomstig is, de beschrijving van de inhoud van het pakket en nog veel meer\&. Het kan bijvoorbeeld nuttig zijn om die informatie te bekijken vooraleer u
\fBapt\fR(8)
toestaat om een pakket te verwijderen of bij het zoeken naar nieuw te installeren pakketten\&.
.RE
.PP
\fBlist\fR (werk\-in\-uitvoering)
.RS 4
list
is min of meer vergelijkbaar met
\fBdpkg\-query \-\-list\fR
in die zin dat het een lijst van pakketten kan weergeven die aan bepaalde criteria beantwoorden\&. Het kent het gebruik van expansiepatronen (\fBglob\fR(7)
patterns) voor het vergelijken van pakketnamen en het ondersteunt opties om ge\(:installeerde (\fB\-\-installed\fR), opwaardeerbare (\fB\-\-upgradable\fR) of alle beschikbare (\fB\-\-all\-versions\fR) versies weer te geven\&.
.RE
.PP
\fBedit\-sources\fR (werk\-in\-uitvoering)
.RS 4
edit\-sources
laat u toe uw
\fBsources.list\fR(5)\-bestanden te bewerken met de teksteditor van uw voorkeur terwijl het ook basale foutcontroles uitvoert\&.
.RE
.SH "HET GEBRUIK IN SCRIPTS EN VERSCHILLEN MET ANDER APT\-GEREEDSCHAP"
.PP
Het commandoregelprogramma
\fBapt\fR(8)
werd ontworpen als een instrument voor de eindgebruiker en het is mogelijk dat het gedrag ervan verschilt naargelang de versie van het programma\&. Hoewel ernaar gestreefd wordt om de neerwaartse compatibiliteit niet te verbreken, wordt ze ook niet gegarandeerd als blijkt dat een aanpassing gunstig is voor interactief gebruik\&.
.PP
Alle functionaliteit van
\fBapt\fR(8)
is ook beschikbaar via toepassingsspecifiek APT\-gereedschap zoals
\fBapt-get\fR(8)
en
\fBapt-cache\fR(8)\&.
\fBapt\fR(8)
wijzigt enkel de standaardwaarde van sommige opties (zie
\fBapt.conf\fR(5)
en in het bijzonder het binaire toepassingsgebied)\&. U zou er daarom de voorkeur aan moeten geven om in uw scripts deze commando\*(Aqs (met eventueel een aantal bijkomende opties) te gebruiken omdat die zoveel als mogelijk achterwaarts compatibel gehouden worden\&.
.SH "ZIE OOK"
.PP
\fBapt-get\fR(8),
\fBapt-cache\fR(8),
\fBsources.list\fR(5),
\fBapt.conf\fR(5),
\fBapt-config\fR(8), De APT Gebruikershandleiding in /usr/share/doc/apt\-doc/,
\fBapt_preferences\fR(5), de APT Howto\&.
.SH "DIAGNOSTIEK"
.PP
\fBapt\fR
geeft de terugkeerwaarde nul bij een normaal verlopen operatie, het decimaal getal 100 in geval van een fout\&.
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[1]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEUR"
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
