#ifndef TRIE_HASH_pkgTagHash
#define TRIE_HASH_pkgTagHash
#include <stddef.h>
#include <stdint.h>
#include <apt-pkg/tagfile.h>
enum class pkgTagSection::Key {
    Architecture = 0,
    Binary = 1,
    Breaks = 2,
    Bugs = 3,
    Build_Conflicts = 4,
    Build_Conflicts_Arch = 5,
    Build_Conflicts_Indep = 6,
    Build_Depends = 7,
    Build_Depends_Arch = 8,
    Build_Depends_Indep = 9,
    Build_Essential = 10,
    Built_For_Profiles = 11,
    Built_Using = 12,
    Checksums_Md5 = 13,
    Checksums_Sha1 = 14,
    Checksums_Sha256 = 15,
    Checksums_Sha512 = 16,
    Class = 17,
    Conffiles = 18,
    Config_Version = 19,
    Conflicts = 20,
    Depends = 21,
    Description = 22,
    Description_md5 = 23,
    Directory = 24,
    Dm_Upload_Allowed = 25,
    Enhances = 26,
    Essential = 27,
    Files = 29,
    Filename = 28,
    Format = 30,
    Homepage = 31,
    Important = 32,
    Installed_Size = 33,
    Installer_Menu_Item = 34,
    Kernel_Version = 35,
    MD5sum = 37,
    MSDOS_Filename = 38,
    Maintainer = 36,
    Multi_Arch = 39,
    Optional = 40,
    Origin = 41,
    Original_Maintainer = 42,
    Package = 43,
    Package_List = 44,
    Package_Revision = 46,
    Package_Type = 47,
    Package__Revision = 45,
    Pre_Depends = 48,
    Priority = 49,
    Provides = 50,
    Recommended = 51,
    Recommends = 52,
    Replaces = 53,
    Revision = 54,
    SHA1 = 56,
    SHA256 = 57,
    SHA512 = 58,
    Section = 55,
    Size = 59,
    Source = 60,
    Standards_Version = 61,
    Status = 62,
    Subarchitecture = 63,
    Suggests = 64,
    Tag = 65,
    Task = 66,
    Testsuite = 67,
    Testsuite_Triggers = 68,
    Triggers_Awaited = 69,
    Triggers_Pending = 70,
    Uploaders = 71,
    Vcs_Bzr = 75,
    Vcs_Cvs = 76,
    Vcs_Git = 78,
    Vcs_Hg = 79,
    Vcs_Mtn = 80,
    Vcs_Svn = 81,
    Vcs_Arch = 72,
    Vcs_Browse = 73,
    Vcs_Browser = 74,
    Vcs_Darcs = 77,
    Version = 82,
    Unknown = -1,
};
 enum pkgTagSection::Key pkgTagHash(const char *string, size_t length);
#endif                       /* TRIE_HASH_pkgTagHash */
