apt: pkgAcqIndexDiffs Class Reference
pkgAcqIndexDiffs Class Reference
Acquire system {{{
An item that is responsible for fetching server-merge patches {{{ that need to be applied to a given package index file.
#include <apt-pkg/acquire-item.h>
Public Member Functions
virtual void Failed (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf) APT_OVERRIDE
Called when the patch file failed to be downloaded.
virtual void Done (std::string const &Message, HashStringList const &Hashes, pkgAcquire::MethodConfig const *const Cnf) APT_OVERRIDE
Invoked by the acquire worker when the object was fetched successfully.
virtual std::string Custom600Headers () const APT_OVERRIDE
Custom headers to be sent to the fetch process.
virtual std::string DescURI () const APT_OVERRIDE
A "descriptive" URI-like string.
virtual HashStringList GetExpectedHashes () const APT_OVERRIDE
virtual bool HashesRequired () const APT_OVERRIDE
virtual bool AcquireByHash () const APT_OVERRIDE
pkgAcqIndexDiffs (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target, std::vector< DiffInfo > const &diffs=std::vector< DiffInfo >()) APT_NONNULL(2
Create an index diff item.
Public Member Functions inherited from pkgAcqBaseIndex
virtual std::string GetFinalFilename () const APT_OVERRIDE
Get the full pathname of the final file for the current URI.
pkgAcqBaseIndex (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target) APT_NONNULL(2
Public Member Functions inherited from pkgAcqTransactionItem
virtual bool TransactionState (TransactionStates const state)
virtual std::string GetMetaKey () const
pkgAcqTransactionItem (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const &Target) APT_NONNULL(2
Public Member Functions inherited from pkgAcquire::Item
APT_DEPRECATED_MSG ("Use the std::string member ActiveSubprocess instead") const char *Mode
If not NULL, contains the name of a subprocess that is operating on this object (for instance, "gzip" or "gpgv").
APT_HIDDEN void FailMessage (std::string const &Message)
virtual bool VerifyDone (std::string const &Message, pkgAcquire::MethodConfig const *const Cnf)
Invoked by the acquire worker to check if the successfully fetched object is also the objected we wanted to have.
virtual void Start (std::string const &Message, unsigned long long const Size)
Invoked when the worker starts to fetch this object.
APT_HIDDEN unsigned int & ModifyRetries ()
APT_HIDDEN std::unordered_map< std::string, std::string > & ModifyCustomFields ()
APT_HIDDEN bool PopAlternativeURI (std::string &NewURI)
APT_HIDDEN bool IsGoodAlternativeURI (std::string const &AltUri) const
APT_HIDDEN void PushAlternativeURI (std::string &&NewURI, std::unordered_map< std::string, std::string > &&fields, bool const at_the_back)
APT_HIDDEN void RemoveAlternativeSite (std::string &&OldSite)
virtual std::string ShortDesc () const
Short item description.
virtual void Finished ()
Invoked by the worker when the download is completely done.
std::string HashSum () const
pkgAcquire * GetOwner () const
pkgAcquire::ItemDesc & GetItemDesc ()
virtual bool IsTrusted () const
Item (pkgAcquire *const Owner)
Initialize an item.
virtual ~Item ()
Remove this item from its owner's queue by invoking pkgAcquire::Remove.
bool APT_HIDDEN IsRedirectionLoop (std::string const &NewURI)
int APT_HIDDEN Priority ()
The priority of the item, used for queuing.
Public Member Functions inherited from WeakPointable
void AddWeakPointer (WeakPointable **weakptr)
void RemoveWeakPointer (WeakPointable **weakptr)
~WeakPointable ()
Protected Types
enum DiffState { StateFetchDiff, StateApplyDiff }
Protected Types inherited from pkgAcquire::Item
enum RenameOnErrorState {
HashSumMismatch, SizeMismatch, InvalidFormat, SignatureError,
NotClearsigned, MaximumSizeExceeded, PDiffError
}
Protected Attributes
bool Debug
If true, debugging output will be written to std::clog.
std::vector< DiffInfo > available_patches
enum pkgAcqIndexDiffs::DiffState State
Protected Attributes inherited from pkgAcquire::Item
pkgAcquire *const Owner
The acquire object with which this item is associated.
pkgAcquire::ItemDesc Desc
The item that is currently being downloaded.
Additional Inherited Members
Public Types inherited from pkgAcqTransactionItem
enum TransactionStates { TransactionStarted, TransactionCommit, TransactionAbort }
Public Types inherited from pkgAcquire::Item
enum ItemState {
StatIdle, StatFetching, StatDone, StatError,
StatAuthError, StatTransientNetworkError
}
The current status of this item.
Public Attributes inherited from pkgAcqTransactionItem
IndexTarget const Target
std::string PartialFile
storge name until a transaction is finished
pkgAcqMetaClearSig *const TransactionManager
TransactionManager.
Public Attributes inherited from pkgAcquire::Item
enum pkgAcquire::Item::ItemState Status
std::string ErrorText
Contains a textual description of the error encountered if ItemState is StatError or StatAuthError.
unsigned long long FileSize
The size of the object to fetch.
unsigned long long PartialSize
How much of the object was already fetched.
std::string ActiveSubprocess
contains the name of the subprocess that is operating on this object (for instance, "gzip", "rred" or "gpgv"). This is obsoleting #Mode from above as it can manage the lifetime of included string properly.
unsigned long ID
A client-supplied unique identifier.
bool Complete
If true, the entire object has been successfully fetched.
bool Local
If true, the URI of this object is "local".
std::string UsedMirror
unsigned int QueueCounter
The number of fetch queues into which this item has been inserted.
unsigned int ExpectedAdditionalItems
The number of additional fetch items that are expected once this item is done.
std::string DestFile
The name of the file into which the retrieved object will be written.
Protected Member Functions inherited from pkgAcqTransactionItem
HashStringList GetExpectedHashesFor (std::string const &MetaKey) const
bool QueueURI (pkgAcquire::ItemDesc &Item) APT_OVERRIDE
Insert this item into its owner's queue.
Protected Member Functions inherited from pkgAcquire::Item
bool RenameOnError (RenameOnErrorState const state)
Rename failed file and set error.
void Dequeue ()
Remove this item from its owner's queue.
bool Rename (std::string const &From, std::string const &To)
Rename a file without modifying its timestamp.
Detailed Description
An item that is responsible for fetching server-merge patches {{{ that need to be applied to a given package index file.
After downloading and applying a single patch, this item will enqueue a new pkgAcqIndexDiffs to download and apply the remaining patches. If no patch can be found that applies to an intermediate file or if one of the patches cannot be downloaded, falls back to downloading the entire package index file using pkgAcqIndex.
See also
pkgAcqDiffIndex, pkgAcqIndex
Member Enumeration Documentation
DiffState
enum DiffState protected
The current status of this patch.
Enumerator
StateFetchDiff
The diff is currently being fetched.
StateApplyDiff
The diff is currently being applied.
Constructor & Destructor Documentation
pkgAcqIndexDiffs()
pkgAcqIndexDiffs (pkgAcquire *const Owner, pkgAcqMetaClearSig *const TransactionManager, IndexTarget const & Target, std::vector< DiffInfo > const & diffs = std::vector<DiffInfo>())
Create an index diff item.
After filling in its basic fields, this invokes Finish(true) if diffs is empty, or QueueNextDiff() otherwise.
Parameters
Owner The pkgAcquire object that owns this item.
TransactionManager responsible for this item
Target we want to built via pdiff patching
baseURI is the URI used for the Index, but stripped down to Target
diffs The remaining diffs from the index of diffs. They should be ordered so that each diff appears before any diff that depends on it.
References available_patches, Debug, pkgAcquire::Item::Desc, pkgAcquire::ItemDesc::Owner, IndexTarget::ShortDesc, pkgAcquire::ItemDesc::ShortDesc, StateFetchDiff, and IndexTarget::URI.
Referenced by Done().
Member Function Documentation
Custom600Headers()
std::string Custom600Headers () const virtual
Custom headers to be sent to the fetch process.
Returns
a string containing RFC822-style headers that are to be inserted into the 600 URI Acquire message sent to the fetch subprocess. The headers are inserted after a newline-less line, so they should (if nonempty) have a leading newline and no trailing newline.
Reimplemented from pkgAcquire::Item.
References available_patches, pkgAcquire::Item::Custom600Headers(), and StateApplyDiff.
DescURI()
virtual std::string DescURI () const inline virtual
A "descriptive" URI-like string.
Returns
a URI that should be used to describe what is being fetched.
Reimplemented from pkgAcqTransactionItem.
References pkgAcquire::Item::GetExpectedHashes(), pkgAcquire::Item::HashesRequired(), and pkgAcquire::Item::Owner.
Done()
void Done (std::string const & Message, HashStringList const & Hashes, pkgAcquire::MethodConfig const *const Cnf) virtual
Invoked by the acquire worker when the object was fetched successfully.
Note that the object might not have been written to DestFile; check for the presence of an Alt-Filename entry in Message to find the file to which it was really written.
Done is often used to switch from one stage of the processing to the next (e.g. fetching, unpacking, copying). It is one branch of the continuation of the fetch process.
Parameters
Message Data from the acquire method. Use LookupTag() to parse it.
Hashes The HashSums of the object that was fetched.
Cnf The method via which the object was fetched.
See also
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References available_patches, Debug, pkgAcquire::Item::Desc, pkgAcquire::Item::Local, pkgAcqIndexDiffs(), pkgAcqTransactionItem::QueueURI(), pkgAcquire::Item::Rename(), StateApplyDiff, StateFetchDiff, IndexTarget::URI, and pkgAcquire::ItemDesc::URI.
Failed()
void Failed (std::string const & Message, pkgAcquire::MethodConfig const *const Cnf) virtual
Called when the patch file failed to be downloaded.
This method will fall back to downloading the whole index file outright; its arguments are ignored.
Reimplemented from pkgAcqBaseIndex.
References available_patches, pkgAcquire::Item::Complete, Debug, pkgAcquire::Item::Dequeue(), pkgAcquire::Item::Desc, IndexTarget::Description, pkgAcquire::ItemDesc::Description, pkgAcqBaseIndex::Failed(), HashStringList::find(), pkgAcqBaseIndex::GetFinalFilename(), IndexTarget::MetaKey, pkgAcqTransactionItem::PartialFile, pkgAcqTransactionItem::QueueURI(), pkgAcquire::Item::Rename(), pkgAcquire::Item::RenameOnError(), pkgAcquire::Item::StatDone, pkgAcqMetaBase::TransactionStageCopy(), IndexTarget::URI, pkgAcquire::ItemDesc::URI, and HashStringList::usable().
GetExpectedHashes()
HashStringList GetExpectedHashes () const virtual
Returns
HashSums the DestFile is supposed to have in this stage
Reimplemented from pkgAcqTransactionItem.
HashesRequired()
APT_PURE bool HashesRequired () const virtual
Returns
if having no hashes is a hard failure or not
Idealy this is always true for every subclass, but thanks to historical grow we don't have hashes for all files in all cases in all steps, so it is slightly more complicated than it should be.
Reimplemented from pkgAcqTransactionItem.
Member Data Documentation
available_patches
std::vector<DiffInfo> available_patches protected
The patches that remain to be downloaded, including the patch being downloaded right now. This list should be ordered so that each diff appears before any diff that depends on it.
Todo:
These are indexed by sha1sum; why not use some sort of dictionary instead of relying on ordering and stripping them off the front?
Referenced by Custom600Headers(), Done(), Failed(), and pkgAcqIndexDiffs().
The documentation for this class was generated from the following files:
apt-pkg/acquire-item.h
apt-pkg/acquire-item.cc