'\" t
.\"     Title: apt_preferences
.\"    Author: APT-team
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 15\ \&augustus\ \&2015
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT_PREFERENCES" "5" "15\ \&augustus\ \&2015" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt_preferences \- Bestand om de voorkeursinstellingen voor APT te beheren
.SH "OMSCHRIJVING"
.PP
Het bestand met de voorkeursinstellingen voor APT,
/etc/apt/preferences, en de bestandsfragmenten uit de map
/etc/apt/preferences\&.d/
kunnen gebruikt worden om in te stellen welke versie van een pakket voor installatie geselecteerd zal worden\&.
.PP
Indien het bestand
\fBsources.list\fR(5)
verwijzingen bevat naar meer dan een uitgave (bijvoorbeeld
stable
en
testing), dan kunnen meerdere versies van eenzelfde pakket beschikbaar zijn voor installatie\&. APT kent aan elke beschikbare versie een prioriteit toe\&. Rekening houdend met eventuele beperkingen ten gevolge van vereisten, zal
\fBapt\-get\fR
de versie met de grootste prioriteit uitkiezen voor installatie\&. De voorkeursinstellingen voor APT overschrijven de prioriteiten die APT standaard aan pakketversies toekent, waardoor de gebruiker controle verwerft over welk pakket voor installatie uitgekozen wordt\&.
.PP
Meerdere exemplaren van eenzelfde versie kunnen beschikbaar zijn indien het bestand
\fBsources.list\fR(5)
verwijzingen bevat naar meer dan een pakketbron\&. In dat geval zal
\fBapt\-get\fR
het exemplaar downloaden dat eerst vermeld wordt in het bestand
\fBsources.list\fR(5)
De APT\-voorkeuren hebben geen invloed op de keuze van het exemplaar, enkel op de versiekeuze\&.
.PP
Voorkeuren leggen veel macht in de handen van een systeembeheerder, maar ze kunnen ook tot zijn grootste nachtmerrie uitgroeien als er niet zorgvuldig mee omgesprongen wordt! APT zal de voorkeuren niet in vraag stellen\&. Daardoor kunnen foute instellingen leiden tot niet\-installeerbare pakketten of tot het nemen van foute beslissingen bij het opwaarderen van pakketten\&. Nog meer problemen kunnen ontstaan als verschillende uitgaven door elkaar gebruikt worden zonder een goed begrip van de volgende paragrafen\&. Pakketten uit een specifieke uitgave worden niet uitgetest voor (en werken daarom niet altijd als verwacht in) eerdere of latere uitgaves of samen met andere pakketten uit verschillende uitgaves\&. U bent gewaarschuwd\&.
.PP
Noteer dat de bestanden uit de map
/etc/apt/preferences\&.d
in oplopende alfanumerieke volgorde ontleed worden en dat hun naam aan de volgende conventie moet beantwoorden: de bestanden hebben ofwel geen bestandsnaamextensie ofwel is dat "pref" en ze bevatten enkel alfanumerieke tekens, koppeltekens (\-), lage streepjes (_) en punten (\&.)\&. In het andere geval zal APT melding maken van het feit dat het een bestand overgeslagen heeft, tenzij dat bestand overeenkomt met een patroon uit de configuratielijst
Dir::Ignore\-Files\-Silently\&. In dat laatste geval zal het stilzwijgend overgeslagen worden\&.
.SS "Door APT standaard toegekende prioriteiten"
.PP
Indien het bestand preferences niet bestaat of indien het geen item bevat dat op een specifieke versie betrekking heeft, dan wordt aan die versie de prioriteit toegekend van de uitgave waartoe die versie behoort\&. Men kan een bepaalde uitgave uitkiezen als "the target release" (de doelrelease), die dan een hogere prioriteit krijgt dan standaard aan andere uitgaven gegeven wordt\&. De doelrelease kan aan de commandoregel van
\fBapt\-get\fR
ingesteld worden of in
/etc/apt/apt\&.conf, het configuratiebestand van APT\&. Merk op dat deze instelling voorrang heeft op gelijk welke algemene prioriteitsinstelling die u vastlegt in het bestand
/etc/apt/preferences
waarover we het later hebben, maar geen voorrang op specifieke gepinde pakketten\&. Bijvoorbeeld
.sp
.if n \{\
.RS 4
.\}
.nf
\fBapt\-get install \-t testing \fR\fB\fIeen\-bepaald\-pakket\fR\fR
.fi
.if n \{\
.RE
.\}
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
APT::Default\-Release "stable";
.fi
.if n \{\
.RE
.\}
.PP
Indien de doelrelease opgegeven werd, dan gebruikt APT het volgende algoritme om de prioriteiten van de versies van een pakket te bepalen\&. Het toekennen van:
.PP
prioriteit 1
.RS 4
aan de versies die afkomstig zijn uit archieven die volgens hun
Release\-bestanden gemarkeerd staan als "NotAutomatic: yes" maar
\fIniet\fR
als "ButAutomaticUpgrades: yes", zoals bijvoorbeeld het Debian\-archief
experimental\&.
.RE
.PP
prioriteit 100
.RS 4
aan de reeds ge\(:installeerde versie (als er een is) en aan de versies die afkomstig zijn van archieven die volgens hun
Release\-bestanden gemarkeerd staan als "NotAutomatic: yes" en "ButAutomaticUpgrades: yes", zoals bijvoorbeeld het Debian\-archief backports sinds
squeeze\-backports\&.
.RE
.PP
prioriteit 500
.RS 4
aan de versies die niet behoren tot de doelrelease\&.
.RE
.PP
prioriteit 990
.RS 4
aan de versies die behoren tot de doelrelease\&.
.RE
De hoogste van deze prioriteiten waarvan de beschrijving overeenkomt met de versie wordt aan die versie toegekend\&.
.PP
Indien er geen doelrelease opgegeven werd, dan kent APT gewoonweg prioriteit 100 toe aan alle ge\(:installeerde pakketversies en prioriteit 500 aan alle niet\-ge\(:installeerde pakketversies, behalve aan versies die afkomstig zijn uit archieven die volgens hun
Release\-bestanden gemarkeerd staan als "NotAutomatic: yes" \- deze versies krijgen de prioriteit 1 of de prioriteit 100 als ze bovendien ook gemarkeerd staan als "ButAutomaticUpgrades: yes"\&.
.PP
Om uit te maken welke versie van een pakket ge\(:installeerd moet worden, past APT dan de volgende regels toe, vermeld in volgorde van prioriteit\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Nooit een degradatie uitvoeren tenzij de prioriteit van een beschikbaar pakket groter is dan 1000\&. ("Degraderen" (downgrading) betekent het installeren van een minder recente versie van een pakket ter vervanging van een recentere versie\&. Noteer dat geen enkele van de standaardprioriteiten die APT gebruikt, groter dan 1000 is\&. Dergelijke hoge prioriteiten kunnen enkel in het bestand preferences ingesteld worden\&. Merk ook op dat het degraderen van een pakket riskant kan zijn\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
De versie met de hoogste prioriteit installeren\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Indien twee of meer versies eenzelfde prioriteit hebben, het meest recente installeren (dat is die met het hoogste versienummer)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
De niet\-ge\(:installeerde versie installeren indien twee of meer versies eenzelfde prioriteit en hetzelfde versienummer hebben maar er op het gebied van de metadata toch een onderling verschil is, of indien de optie
\-\-reinstall
gebruikt werd\&.
.RE
.PP
In een gewone situatie is de ge\(:installeerde versie van een pakket (prioriteit 100) minder recent dan een van de versies die beschikbaar is in een pakketbron die in het bestand
\fBsources.list\fR(5)
vermeld wordt (prioriteit 500 of 990)\&. In dat geval zal het pakket opgewaardeerd worden als de opdracht
\fBapt\-get install \fR\fB\fIeen\-bepaald\-pakket\fR\fR
of
\fBapt\-get upgrade\fR
uitgevoerd wordt\&.
.PP
Een minder vaak voorkomende situatie is die waarbij de ge\(:installeerde versie van een pakket
\fIrecenter\fR
is dan welke andere beschikbare versie ook\&. Bij het uitvoeren van de opdracht apt\-get install
\fB\fIeen\-bepaald\-pakket\fR\fR
of
\fBapt\-get upgrade\fR
zal het pakket dan niet gedegradeerd worden\&.
.PP
Soms is de ge\(:installeerde versie van een pakket recenter dan de versie van de doelrelease, maar niet zo recent als een versie van een andere distributie\&. Zo een pakket zal wel degelijk opgewaardeerd worden als
\fBapt\-get install \fR\fB\fIeen\-bepaald\-pakket\fR\fR
of
\fBapt\-get upgrade\fR
uitgevoerd wordt, omdat minstens
\fIeen\fR
van de beschikbare versies een hogere prioriteit heeft dan de ge\(:installeerde versie\&.
.SS "Het effect van de voorkeursinstellingen voor APT"
.PP
Het APT\-bestand preferences laat de systeembeheerder toe het toekennen van prioriteiten te regelen\&. Het bestand bestaat uit een of meer structuren die uit meerdere regels bestaan en van elkaar gescheiden worden door lege regels\&. De structuren kunnen een van de twee volgende vormen aannemen: een specifieke vorm of een algemene vorm\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
De specifieke vorm kent een prioriteit (een "Pin\-Priority") toe aan een of meer opgegeven pakketten met een specifieke versie of binnen een versiebereik\&. De volgende structuur geeft bijvoorbeeld een hoge prioriteit aan alle versies van het pakket
perl
waarvan het versienummer begint met "5\&.20"\&. Meerdere pakketten kunnen van elkaar gescheiden worden met spaties\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.20*
Pin\-Priority: 1001
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
De algemene vorm kent een prioriteit toe aan alle pakketversies in een bepaalde distributie (dit betekent alle versies van pakketten die vermeld worden in een bepaald
Release\-bestand) of aan alle pakketversies die afkomstig zijn van een bepaalde internetsite, zoals aangegeven door de unieke volledige domeinnaam (fully qualified domain name) van de site\&.
.sp
Zo een item in het preferences\-bestand van APT dat aan de algemene vorm beantwoordt, is enkel op groepen pakketten van toepassing\&. De volgende structuur kent bijvoorbeeld een hoge prioriteit toe aan alle pakketversies die op de lokale site beschikbaar zijn\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: origin ""
Pin\-Priority: 999
.fi
.if n \{\
.RE
.\}
.sp
Een aanmaning tot voorzichtigheid: het gebruikte trefwoord hier is "origin" dat gebruikt kan worden om een computernaam te vergelijken\&. De volgende structuur kent een hoge prioriteit toe aan alle versies die te verkrijgen zijn op de server die met de computernaam "ftp\&.de\&.debian\&.org" ge\(:identificeerd wordt\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: origin "ftp\&.de\&.debian\&.org"
Pin\-Priority: 999
.fi
.if n \{\
.RE
.\}
.sp
Men mag dit
\fIniet\fR
verwarren met de oorsprong (Origin) van een distributie zoals die in een
Release\-bestand vermeld wordt\&. Wat in een
Release\-bestand op het label "Origin:" volgt is geen internetadres, maar een auteur of de naam van een leverancier, zoals "Debian" of "Ximian"\&.
.sp
De volgende structuur kent een lage prioriteit toe aan alle pakketversies die behoren tot gelijk welke distributie die "unstable" als archiefnaam heeft\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.sp
De volgende structuur kent een hoge prioriteit toe aan alle pakketversies die behoren tot om het even welke distributie met de codenaam "buster"\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release n=buster
Pin\-Priority: 900
.fi
.if n \{\
.RE
.\}
.sp
De volgende structuur kent een hoge prioriteit toe aan alle pakketversies die behoren tot om het even welke uitgave die "stable" als archiefnaam heeft en die "9" als releaseversienummer heeft\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=stable, v=9
Pin\-Priority: 500
.fi
.if n \{\
.RE
.\}
.RE
.sp
Het effect van de kommaoperator is vergelijkbaar met een "en" in de logica: aan alle voorwaarden moet voldaan zijn opdat er een overeenkomst zou zijn met de pin\&. Er is \('e\('en uitzondering: voor om het even welk type voorwaarde (zoals twee "a"\-voorwaarden) geldt dat enkel de laatste dergelijke voorwaarde getoetst wordt\&.
.SS "Reguliere expressies en glob(7) syntaxis"
.PP
APT ondersteunt bij het pinnen ook het gebruik van
\fBglob\fR(7)\-expressies, en reguliere expressies die door slashes ingesloten worden\&. Het volgende voorbeeld geeft prioriteit 500 aan alle pakketten uit experimental waarvan de naam begint met gnome (als een
\fBglob\fR(7)\-achtige expressie) of het woord kde (als een in slashes ingesloten POSIX uitgebreide reguliere expressie) bevat\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: gnome* /kde/
Pin: release a=experimental
Pin\-Priority: 500
.fi
.if n \{\
.RE
.\}
.PP
De regel voor deze expressies is dat ze overal kunnen voorkomen waar een tekenreeks kan voorkomen\&. De volgende pin kent dus een prioriteit 990 toe aan alle pakketten van een uitgave die begint met xenial\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release n=xenial*
Pin\-Priority: 990
.fi
.if n \{\
.RE
.\}
.PP
Indien een reguliere expressie voorkomt in een
Package\-veld, dan lokt dit hetzelfde gedrag uit als wanneer deze reguliere expressie vervangen zou worden door een lijst met alle pakketnamen die ermee overeenkomen\&. Het is nog niet beslist of dit in de toekomst anders zal worden\&. U moet dus altijd jokertekenpins eerst plaatsen, zodat latere specifieke pins die kunnen overschrijven\&. Het patroon "*" in een Package\-veld wordt op zichzelf niet als een
\fBglob\fR(7)\-expressie beschouwd\&.
.SS "Hoe APT prioriteiten interpreteert"
.PP
Prioriteiten (P) die in het preferences\-bestand van APT toegekend worden, moeten positieve of negatieve gehele getallen zijn\&. Zij worden (grof geschetst) als volgt ge\(:interpreteerd:
.PP
P >= 1000
.RS 4
heeft de installatie van een versie tot gevolg ook al houdt dit een degradatie van het pakket in
.RE
.PP
990 <= P < 1000
.RS 4
heeft de installatie van een versie tot gevolg ook al is ze niet van de doelrelease afkomstig, tenzij de ge\(:installeerde versie recenter is
.RE
.PP
500 <= P < 990
.RS 4
heeft de installatie van een versie tot gevolg tenzij er een versie uit de doelrelease beschikbaar is of de ge\(:installeerde versie recenter is
.RE
.PP
100 <= P < 500
.RS 4
heeft de installatie van een versie tot gevolg tenzij er een versie uit een andere distributie beschikbaar is of de ge\(:installeerde versie recenter is
.RE
.PP
0 < P < 100
.RS 4
heeft de installatie van een versie tot gevolg enkel en alleen als er geen versie van het pakket ge\(:installeerd is
.RE
.PP
P < 0
.RS 4
voorkomt dat de versie ge\(:installeerd wordt
.RE
.PP
P = 0
.RS 4
heeft ongedefinieerd gedrag; niet te gebruiken\&.
.RE
.PP
Het eerste record van specifieke aard dat een overeenkomst oplevert met een beschikbare pakketversie, bepaalt de prioriteit van die pakketversie\&. Bij gebrek daaraan wordt de prioriteit van het pakket vastgelegd op het maximum van al de prioriteiten die gedefinieerd worden door records van algemene aard waarmee die versie een overeenkomst oplevert\&. Records die bij middel van andere patronen dan "*" in het Pin\-veld gedefinieerd worden, worden behandeld als records van specifieke aard\&.
.PP
Veronderstel bijvoorbeeld dat het APT\-bestand preferences de drie structuren bevat die we eerder bespraken:
.sp
.if n \{\
.RS 4
.\}
.nf
Package: perl
Pin: version 5\&.20*
Pin\-Priority: 1001

Package: *
Pin: origin ""
Pin\-Priority: 999

Package: *
Pin: release unstable
Pin\-Priority: 50
.fi
.if n \{\
.RE
.\}
.PP
Dan is dit het gevolg:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
De meest recente beschikbare versie van het pakket
perl
zal ge\(:installeerd worden, zolang het versienummer van die versie begint met "5\&.20"\&. Indien er
\fIeen of andere\fR
5\&.20* versie van
perl
beschikbaar is en de ge\(:installeerde versie is 5\&.24*, dan zal
perl
gedegradeerd worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Een versie van om het even welk ander pakket dan
perl
dat vanaf het lokale systeem beschikbaar is, heeft prioriteit over andere versies, zelfs versies uit de doelrelease\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Een versie van een pakket waarvan de origine niet het lokale systeem is, maar een andere site die in
\fBsources.list\fR(5)
vermeld wordt, en die tot een
unstable
distributie behoort, wordt enkel ge\(:installeerd als het geselecteerd werd om ge\(:installeerd te worden en er niet reeds een versie van het pakket ge\(:installeerd is\&.
.RE
.sp
.SS "Het vaststellen van pakketversie en distributie\-eigenschappen"
.PP
De locaties die in het bestand
\fBsources.list\fR(5)
vermeld worden, moeten de bestanden
Packages
en
Release
aanbieden om de pakketten te beschrijven die op die locatie ter beschikking staan\&.
.PP
Het bestand
Packages
bevindt zich normaal in de map
\&.\&.\&./dists/\fIdistributienaam\fR/\fIcomponent\fR/\fIarchitectuur\fR, bijvoorbeeld
\&.\&.\&./dists/stable/main/binary\-i386/Packages\&. Het bevat een reeks structuren, die uit meerdere regels bestaan, een per pakket dat in die map beschikbaar is\&. In elke structuur zijn slechts twee regels relevant voor het instellen van APT\-prioriteiten:
.PP
de regel Package:
.RS 4
vermeldt de pakketnaam
.RE
.PP
de regel Version:
.RS 4
vermeldt het versienummer van het genoemde pakket
.RE
.PP
Het bestand
Release
bevindt zich normaal in de map
\&.\&.\&./dists/\fIdistributienaam\fR, bijvoorbeeld
\&.\&.\&./dists/stable/Release, of
\&.\&.\&./dists/stretch/Release\&. Het bevat een enkele structuur bestaande uit meerdere regels, die van toepassing is op
\fIalle\fR
pakketten uit de volledige mappenboom die zich onder diens bovenliggende map bevindt\&. In tegenstelling tot wat het geval is voor het bestand
Packages, zijn praktisch alle regels uit een
Release\-bestand relevant voor het instellen van de APT\-prioriteiten:
.PP
de regel Archive: of de regel Suite:
.RS 4
benoemt het archief waartoe alle pakketten uit de mappenboom behoren\&. Bijvoorbeeld de regel "Archive: stable" of "Suite: stable" geeft aan dat alle pakketten uit de mappenboom die zich onder de bovenliggende map van het bestand
Release
bevindt, deel uitmaken van een
stable
archief\&. Om deze waarde op te geven in het APT\-bestand preferences is de volgende regel nodig:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release a=stable
.fi
.if n \{\
.RE
.\}
.RE
.PP
de regel Codename:
.RS 4
benoemt de codenaam waartoe alle pakketten in de mappenboom behoren\&. De regel "Codename: buster" geeft bijvoorbeeld aan dat alle pakketten uit de mappenboom die zich onder de bovenliggende map van het
Release\-bestand bevindt, tot een versie behoren die de naam
buster
draagt\&. Om deze waarde op te geven in het APT\-bestand preferences is de volgende regel nodig:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release n=buster
.fi
.if n \{\
.RE
.\}
.RE
.PP
de regel Version:
.RS 4
benoemt de releaseversie\&. De pakketten uit de boomstructuur zouden bijvoorbeeld kunnen komen uit de Debian releaseversie 9\&. Merk op dat er normaal geen versienummer bestaat voor de distributies
testing
en
unstable
omdat ze nog niet uitgegeven werden\&. Om dit op te geven in het APT\-bestand preferences is een van de volgende regels nodig\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release v=9
Pin: release a=stable, v=9
Pin: release 9
.fi
.if n \{\
.RE
.\}
.RE
.PP
de regel Component:
.RS 4
benoemt de licentiecomponent van de pakketten uit de mappenboom van het
Release\-bestand\&. De lijn "Component: main" bijvoorbeeld geeft aan dat alle pakketten uit de mappenboom behoren tot de component
main, hetgeen inhoudt dat hun licentie in overeenstemming is met de Vrije Softwarerichtlijnen van Debian\&. Om deze component op te geven in het APT\-bestand preferences is de volgende regel nodig:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release c=main
.fi
.if n \{\
.RE
.\}
.RE
.PP
de regel Origin:
.RS 4
benoemt de maker van de pakketten uit de mappenboom van het
Release\-bestand\&. Meest gebruikelijk is dat
Debian\&. Om deze oorsprong op te geven in het APT\-bestand preferences is de volgende regel nodig:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release o=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
de regel Label:
.RS 4
benoemt het etiket van de pakketten uit de mappenboom van het
Release\-bestand\&. Meest gebruikelijk is dat
Debian\&. Om dit etiket op te geven in het APT\-bestand preferences is de volgende regel nodig:
.sp
.if n \{\
.RS 4
.\}
.nf
Pin: release l=Debian
.fi
.if n \{\
.RE
.\}
.RE
.PP
Alle
Packages\- en
Release\-bestanden die opgehaald worden van locaties die in het bestand
\fBsources.list\fR(5)
vermeld staan, worden opgeslagen in de map
/var/lib/apt/lists
of in het bestand dat in het bestand
apt\&.conf
door de variabele
Dir::State::Lists
genoemd wordt\&. Het bestand
debian\&.lcs\&.mit\&.edu_debian_dists_unstable_contrib_binary\-i386_Release
bevat bijvoorbeeld het
Release\-bestand dat opgehaald werd van de site
debian\&.lcs\&.mit\&.edu
en dat betrekking heeft op bestanden voor de architectuur
binary\-i386
uit de component
contrib
van de distributie
unstable\&.
.SS "Facultatieve regels van een structuur in het bestand preferences van APT"
.PP
In het APT\-bestand preferences kan elke structuur facultatief beginnen met een of meer regels waarvan het eerste woord
Explanation:
is\&. Zo wordt ruimte gemaakt voor commentaar\&.
.SH "VOORBEELDEN"
.SS "De distributie Stable volgen"
.PP
Het volgende preferences\-bestand van APT doet APT een hogere prioriteit dan standaard (500) toekennen aan alle pakketversies die tot een
stable\-distributie behoren en een buitensporig lage prioriteit aan pakketversies die tot andere
Debian\-distributies behoren\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Explanation: Installeer geen van Debian afkomstige pakketten met andere
Explanation: versies dan die uit de distributie stable of verwijder ze anders
Package: *
Pin: release a=stable
Pin\-Priority: 900

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
Met een passend bestand
\fBsources.list\fR(5)
en het bovenstaande preferences\-bestand, zal elk van de volgende commando\*(Aqs APT ertoe aanzetten om op te waarderen naar de nieuwste versie(s) uit
stable\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakketnaam\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
Het volgende commando zal APT ertoe aanzetten om het opgegeven pakket op te waarderen naar de allernieuwste versie uit de distributie
testing\&. Het pakket zal niet opnieuw opgewaardeerd worden tenzij die opdracht terug gegeven wordt\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakket\fR/testing
.fi
.if n \{\
.RE
.\}
.sp
.SS "Testing of Unstable volgen"
.PP
Het volgende preferences\-bestand van APT doet APT een hoge prioriteit toekennen aan pakketversies uit de distributie
testing, een lagere prioriteit aan pakketversies uit de distributie
unstable
en een buitensporig lage prioriteit aan pakketversies die tot andere
Debian\-distributies behoren\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Package: *
Pin: release a=testing
Pin\-Priority: 900

Package: *
Pin: release a=unstable
Pin\-Priority: 800

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
Met een passend bestand
\fBsources.list\fR(5)
en het bovenstaande preferences\-bestand, zal elk van de volgende commando\*(Aqs APT ertoe aanzetten om op te waarderen naar de nieuwste versie(s) uit
testing\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakketnaam\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
Het volgende commando zal APT ertoe aanzetten om het opgegeven pakket op te waarderen naar de allernieuwste versie uit de distributie
unstable\&. Nadien zal
\fBapt\-get upgrade\fR
het pakket opwaarderen naar de nieuwste versie uit
testing
als die recenter is dan de ge\(:installeerde versie en anders naar de nieuwste versie uit
unstable
als die recenter is dan de ge\(:installeerde versie\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakket\fR/unstable
.fi
.if n \{\
.RE
.\}
.sp
.SS "De evolutie van een uitgave volgen aan de hand van zijn codenaam"
.PP
Het volgende preferences\-bestand van APT doet APT een hogere prioriteit dan standaard (500) toekennen aan alle pakketversies die tot een distributie met de opgegeven codenaam behoren en een buitensporig lage prioriteit aan pakketversies die tot andere
Debian\-distributies, \-codenamen en \-archieven behoren\&. Merk op dat met deze APT\-voorkeur APT de overgang van een release zal volgen vanuit het archief
testing
naar
stable
en later
oldstable\&. Indien u bijvoorbeeld de voortgang in
testing
wilt volgen ongeacht de veranderende codenaam, dan moet u de hierboven gegeven configuratievoorbeelden gebruiken\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Explanation: Installeer geen van Debian afkomstige pakketversies behalve 
Explanation: die uit de distributie met codenaam buster of sid
Explanation: of verwijder ze in het andere geval
Package: *
Pin: release n=buster
Pin\-Priority: 900

Explanation: Debian unstable heeft steeds de codenaam sid
Package: *
Pin: release n=sid
Pin\-Priority: 800

Package: *
Pin: release o=Debian
Pin\-Priority: \-10
.fi
.if n \{\
.RE
.\}
.PP
Met een passend bestand
\fBsources.list\fR(5)
en het bovenstaande preferences\-bestand, zal elk van de volgende commando\*(Aqs APT ertoe aanzetten om op te waarderen naar de nieuwste versie(s) uit de release met de codenaam
buster\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakketnaam\fR
apt\-get upgrade
apt\-get dist\-upgrade
.fi
.if n \{\
.RE
.\}
.PP
Het volgende commando zal APT ertoe bewegen om het opgegeven pakket op te waarderen naar de nieuwste versie uit de distributie
sid\&. Nadien zal de opdracht
\fBapt\-get upgrade\fR
het pakket opwaarderen naar de meest recente versie uit
buster
indien dat een meer recente versie is dan die welke ge\(:installeerd is of anders naar de meest recente versie uit
sid
indien dat een meer recente versie is dan die welke ge\(:installeerd is\&.
.sp
.if n \{\
.RS 4
.\}
.nf
apt\-get install \fIpakket\fR/sid
.fi
.if n \{\
.RE
.\}
.sp
.SH "BESTANDEN"
.PP
/etc/apt/preferences
.RS 4
Bestand met versievoorkeuren\&. Dit is waar u "pinning" kunt opgeven\&. Dit is een voorkeur voor het ophalen van bepaalde pakketten uit een aparte pakketbron of uit een andere versie van een distributie\&. Configuratie\-item:
Dir::Etc::Preferences\&.
.RE
.PP
/etc/apt/preferences\&.d/
.RS 4
Bestandsfragmenten met versievoorkeuren\&. Configuratie\-item:
Dir::Etc::PreferencesParts\&.
.RE
.SH "ZIE OOK"
.PP
\fBapt-get\fR(8)
\fBapt-cache\fR(8)
\fBapt.conf\fR(5)
\fBsources.list\fR(5)
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[1]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEUR"
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
