'\" t
.\"     Title: sources.list
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 17\ \&augustus\ \&2018
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "SOURCES\&.LIST" "5" "17\ \&augustus\ \&2018" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sources.list \- Lijst met geconfigureerde gegevensbronnen van APT
.SH "OMSCHRIJVING"
.PP
De pakketbronnenlijst
/etc/apt/sources\&.list
en de bestanden die in
/etc/apt/sources\&.list\&.d/
te vinden zijn, werden ontwikkeld om gelijk welk aantal actieve bronnen en een variatie aan bronmedia te ondersteunen\&. In de bestanden wordt elke pakketbron op een aparte regel vermeld (de \('e\('en\-regelstijl) of ze bevatten uit meerdere regels bestaande elementen die per element een of meer pakketbronnen defini\(:eren (de deb822 stijl), waarbij de meest wenselijke pakketbron eerst komt (voor het geval een bepaalde versie in meer dan \('e\('en pakketbron te vinden is)\&. De op deze geconfigureerde pakketbronnen beschikbare informatie wordt opgevraagd met
\fBapt\-get update\fR
(of met een equivalent commando van een ander front\-end voor APT)\&.
.SH "SOURCES\&.LIST\&.D"
.PP
De map
/etc/apt/sources\&.list\&.d
biedt de mogelijkheid om items voor sources\&.list in afzonderlijke bestanden toe te voegen\&. Zoals beschreven wordt in de volgende twee secties, zijn twee verschillende bestandsindelingen toegelaten\&. Bestandsnamen moeten eindigen op
\&.list
of
\&.sources, afhankelijk van welke indeling ze bevatten\&. De bestandsnamen mogen enkel letters (a\-z en A\-Z), cijfers (0\-9), lage streepjes (_), koppeltekens (\-) en punten (\&.) bevatten\&. Is dit niet het geval, dan zal APT melden dat het een bestand overgeslagen heeft, tenzij dat bestand beantwoordt aan een patroon uit de configuratielijst
Dir::Ignore\-Files\-Silently
\- in dat geval zal het stilzwijgend overgeslagen worden\&.
.SH "INDELING IN \('E\('EN\-REGELSTIJL"
.PP
Bestanden met deze indeling hebben de extensie
\&.list\&. Iedere regel die een pakketbron specificeert, begint met het type (bijv\&.
deb\-src), gevolgd door opties en argumenten voor dat type\&. Een individueel item mag niet tot op een volgende regel doorlopen\&. Lege regels worden overgeslagen en het teken
#
ergens op een regel geeft aan dat de rest van die regel commentaar bevat\&. Als gevolg daarvan kan een item gedeactiveerd worden door de hele regel uit te commentari\(:eren\&. Indien er opties opgegeven moeten worden, worden ze van elkaar gescheiden door komma\*(Aqs en allemaal samen worden ze tussen rechte haakjes ([]) op de regel geplaatst na het type en daarvan gescheiden door een komma\&. Indien een optie meerdere waarden mag hebben, dan worden ze met een komma (,) van elkaar gescheiden\&. De naam van een optie wordt van zijn waarde(n) gescheiden met een gelijkheidsteken (=)\&. Multi\-waarde opties hebben ook
\-=
en
+=
als scheidingstekens\&. In plaats van de standaardwaarde(n) te vervangen door de opgegeven waarde(n), wijzigen zij de standaardwaarde(n) door er de opgegeven waarden uit te verwijderen of eraan toe te voegen\&.
.PP
Dit is de traditionele indeling die door alle versies van apt ondersteund wordt\&. Merk op dat niet alle opties die hieronder beschreven worden door alle versies van apt ondersteund worden\&. Merk ook op dat sommige oudere toepassingen die zelfstandig deze indeling ontleden wellicht geen opties zullen verwachten, aangezien die ongebruikelijk waren voor de invoering van multi\-architectuurondersteuning\&.
.SH "INDELING IN DEB822\-STIJL"
.PP
Bestanden met deze indeling hebben de extensie
\&.sources\&. Op het gebied van de syntaxis is de indeling gelijkaardig aan andere bestanden die door Debian en zijn derivaten gebruikt worden, zoals de metadatabestanden die apt ophaalt bij de geconfigureerde pakketbronnen of het bestand
debian/control
in een Debian broncodebestand\&. Individuele items worden van elkaar gescheiden door een witregel\&. Bijkomende witregels worden genegeerd en het teken
#
aan het begin van een regel markeert de volledige regel als commentaar\&. Een item kan dus gedeactiveerd worden door elke regel die onderdeel is van dat item, uit te commentari\(:eren\&. Maar meestal is het eenvoudiger om het item te deactiveren door er het veld "Enabled: no" aan toe te voegen\&. Dat veld verwijderen of het instellen op yes, activeert het item opnieuw\&. Opties gebruiken dezelfde syntaxis als elk ander veld: een veldnaam gescheiden van zijn waarde(n) door een dubbele punt (:) en optionele spaties\&. Merk in het bijzonder op dat meerdere waarden onderling gescheiden worden door witruimte (zoals spaties, tabs en regeleindes) en niet door komma\*(Aqs, zoals het geval is bij de \('e\('en\-regelindeling\&. Multi\-waarde velden, zoals
Architectures, kennen ook
Architectures\-Add
en
Architectures\-Remove
om de standaardwaarde aan te passen in plaats van ze te vervangen\&.
.PP
Dit is een nieuwe indeling die door apt zelf ondersteund wordt sinds versie 1\&.1\&. Eerdere versies negeren dergelijke bestanden met een kennisgevingsbericht zoals eerder beschreven\&. Het is de bedoeling dat deze indeling gaandeweg de standaardindeling wordt en dat de eerder beschreven \('e\('en\-regelstijl uitgefaseerd wordt, vermits het zowel voor mensen als voor machines makkelijker is om in deze nieuwe indeling items aan te maken, uit te breiden en te wijzigen, in het bijzonder als er een heleboel pakketbronnen en/of opties in het spel zijn\&. Ontwikkelaars die met pakketbronnen van apt werken en/of ze ontleden worden sterk aangemoedigd om ondersteuning voor deze indeling toe te voegen en om met het APT\-team contact te nemen om dit werk te co\(:ordineren en met elkaar te delen\&. Gebruikers kunnen nu reeds ongehinderd op deze indeling overschakelen, maar kunnen eventueel problemen ondervinden met software die deze nieuwe indeling nog niet ondersteunt\&.
.SH "DE TYPES DEB EN DEB\-SRC: ALGEMENE INDELING"
.PP
Het type
deb
verwijst naar een typisch Debian\-archief met twee niveaus,
distributie/component\&. De
distributie
is over het algemeen de naam van een suite zoals
stable
of
testing
of een codenaam zoals
stretch
of
buster, terwijl component een van de volgende kan zijn:
main,
contrib
of
non\-free\&. Het type
deb\-src
verwijst in dezelfde vorm als het type
deb
naar de broncode van een Debian distributie\&. Om bronnenindexen te kunnen ophalen is een
deb\-src\-regel noodzakelijk\&.
.PP
De indeling van twee items in de \('e\('en\-regelstijl met de types
deb
en
deb\-src, ziet er zo uit:
.sp
.if n \{\
.RS 4
.\}
.nf
deb [ optie1=waarde1 optie2=waarde2 ] uri suite [component1] [component2] [\&.\&.\&.]
deb\-src [ optie1=waarde1 optie2=waarde2 ] uri suite [component1] [component2] [\&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.PP
Anderzijds ziet het equivalent van dit item in deb822\-stijl er als volgt uit:
.sp
.if n \{\
.RS 4
.\}
.nf
     Types: deb deb\-src
     URIs: uri
     Suites: suite
     Components: [component1] [component2] [\&.\&.\&.]
     optie1: waarde1
     optie2: waarde2
   
.fi
.if n \{\
.RE
.\}
.PP
De URI voor het type
deb
moet de basis vermelden van de Debian distributie waar APT de benodigde informatie kan vinden\&.
suite
kan een exact pad opgeven en in dat geval moeten de componenten weggelaten worden en moet
suite
eindigen op een slash (/)\&. Dit is nuttig in een geval waarbij enkel een specifieke sub\-sectie van het archief dat door de URI aangeduid wordt, van belang is\&. Indien
suite
geen exact pad opgeeft, moet minstens \('e\('en
component
vermeld worden\&.
.PP
suite
kan ook een variabele,
$(ARCH), bevatten, die omgezet wordt naar de Debian architectuur (zoals
amd64
of
armel) die op het systeem in gebruik is\&. Dit laat toe om archtectuuronafhankelijke
sources\&.list\-bestanden te gebruiken\&. Over het algemeen is dit enkel van belang wanneer een exact pad opgegeven wordt\&. Anders zal
APT
automatisch een URI genereren met de huidige architectuur\&.
.PP
Als uit een bepaalde locatie een subset van alle beschikbare distributies of componenten gewenst wordt, kan het bij het hanteren van de \('e\('en\-regelstijl nodig zijn om meerdere regels voor dezelfde URI te gebruiken, aangezien er per regel slechts \('e\('en distributie opgegeven kan worden\&. Nadat APT intern een complete set gegenereerd heeft, zal het de URI\-lijst sorteren en bijvoorbeeld meerdere verwijzingen naar eenzelfde computer op het internet, samenbundelen in eenzelfde verbinding\&. Dit is om niet op een ineffici\(:ente manier te werk te gaan door een FTP\-verbinding tot stand te brengen, die te sluiten, iets anders te doen en vervolgens opnieuw een verbinding te moeten maken met dezelfde computer\&. APT zet ook parallelle verbindingen op met verschillende computers om effectiever om te gaan met sites met een geringe bandbreedte\&.
.PP
Het is belangrijk om pakketbronnen in volgorde van voorkeur te vermelden met de grootste voorkeur eerst\&. Een typisch gebruik is een ordening volgens snelheid van snelst naar traagst (bijvoorbeeld een CD gevolgd door computers op een lokaal netwerk en tenslotte afgelegen internetcomputers)\&.
.PP
Bij wijze van voorbeeld zouden de pakketbronnen voor uw distributie er als volgt kunnen uitzien met de indeling in de \('e\('en\-regelstijl:
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stretch main contrib non\-free
deb http://security\&.debian\&.org stretch/updates main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
en als volgt met de indeling in de deb822\-stijl:
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main contrib non\-free

Types: deb
URIs: http://security\&.debian\&.org
Suites: stretch/updates
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.SH "DE TYPES DEB EN DEB\-SRC: OPTIES"
.PP
Bij elk pakketbronitem kunnen opties opgegeven worden om aan te passen welke bron gebruikt wordt en op welke manier er gegevens van opgehaald worden\&. Indeling, syntaxis en namen van de opties vari\(:eren naargelang het een \('e\('en\-regelstijl of een deb822\-stijl betreft, zoals eerder beschreven, maar met beide stijlen kunnen dezelfde opties gebruikt worden\&. Om het eenvoudig te houden vermelden we hier de veldnaam voor de deb822\-stijl en geven we de naam voor de \('e\('en\-regelstijl er tussen haakjes bij\&. Onthoud dat u multi\-waarde opties expliciet kunt vermelden, maar dat u daarnaast over de optie beschikt om ze aan te passen uitgaande van hun standaardwaarde\&. Maar hier geven we hun namen expliciet weer\&. Niet\-ondersteunde opties worden door alle versies van APT geruisloos genegeerd\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBArchitectures\fR
(\fBarch\fR) is een multi\-waarde optie waarmee opgegeven wordt voor welke architecturen er informatie opgehaald moet worden\&. Indien deze optie niet ingesteld werd, geldt als standaard alle architecturen die in de configuratieoptie
APT::Architectures
gedefinieerd zijn\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBLanguages\fR
(\fBlang\fR) is een multi\-waarde optie waarmee opgegeven wordt voor welke talen er informatie, zoals vertaalde pakketbeschrijvingen, opgehaald moet worden\&. Indien deze optie niet ingesteld werd, geldt als standaard alle talen die in de configuratieoptie
Acquire::Languages
gedefinieerd zijn\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBTargets\fR
(\fBtarget\fR) is een multi\-waarde optie waarmee opgegeven wordt welke downloadtargets apt uit deze pakketbron zal trachten op te halen\&. Indien deze optie niet gespecificeerd werd, wordt de standaardset gedefinieerd door het configuratiebereik
\fBAcquire::IndexTargets\fR
(targets worden aan de hand van hun naam gepreciseerd in het veld
Created\-By)\&. Daarenboven kunnen specifieke targets geactiveerd of gedeactiveerd worden door het veld
Identifier
als een optie met een booleaanse waarde te gebruiken in plaats van op deze multi\-waarde optie beroep te doen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBPDiffs\fR
(\fBpdiffs\fR) is een yes/no (ja/nee) waarde die regelt of APT moet proberen om PDiffs op te halen om oude indexen bij te werken in plaats van de volledige nieuwe indexen te downloaden\&. De waarde van deze optie wordt genegeerd als de pakketbron niet aangeeft dat er PDiffs beschikbaar zijn\&. Standaard is dit de waarde van de optie met eenzelfde naam voor een specifiek indexbestand, zoals gedefinieerd in het bereik
\fBAcquire::IndexTargets\fR, dat zelf als standaard de waarde krijgt van de configuratieoptie
\fBAcquire::PDiffs\fR, die op zijn beurt standaard op
yes
ingesteld staat\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBBy\-Hash\fR
(\fBby\-hash\fR) kan als waarde hebben
yes,
no
of
force
en regelt of APT moet proberen de indexen te bekomen via een URI die geconstrueerd wordt op basis van de hash\-som van het verwachte bestand, in plaats van de welbekende stabiele bestandsnaam van het indexbestand te gebruiken\&. Dit gebruiken kan een discrepantie tussen hash\-sommen voorkomen, maar het vereist wel een spiegelserver die dit ondersteunt\&. De waarde
yes
activeert en
no
deactiveert het gebruik van deze functionaliteit in het geval de pakketbron aangeeft dit te ondersteunen, terwijl
force
deze functionaliteit activeert, ongeacht wat de pakketbron aangeeft\&. Standaard is dit de waarde van de optie met eenzelfde naam voor een specifiek indexbestand, zoals gedefinieerd in het bereik
\fBAcquire::IndexTargets\fR, dat zelf als standaard de waarde krijgt van de configuratieoptie
\fBAcquire::By\-Hash\fR, die op zijn beurt standaard op
yes
ingesteld staat\&.
.RE
.sp
Daarnaast zijn er opties die, als ze ingesteld worden, betrekking hebben op
\fIalle\fR
pakketbronnen met dezelfde URI en Suite, waardoor ze ingesteld moeten worden voor alle soortgelijke items en er niet gevarieerd kan worden tussen verschillende componenten\&. Als er zich dergelijke anomalie\(:en manifesteren, zal APT ze proberen te ontdekken en verbeteren\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBAllow\-Insecure\fR
(\fBallow\-insecure\fR),
\fBAllow\-Weak\fR
(\fBallow\-weak\fR) en
\fBAllow\-Downgrade\-To\-Insecure\fR
(\fBallow\-downgrade\-to\-insecure\fR) zijn booleaanse waarden die allemaal standaard de waarde
no
hebben\&. Indien ze op
yes
ingesteld worden, omzeilen ze delen van
\fBapt-secure\fR(8)
en daarom zouden ze niet lichtzinnig gebruikt moeten worden!
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBTrusted\fR
(\fBtrusted\fR) is een drie\-status waarde die als standaardgedrag heeft dat APT uitmaakt of een pakketbron als betrouwbaar aanzien wordt, dan wel of er een waarschuwing getoond moet worden vooraleer bijvoorbeeld pakketten van die pakketbron ge\(:installeerd worden\&. Deze optie kan gebruikt worden om die beslissing te omzeilen\&. De waarde
yes
zegt APT om die pakketbron steeds als betrouwbaar te beschouwen, zelfs als ze niet slaagt bij authenticatietoetsen\&. Ze schakelt delen van
\fBapt-secure\fR(8)
uit en zou daarom enkel gebruikt mogen worden in een lokale en betrouwbare context (als men ze hoe dan ook al zou gebruiken), aangezien anders de beveiliging verbroken wordt\&. De waarde
no
doet het tegenovergestelde en zorgt ervoor dat een pakketbron behandeld wordt als onbetrouwbaar, zelfs al was ze succesvol bij de authenticatietoetsen\&. De standaardwaarde kan niet expliciet ingesteld worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBSigned\-By\fR
(\fBsigned\-by\fR) is an option to require a repository to pass
\fBapt-secure\fR(8)
verification with a certain set of keys rather than all trusted keys apt has configured\&. It is specified as a list of absolute paths to keyring files (have to be accessible and readable for the
_apt
system user, so ensure everyone has read\-permissions on the file) and fingerprints of keys to select from these keyrings\&. If no keyring files are specified the default is the
trusted\&.gpg
keyring and all keyrings in the
trusted\&.gpg\&.d/
directory (see
\fBapt\-key fingerprint\fR)\&. If no fingerprint is specified all keys in the keyrings are selected\&. A fingerprint will accept also all signatures by a subkey of this key, if this isn\*(Aqt desired an exclamation mark (!) can be appended to the fingerprint to disable this behaviour\&. The option defaults to the value of the option with the same name if set in the previously acquired
Release
file of this repository (only fingerprints can be specified there through)\&. Otherwise all keys in the trusted keyrings are considered valid signers for this repository\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBCheck\-Valid\-Until\fR
(\fBcheck\-valid\-until\fR) is een yes/no (ja/nee) waarde die regelt of APT moet proberen om replay\-aanvallen te ontdekken\&. De maker van een pakketbron kan een tijdstip bepalen tot wanneer de gegevens die door de pakketbron ter beschikking gesteld worden, als geldig beschouwd mogen worden\&. Als dat tijdstip aangebroken is en er geen nieuwe gegevens ter beschikking gesteld werden, zullen de gegevens als vervallen beschouwd worden en er zal een foutmelding gegeven worden\&. Dit verhoogt niet enkel de veiligheid, aangezien een aanvaller met kwade bedoelingen niet eeuwig oude gegevens kan blijven versturen om op die manier een gebruiker van een opwaardering af te houden, het helpt gebruikers ook om spiegelservers die niet langer bijgewerkt worden te detecteren\&. Sommige pakketbronnen, zoals historische archieven, worden evenwel met opzet niet langer bijgewerkt en om die reden kan deze toets uitgezet worden door deze optie op
no
in te stellen\&. Als standaard geldt de waarde van de configuratieoptie
\fBAcquire::Check\-Valid\-Until\fR, die op haar beurt
yes
als standaard heeft\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBValid\-Until\-Min\fR
(\fBvalid\-until\-min\fR) en
\fBValid\-Until\-Max\fR
(\fBvalid\-until\-max\fR) kunnen gebruikt worden om, uitgedrukt in seconden, de periode tot wanneer gegevens van deze pakketbron als geldig beschouwd mogen worden, te verlengen of te verkorten\&. \-Max kan vooral nuttig zijn om uw eigen waarde in te stellen in het geval van een pakketbron met een Release\-bestand waarin het veld Valid\-Until ontbreekt, terwijl \-Min gebruikt kan worden om de geldigheidsduur te verlengen van een zelden opgewaardeerde (lokale) spiegelserver van een vaker bijgewerkt, maar moeilijker toegankelijk archief (dat ook vermeld staat in sources\&.list)\&. Op die manier hoeft men deze toets niet volledig uit te schakelen\&. Als standaard geldt de waarde van de configuratieopties
\fBAcquire::Min\-ValidTime\fR
en
\fBAcquire::Max\-ValidTime\fR, die beide standaard niet ingesteld zijn\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBCheck\-Date\fR
(\fBcheck\-date\fR) is een waarde van het type yes/no\&. Ze regelt of APT de tijd op de machine als correct moet beschouwen en dus tijdgerelateerde toetsingen moet uitvoeren, zoals controleren of een Release\-bestand zich niet in de toekomst situeert\&. Als men deze optie uitzet zet men ook de hierboven vermelde optie
\fBCheck\-Valid\-Until\fR
uit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBDate\-Max\-Future\fR
(\fBdate\-max\-future\fR) regelt hoe ver in de toekomst een pakketbron zich mag situeren\&. Is standaard ingesteld op de waarde van de configuratieoptie
\fBAcquire::Max\-FutureTime\fR
die standaard de waarde van 10 seconden heeft\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBInRelease\-Path\fR
(\fBinrelease\-path\fR) bepaalt het pad naar het InRelease\-bestand ten opzichte van de normale positie van een
InRelease\-bestand\&. Standaard staat deze optie uit en zal APT proberen een
InRelease\-bestand op te halen, en indien dat niet lukt, een
Release\-bestand en het daaraan gekoppelde
Release\&.gpg\-bestand\&. Als deze optie ingesteld wordt, zal het opgegeven pad gebruikt worden in plaats van het InRelease\-bestand en wordt het terugvallen op
Release\-bestanden uitgeschakeld\&.
.RE
.sp
.SH "URI\-SPECIFICATIE"
.PP
De momenteel herkende URI\-types zijn:
.PP
\fBhttp\fR (\fBapt-transport-http\fR(1))
.RS 4
De methode http geeft een HTTP\-server op voor een archief\&. Dit is de meest gebruikelijke methode\&. De URI zelf kan rechtstreeks login\-informatie bevatten als dat door het archief vereist wordt, maar de voorkeur moet gegeven worden aan het gebruik van
\fBapt_auth.conf\fR(5)\&. De methode biedt ook ondersteuning voor SOCKS5\- en HTTP(S)\-proxy\*(Aqs, ofwel geconfigureerd via een apt\-specifieke configuratie, of gespecificeerd met de omgevingsvariabele
\fBhttp_proxy\fR
volgens de indeling
\fIhttp://gebruiker:wachtwoord@server:poort/\fR
(er vanuit gaand dat het om een HTTP\-proxy gaat die authenticatie vereist)\&. De authenticatie\-informatie voor proxy\*(Aqs kan ook verstrekt worden via
\fBapt_auth.conf\fR(5)\&.
.sp
Merk op dat deze authenticatiemethodes onveilig zijn, aangezien de volledige communicatie met de externe server (of de proxy) onversleuteld verloopt\&. Daardoor kan een voldoende onderlegde aanvaller de logingegevens bekijken en opslaan evenals de rest van de interactie\&. De aanvaller kan evenwel de communicatie
\fIniet\fR
be\(:invloeden, vermits het databeveiligingsmodel dat toegepast wordt door APT, onafhankelijk van de gekozen transportmethode functioneert\&. Raadpleeg voor details
\fBapt-secure\fR(8)\&.
.RE
.PP
\fBhttps\fR (\fBapt-transport-https\fR(1))
.RS 4
De methode https geeft een HTTPS\-server op voor een archief en is inzake gebruik en beschikbare opties erg vergelijkbaar met de http\-methode\&. Het grote verschil is dat de communicatie tussen apt en de server (of de proxy) versleuteld verloopt\&. Merk op dat de versleuteling niet verhindert dat een aanvaller kan te weten komen met welke server (of welke proxy) apt communiceert\&. En eventueel kan deze via een meer diepgaande analyse toch nog achterhalen welke gegevens gedownload werden\&. Indien dit een bekommernis is, kunnen de op Tor gebaseerde methodes die later behandeld worden, een adequaat alternatief vormen\&.
.RE
.PP
\fBmirror\fR, \fBmirror+\fR\fB\fImethode\fR\fR (\fBapt-transport-mirror\fR(1))
.RS 4
De methode mirror (spiegelserver) geeft de locatie van een spiegelserverlijst aan\&. Standaard is de methode die voor de locatie gebruikt wordt,
http, maar gelijk welke andere methode kan gebruikt worden via
\fBmirror+\fR\fB\fImethode\fR\fR\&. De spiegelserverlijst zelf kan veel verschillende URI\*(Aqs bevatten voor spiegelservers, welke de APT\-cli\(:ent op transparante wijze kan uitpikken, kiezen en erop terugvallen om op die manier bij te dragen tot het verdelen van de werklast over de beschikbare spiegelservers en ervoor te zorgen dat clients gegevens kunnen verkrijgen, zelfs als bepaalde geconfigureerde spiegelservers niet beschikbaar zijn\&.
.RE
.PP
\fBfile\fR
.RS 4
De methode file laat toe om gelijk welke map uit het bestandssysteem als een archief te beschouwen\&. Dit is nuttig voor aankoppelingen via NFS, voor lokale spiegelservers en lokale archieven\&.
.RE
.PP
\fBcdrom\fR
.RS 4
De methode cdrom laat APT toe om een lokaal CD\-, DVD\- of USB\-station te gebruiken en media te wisselen\&. Gebruik het programma
\fBapt-cdrom\fR(8)
om regels met CD\-pakketbronnen aan te maken in de lijst met pakketbronnen\&.
.RE
.PP
\fBftp\fR
.RS 4
De methode ftp geeft een FTP\-server op voor een archief\&. Het gebruik van FTP is op de terugweg ten voordele van
http
en
https
en veel archieven hebben ofwel nooit FTP\-toegang aangeboden of trekken die terug in\&. Indien u deze methode nog steeds nodig heeft, zijn er veel configuratieopties voor beschikbaar binnen de ruimte
Acquire::ftp\&. Ze worden in
\fBapt.conf\fR(5)
gedetailleerd\&.
.sp
Noteer dat een FTP\-proxy opgegeven kan worden met de omgevingsvariabele
\fBftp_proxy\fR\&. Met deze omgevingsvariabele en
\fIenkel\fR
daarmee kan ook een HTTP\-proxy opgegeven worden (HTTP proxyservers kunnen vaak omgaan met FTP\-URL\*(Aqs)\&. Proxy\*(Aqs die HTTP gebruiken en in het configuratiebestand vermeld staan worden genegeerd\&.
.RE
.PP
\fBcopy\fR
.RS 4
De methode copy is identiek aan de methode file behalve dat pakketten gekopieerd worden naar de cache\-map in plaats van ze rechtstreeks op hun locatie te gebruiken\&. Dit is nuttig voor gebruikers van verwijderbare media om met behulp van APT bestanden te kopi\(:eren\&.
.RE
.PP
\fBrsh\fR, \fBssh\fR
.RS 4
De methode rsh/ssh maakt gebruik van RSH/SSH om een verbinding met een externe computer te maken en als een welbepaalde gebruiker toegang te krijgen tot de bestanden\&. Voorafgaandelijke configuratie van rhosts of RSA\-sleutels wordt aanbevolen\&. De standaardcommando\*(Aqs
\fBfind\fR
en
\fBdd\fR
worden gebruikt om de overdracht van bestanden van de externe computer uit te voeren\&.
.RE
.PP
nog andere herkenbare URI\-types toevoegen
.RS 4
APT kan uitgebreid worden met extra methodes die door andere optionele pakketten ter beschikking gesteld worden en die moeten voldoen aan het naamgevingsschema
apt\-transport\-\fImethode\fR\&. Het APT\-team onderhoudt bijvoorbeeld ook het pakket
apt\-transport\-tor, dat methodes aanbiedt om toegang te krijgen tot HTTP\- en HTTPS\-URI\*(Aqs, waarbij een route via het Tor\-netwerk genomen wordt\&.
.RE
.SH "VOORBEELDEN"
.PP
Gebruikt het lokaal opgeslagen (of via NFS aangekoppelde) archief in /home/apt/debian voor stable/main, stable/contrib, en stable/non\-free\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/apt/debian stable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: file:/home/apt/debian
Suites: stable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Zoals hierboven, behalve dat hier de distributie unstable (distributie in ontwikkeling) gebruikt wordt\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/apt/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: file:/home/apt/debian
Suites: unstable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Specificatie voor de bronbestanden van het voorgaande\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb\-src file:/home/apt/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb\-src
URIs: file:/home/apt/debian
Suites: unstable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
De eerste regel haalt pakketinformatie op voor de architecturen uit
APT::Architectures
terwijl de tweede steeds
amd64
en
armel
ophaalt\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stretch main
deb [ arch=amd64,armel ] http://deb\&.debian\&.org/debian stretch main
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main

Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main
Architectures: amd64 armel
.fi
.if n \{\
.RE
.\}
.PP
Gebruikt HTTP om toegang te krijgen tot het archief van archive\&.debian\&.org en gebruikt daar enkel het gebied hamm/main\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://archive\&.debian\&.org/debian\-archive hamm main
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://archive\&.debian\&.org/debian\-archive
Suites: hamm
Components: main
.fi
.if n \{\
.RE
.\}
.PP
Gebruikt FTP om toegang te krijgen tot het archief op ftp\&.debian\&.org onder de map debian en gebruikt er enkel het gebied stretch/contrib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian stretch contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: ftp://ftp\&.debian\&.org/debian
Suites: stretch
Components: contrib
.fi
.if n \{\
.RE
.\}
.PP
Gebruikt FTP om toegang te krijgen tot het archief op ftp\&.debian\&.org onder de map debian en gebruikt er enkel het gebied unstable/contrib\&. Indien deze regel en die uit het voorgaande voorbeeld allebei voorkomen in
sources\&.list
zal een enkele FTP\-verbinding gebruikt worden voor beide regels met pakketbronnen\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian unstable contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: ftp://ftp\&.debian\&.org/debian
Suites: unstable
Components: contrib
.fi
.if n \{\
.RE
.\}
.PP
Gebruikt HTTP om toegang te krijgen tot het archief op ftp\&.tlh\&.debian\&.org onder de map universe en gebruikt op i386\-computers enkel bestanden die te vinden zijn onder
unstable/binary\-i386
en op amd64\-computers bestanden onder
unstable/binary\-amd64
en zo verder voor andere ondersteunde architecturen\&. [Merk op dat dit voorbeeld enkel toont hoe de substitutievariabele moet gebruikt worden; offici\(:ele debian\-archieven worden niet op die manier georganiseerd]
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://ftp\&.tlh\&.debian\&.org/universe unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://ftp\&.tlh\&.debian\&.org/universe
Suites: unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.PP
Gebruikt HTTP om binaire pakketten en broncode uit de suites stable, testing en unstable en uit de componenten main en contrib op te halen\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stable main contrib
deb\-src http://deb\&.debian\&.org/debian stable main contrib
deb http://deb\&.debian\&.org/debian testing main contrib
deb\-src http://deb\&.debian\&.org/debian testing main contrib
deb http://deb\&.debian\&.org/debian unstable main contrib
deb\-src http://deb\&.debian\&.org/debian unstable main contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb deb\-src
URIs: http://deb\&.debian\&.org/debian
Suites: stable testing unstable
Components: main contrib
.fi
.if n \{\
.RE
.\}
.SH "ZIE OOK"
.PP
\fBapt-get\fR(8),
\fBapt.conf\fR(5),
/usr/share/doc/apt\-doc/acquire\-additional\-files\&.md\&.gz
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[1]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
