'\" t
.\"     Title: sources.list
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 17\ \&ao\(^ut\ \&2018
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: French
.\"
.TH "SOURCES\&.LIST" "5" "17\ \&ao\(^ut\ \&2018" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
sources.list \- Liste des sources de donn\('ees APT configur\('ees
.SH "DESCRIPTION"
.PP
Le fichier de liste de sources
/etc/apt/sources\&.list
et les fichiers contenus dans
/etc/apt/sources\&.list\&.d/
sont con\(,cus pour pouvoir g\('erer un nombre quelconque de sources actives et de m\('edias\&. Le fichier donne une source par ligne (One\-Line style) ou fournit des paragraphes multilignes d\('efinissant une ou plusieurs sources par paragraphe (style deb822), avec les sources prioritaires en premier (dans le cas o\(`u il y a une seule version disponible \(`a partir de plus d\*(Aqune source)\&. L\*(Aqinformation relative aux sources configur\('ees est r\('ecup\('er\('ee par la commande
\fBapt\-get update\fR
(ou par une commande \('equivalente avec une autre interface \(`a APT)\&.
.SH "SOURCES\&.LIST\&.D"
.PP
Le r\('epertoire
/etc/apt/sources\&.list\&.d
permet de sp\('ecifier des sources de paquets dans des fichiers distincts\&. Deux formats de fichiers diff\('erents sont permis comme cela est d\('ecrit dans les deux sections suivantes\&. Les noms de fichier doivent se terminer par
\&.list
ou par
\&.sources
selon le format fourni\&. Ils ne peuvent contenir que des lettres (a\-z et A\-Z), des chiffres (0\-9), des caract\(`eres de soulignement (_), des tirets (\-) et des points (\&.)\&. Dans le cas contraire, APT affichera un avertissement indiquant qu\*(Aqil a ignor\('e un fichier si celui\-ci ne correspond par \(`a un motif d\('efini dans
Dir::Ignore\-Files\-Silently
(les fichiers correspondant \(`a cette variable de configuration \('etant, eux, ignor\('es silencieusement)\&.
.SH "FORMAT ONE\-LINE\-STYLE"
.PP
Les entr\('ees individuelles ne peuvent pas se poursuivre sur la ligne suivante\&. Les lignes vides sont ignor\('ees et un caract\(`ere
#
n\*(Aqimporte o\(`u sur une ligne signale que le reste de la ligne est un commentaire\&. Par cons\('equent, une entr\('ee peut \(^etre d\('esactiv\('ee en commentant la totalit\('e de la ligne\&. Si plusieurs options doivent \(^etre fournies, elles sont s\('epar\('ees par des espaces et sont entour\('ees toutes ensembles par des crochets ([]) inclus sur la ligne apr\(`es le type s\('epar\('e par un espace\&. Si une option permet plusieurs valeurs, elles sont s\('epar\('ees les unes des autres par une virgule (,)\&. Un nom d\*(Aqoption est s\('epar\('e de ses options par une signe \('egal (=)\&. Des options \(`a plusieurs valeurs disposent aussi des s\('eparateurs
\-=
et
+=, qui, au lieu de remplacer la valeur par d\('efaut par la ou les valeurs donn\('ees, modifient la ou les valeurs par d\('efaut pour supprimer ou inclure les valeurs donn\('ees\&.
.PP
Il s\*(Aqagit du format traditionnel, g\('er\('e par toute les version de APT\&. Veuillez noter que toutes les options d\('ecrites plus bas ne sont pas prises en charge par toutes les versions d\*(AqAPT\&. Notez aussi que certaine des plus anciennes applications qui analysent ce format elles\-m\(^emes ne s\*(Aqattendent pas \(`a rencontrer des options qui \('etaient rares avant l\*(Aqintroduction de la prise en charge multi\-architecture\&.
.SH "FORMAT DEB822\-STYLE"
.PP
Les fichiers dans ce format poss\(`edent l\*(Aqextension
\&.sources\&. La syntaxe du format est similaire \(`a celle des autres fichiers utilis\('es par Debian et ses d\('eriv\('es, comme les fichiers de m\('etadonn\('ees qu\*(AqAPT t\('el\('echarge des sources configur\('ees ou le fichier
debian/control
d\*(Aqun paquet source de Debian\&. Les entr\('ees individuelles sont s\('epar\('ees par une ligne vide\ \&; les lignes vides suppl\('ementaires sont ignor\('ees et un caract\(`ere
#
en d\('ebut de ligne signale la ligne comme un commentaire\&. Une entr\('ee, par cons\('equent, peut \(^etre d\('esactiv\('ee en commentant chaque ligne appartenant au paragraphe, mais il est habituellement plus facile d\*(Aqajouter le champ \(Fo\ \&Enabled: no\ \&\(Fc au paragraphe pour d\('esactiver l\*(Aqentr\('ee\&. Retirer ce champ ou le d\('efinir \(`a \(Fo\ \&yes\ \&\(Fc le r\('eactive\&. Les options ont la m\(^eme syntaxe que tous les autres champs\ \&: un nom de champ s\('epar\('e par le caract\(`ere deux\-points (:) et \('eventuellement des valeurs s\('epar\('ees par des espaces\&. Veuillez noter particuli\(`erement que des valeurs multiples sont s\('epar\('ees par des espacements (espaces, tabulations ou nouvelles lignes) et non par des virgules comme dans le format \(Fo\ \&One\-Line\ \&\(Fc\&. Les champs multivaleurs comme
Architectures
disposent aussi des options
Architectures\-Add
et
Architectures\-Remove
pour modifier la valeur par d\('efaut plut\(^ot que de la remplacer\&.
.PP
Il s\*(Aqagit d\*(Aqun nouveau format pris en charge par APT lui\-m\(^eme depuis la version\ \&1\&.1\&. Les versions pr\('ec\('edentes ignorent ce type de fichier avec un message d\*(Aqavertissement tel que d\('ecrit pr\('ec\('edemment\&. L\*(Aqobjectif est de faire de ce format le format par d\('efaut, et de rendre obsol\(`ete le format \(Fo\ \&One\-Line\-Style\ \&\(Fc d\('ecrit plus haut, parce qu\*(Aqil est plus facile \(`a cr\('eer, \(`a \('etendre et \(`a modifier pour les humains comme pour les machines, surtout s\*(Aqil inclut beaucoup de sources et/ou d\*(Aqoptions\&. Les d\('eveloppeurs qui travaillent avec les sources apt ou les analysent sont fortement encourag\('es \(`a ajouter la prise en charge de ce format et \(`a prendre contact avec l\*(Aq\('equipe APT pour coordonner et partager ce travail\&. Les utilisateurs sont libres d\*(Aqadopter d\('ej\(`a ce format, mais peuvent se confronter \(`a des probl\(`emes avec les logiciels qui ne le g\(`erent pas encore\&.
.SH "LES TYPES DEB ET DEB\-SRC\ \&: FORMAT G\('EN\('ERAL"
.PP
Le type
deb
d\('ecrit une archive Debian classique \(`a deux niveaux,
distribution/composant\&.
distribution
peut prendre l\*(Aqune des valeurs suivantes\ \&: un nom de suite tel que
stable
ou
testing
ou bien un nom de code comme
stretch
ou
buster, alors que composant prend les valeurs\ \&:
main,
contrib
ou
non\-free\&. Le type
deb\-src
d\('ecrit une archive de distribution de code source pour une distribution Debian dans le m\(^eme format que le type
deb\&. Une ligne
deb\-src
est n\('ecessaire pour r\('ecup\('erer les index des sources\&.
.PP
Le format de deux entr\('ees du genre \(Fo\ \&One\-Line\-Style\ \&\(Fc utilisant les types
deb
et
deb\-src
est\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb [ option1=value1 option2=value2 ] uri suite [component1] [component2] [\&.\&.\&.]
deb\-src [ option1=value1 option2=value2 ] uri suite [component1] [component2] [\&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.PP
Autrement, l\*(Aqentr\('ee \('equivalente de style deb822 ressemble \(`a ceci\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
     Types: deb deb\-src
     URIs: uri
     Suites: suite
     Components: [component1] [component2] [\&.\&.\&.]
     option1: value1
     option2: value2
   
.fi
.if n \{\
.RE
.\}
.PP
L\*(AqURI de type
deb
doit indiquer la base de la distribution Debian dans laquelle APT trouvera les informations dont il a besoin\&.
suite
peut sp\('ecifier le chemin exact\ \&: dans ce cas, on doit omettre les composants et
suite
doit se terminer par une barre oblique (/)\&. C\*(Aqest utile quand seul un sous\-r\('epertoire particulier de l\*(Aqarchive d\('ecrite par cet URI est int\('eressant\&. Quand
suite
n\*(Aqindique pas un chemin exact, un
composant
au moins doit \(^etre pr\('esent\&.
.PP
suite
peut aussi contenir une variable
$(ARCH), qui sera remplac\('ee par l\*(Aqarchitecture Debian (comme
amd64
ou
armel) sur laquelle s\*(Aqex\('ecute le syst\(`eme\&. On peut ainsi utiliser un fichier
sources\&.list
qui ne d\('epend pas d\*(Aqune architecture\&. En g\('en\('eral, ce n\*(Aqest int\('eressant que si l\*(Aqon indique un chemin exact\ \&; sinon
APT
cr\('ee automatiquement un URI en fonction de l\*(Aqarchitecture effective\&.
.PP
Particuli\(`erement lorsqu\*(Aqon utilise le format \(Fo\ \&One\-Line\-Style\ \&\(Fc, puisqu\*(Aqon ne peut indiquer qu\*(Aqune seule distribution par ligne, il peut \(^etre n\('ecessaire de disposer le m\(^eme URI sur plusieurs lignes quand on veut acc\('eder \(`a un sous\-ensemble des distributions ou composants disponibles \(`a cette adresse\&. APT trie les URI apr\(`es avoir cr\('ee pour lui\-m\(^eme la liste compl\(`ete\ \&; il regroupe les r\('ef\('erences multiples au m\(^eme h\(^ote Internet en vue d\*(Aqune connexion unique et il \('evite ainsi, par exemple, d\*(Aq\('etablir une connexion FTP, de la fermer, faire autre chose, puis d\*(Aq\('etablir encore cette connexion\&. Cette fonctionnalit\('e permet l\*(Aqacc\(`es \(`a des sites FTP surcharg\('es qui limitent le nombre de connexions simultan\('ees pour les utilisateurs anonymes\&. APT parall\('elise aussi les connexions \(`a diff\('erents h\(^otes pour tirer plus efficacement parti des sites \(`a faible bande passante\&.
.PP
Il est important d\*(Aqindiquer les sources par ordre de pr\('ef\('erence, la source principale apparaissant en premier\&. Un tri est fait, de la plus rapide \(`a la plus lente\ \&; par exemple, un CD suivi par les h\(^otes d\*(Aqun r\('eseau local, puis les h\(^otes distants\&.
.PP
\(`A titre d\*(Aqexemple, les sources de votre distribution au format \(Fo\ \&One\-Line\-Style\ \&\(Fc pourraient ressembler \(`a ceci\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stretch main contrib non\-free
deb http://security\&.debian\&.org stretch/updates main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
ou \(`a ceci au format de style deb822\ \&:
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main contrib non\-free

Types: deb
URIs: http://security\&.debian\&.org
Suites: stretch/updates
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.SH "LES TYPES DEB ET DEB\-SRC\ \&: OPTIONS"
.PP
Chaque entr\('ee de source peut avoir des options sp\('ecifi\('ees pour modifier la source \(`a laquelle acc\('eder et comment les donn\('ees y sont r\('ecup\('er\('ees\&. Le format, la syntaxe et les noms des options peuvent \(^etre diff\('erents entre le format \(Fo\ \&One\-Line\-Style\ \&\(Fc et le format de style deb822, mais les m\(^emes options sont disponibles dans les deux formats\&. Pour simplifier, nous listons les noms de champ avec deb822 et fournissons le nom \(Fo\ \&One\-Line\ \&\(Fc entre parenth\(`eses\&. Il faut se souvenir que en plus du r\('eglage explicite des options multi\-valeurs, il y a aussi l\*(Aqoption de les modifier en se basant sur les valeurs par d\('efaut, mais nous ne listons pas ces noms explicitement ici\&. Les options non prises en charge sont ignor\('ees par toutes les version d\*(AqAPT\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBArchitectures\fR
(\fBarch\fR) est une option multivaleur pour d\('efinir les architectures pour lesquelles l\*(Aqinformation doit \(^etre t\('el\('echarg\('ee\&. Si cette option n\*(Aqest pas utilis\('ee, l\*(Aqoption par d\('efaut est toutes les architectures d\('efinies par l\*(Aqoption de configuration
APT::Architectures\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBLanguages\fR
(\fBlang\fR) est une option multivaleur pour d\('efinir les langues pour lesquelles les informations, telles que les descriptions de paquet traduites, doivent \(^etre t\('el\('echarg\('ees\&. Si cette option n\*(Aqest pas utilis\('ee, l\*(Aqoption par d\('efaut est toutes les langues d\('efinies par l\*(Aqoption de configuration
\fBAcquire::Languages\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBTargets\fR
(\fBtarget\fR) est une option multivaleur pour d\('efinir les cibles qu\*(Aqapt essaiera d\(cqacqu\('erir \(`a partir de cette source\&. Si cette option n\*(Aqest pas sp\('ecifi\('ee, la configuration par d\('efaut est d\('efinie par le champ d\*(Aqaction de configuration
\fBAcquire::IndexTargets\fR
(les cibles sont d\('efinies par leur nom dans le champ
Created\-By)\&. De plus, les cibles peuvent \(^etre activ\('ees ou d\('esactiv\('ees en utilisant le champ
Identifier
comme option avec une valeur bool\('eenne plut\(^ot que d\*(Aqutiliser cette option multivaleur\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBPDiffs\fR
(\fBpdiffs\fR) est une valeur yes/no qui contr\(^ole si APT doit essayer d\*(Aqutiliser PDiffs pour mettre \(`a jour des index anciens plut\(^ot que de t\('el\('echarger les nouveaux index en totalit\('e\&. La valeur de cette option est ignor\('ee si le d\('ep\(^ot n\*(Aqannonce pas la disponibilit\('e de PDiffs\&. Elle a, par d\('efaut, la valeur de l\*(Aqoption du m\(^eme nom pour un fichier particulier d\('efini dans le champ d\*(Aqaction
\fBAcquire::IndexTargets\fR, qui prend lui\-m\(^eme par d\('efaut la valeur de l\*(Aqoption de configuration
\fBAcquire::PDiffs\fR, dont la valeur par d\('efaut est
yes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBBy\-Hash\fR
(\fBby\-hash\fR)peut avoir la valeur
yes,
no
ou
force
et contr\(^ole si APT doit essayer d\(cqacqu\('erir des index gr\(^ace \(`a un URI construit \(`a partir de la somme de hachage du fichier attendu plut\(^ot que d\*(Aqutiliser le nom de fichier de stable bien connu de l\*(Aqindex\&. Son utilisation peut \('eviter des d\('ecalages de somme de hachage, mais n\('ecessite un miroir de prise en charge\&. Une valeur
yes
ou
no
active ou d\('esactive l\*(Aqutilisation de cette fonctionnalit\('e si cette source indique sa prise en charge, tandis que
force
activera la fonctionnalit\('e quel que soit ce que la source indique\&. Elle a, par d\('efaut, la valeur de l\*(Aqoption du m\(^eme nom pour un fichier particulier d\('efini dans le champ d\*(Aqaction
\fBAcquire::IndexTargets\fR, qui prend lui\-m\(^eme par d\('efaut la valeur de l\*(Aqoption de configuration
\fBAcquire::By\-Hash\fR, dont la valeur par d\('efaut est
yes\&.
.RE
.sp
Par ailleurs, si certaines options sont d\('efinies, elles affectent
\fItoutes\fR
les sources avec les m\(^emes URI et Suite, et donc doivent \(^etre d\('efinies sur toutes ces entr\('ees et ne peuvent \(^etre modifi\('ees entre les diff\('erents composants\&. APT essaiera de d\('etecter et provoquera une erreur avec de telles anomalies\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBAllow\-Insecure\fR
(\fBallow\-insecure\fR),
\fBAllow\-Weak\fR
(\fBallow\-weak\fR) et
\fBAllow\-Downgrade\-To\-Insecure\fR
(\fBallow\-downgrade\-to\-insecure\fR) sont des valeurs bool\('eennes dont la valeur par d\('efaut est
no\&. Si elles sont d\('efinies \(`a
yes, elles contournent certains \('el\('ements d\*(Aq\fBapt-secure\fR(8)
et par cons\('equent ne devraient pas utilis\('ees \(`a la l\('eg\(`ere\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBTrusted\fR
(\fBtrusted\fR) comporte trois valeurs d\*(Aq\('etat qui d\('efinissent par d\('efaut si APT d\('ecide de consid\('erer une source comme s\(^ure ou doit lancer un avertissement avant qu\*(Aqun paquet soit, par exemple, install\('e \(`a partir de cette source\&. Cette option peut \(^etre utilis\('ee pour outrepasser cette d\('ecision\&. La valeur
yes
dit \(`a APT de consid\('erer cette source comme s\(^ure, m\(^eme si elle \('echoue au test d\*(Aqauthentification\&. Elle d\('esactive des \('el\('ements d\*(Aq\fBapt-secure\fR(8)
et elle ne devrait \(^etre utilis\('ee que dans un contexte local et s\('ecuris\('e si possible, parce qu\*(Aqautrement elle ouvre une br\(`eche dans la s\('ecurit\('e\&. La valeur
no
fait le contraire et fait que la source est trait\('ee comme non s\(^ure, m\(^eme si les tests d\*(Aqauthentification sont r\('eussis\&. La valeur par d\('efaut ne peut pas \(^etre d\('efinie explicitement\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBSigned\-By\fR
(\fBsigned\-by\fR) is an option to require a repository to pass
\fBapt-secure\fR(8)
verification with a certain set of keys rather than all trusted keys apt has configured\&. It is specified as a list of absolute paths to keyring files (have to be accessible and readable for the
_apt
system user, so ensure everyone has read\-permissions on the file) and fingerprints of keys to select from these keyrings\&. If no keyring files are specified the default is the
trusted\&.gpg
keyring and all keyrings in the
trusted\&.gpg\&.d/
directory (see
\fBapt\-key fingerprint\fR)\&. If no fingerprint is specified all keys in the keyrings are selected\&. A fingerprint will accept also all signatures by a subkey of this key, if this isn\*(Aqt desired an exclamation mark (!) can be appended to the fingerprint to disable this behaviour\&. The option defaults to the value of the option with the same name if set in the previously acquired
Release
file of this repository (only fingerprints can be specified there through)\&. Otherwise all keys in the trusted keyrings are considered valid signers for this repository\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBCheck\-Valid\-Until\fR
(\fBcheck\-valid\-until\fR) est une valeur yes/no qui d\('etermine si APT doit tenter de d\('etecter les attaques par replay\&. Un cr\('eateur de d\('ep\(^ot peut d\('eclarer une p\('eriode pendant laquelle les donn\('ees fournies par le d\('ep\(^ot peuvent \(^etre consid\('er\('ees comme valables, une fois ce d\('elai \('echu, et si les donn\('ees n\*(Aqont pas \('et\('e fournies, elles sont consid\('er\('ees comme expir\('ees, et un message d\*(Aqerreur est envoy\('e\&. En plus d\*(Aqaccro\(^itre la s\('ecurit\('e, puisqu\*(Aqun attaquant malveillant ne peut plus envoyer des donn\('ees anciennes pour emp\(^echer un utilisateur de mettre \(`a niveau vers une nouvelle version, elle facilite l\*(Aqidentification de miroirs qui ne sont plus mis \(`a jour\&. N\('eanmoins, certains d\('ep\(^ots, comme les archives historiques ne sont plus mis \(`a jour \(`a dessein, aussi cette v\('erification peut \(^etre d\('esactiv\('ee en r\('eglant cette option \(`a
no\&. Elle poss\(`ede la valeur par d\('efaut de l\*(Aqoption
\fBAcquire::Check\-Valid\-Until\fR
qui elle\-m\(^eme poss\(`ede la valeur
yes
par d\('efaut\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBValid\-Until\-Min\fR
(\fBvalid\-until\-min\fR) et
\fBValid\-Until\-Max\fR
(\fBvalid\-until\-max\fR) peuvent \(^etre utilis\('ees pour augmenter ou diminuer la dur\('ee, en secondes pendant laquelle les donn\('ees de ce d\('ep\(^ot sont consid\('er\('ees comme valables\&. \-Max peut \(^etre particuli\(`erement utile pour d\('efinir une valeur propre si le d\('ep\(^ot ne fournit pas de champ Valid\-Until dans son fichier Release, tandis que \-Min peut \(^etre utilis\('e pour augmenter la dur\('ee de validit\('e sur des miroirs (locaux), rarement mis \(`a jour, d\*(Aqune archive plus fr\('equemment mise \(`a jour mais moins accessible (qui est aussi dans le sources\&.list), plut\(^ot que de d\('esactiver totalement la v\('erification\&. Elle poss\(`ede la valeur par d\('efaut des options de configuration
\fBAcquire::Min\-ValidTime\fR
et
\fBAcquire::Max\-ValidTime\fR
qui toutes les deux ne sont pas d\('efinies par d\('efaut\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBCheck\-Date\fR
(\fBcheck\-date\fR) est une valeur yes/no qui contr\(^ole si APT doit consid\('erer que la date de la machine est correcte et donc effectuer les v\('erifications li\('ees au temps, comme v\('erifier si le fichier Release n\*(Aqest pas dans le futur\&. Sa d\('esactivation d\('esactive l\*(Aqoption
\fBCheck\-Valid\-Until\fR
mentionn\('ee ci\-dessus\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBDate\-Max\-Future\fR
(\fBdate\-max\-future\fR) contr\(^ole jusqu\*(Aqo\(`u un d\('ep\(^ot peut \(^etre dans le futur\&. Elle poss\(`ede la valeur del\*(Aqoption de configuration
\fBAcquire::Max\-FutureTime\fR
qui est par d\('efaut de 10\ \&secondes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBInRelease\-Path\fR
(\fBinrelease\-path\fR) d\('etermine le chemin du fichier InRelease, relativement \(`a la position normale d\*(Aqun fichier
InRelease\&. Par d\('efaut, cette option n\*(Aqest pas d\('efinie et APT cherchera \(`a r\('ecup\('erer un fichier
InRelease
ou, s\*(Aqil \('echoue, un fichier
Release
et le fichier
Release\&.gpg
associ\('e\&. Si cette option est d\('efinie, le chemin sp\('ecifi\('e sera essay\('e \(`a la place du fichier InRelease, et le repli vers les fichiers
Release
sera d\('esactiv\('e\&.
.RE
.sp
.SH "SP\('ECIFICATION DES URI"
.PP
Les types d\*(AqURI actuellement reconnus sont\ \&:
.PP
\fBhttp\fR (\fBapt-transport-http\fR(1))
.RS 4
Le proc\('ed\('e http pr\('ecise un serveur HTTP pour une archive et c\*(Aqest la m\('ethode la plus couramment utilis\('ee\&. L\*(AqURI peut inclure directement les information de connexion si l\*(Aqarchive le requiert, mais l\*(Aqutilisation de
\fBapt_auth.conf\fR(5)
devrait \(^etre pr\('ef\('er\('ee\&. La m\('ethode prend \('egalement en charge SOCKS5 et les mandataires HTTP(S) configur\('es soit au moyen d\*(Aqune configuration sp\('ecifique \(`a apt ou sp\('ecifi\('es par la variable d\*(Aqenvironnement
\fBhttp_proxy\fR
au format
\fIhttp://user:pass@server:port/\fR
(en supposant un mandataire HTTP n\('ecessitant une authentification)\&. Les d\('etails de l\*(Aqauthentification pour les mandataires peuvent aussi \(^etre fournis avec
\fBapt_auth.conf\fR(5)\&.
.sp
Veuillez noter que ces formes d\*(Aqauthentification ne sont pas s\(^ures puisque toutes les communications avec le serveur distant (ou le mandataire) ne sont pas chiffr\('ees, donc un attaquant suffisamment comp\('etent peut observer et enregistrer la connexion ainsi que les autres interactions\&. L\*(Aqattaquant ne peut
\fIpas\fR
modifier la communication dans la mesure o\(`u le mod\(`ele de s\('ecurit\('e des donn\('ees d\*(AqApt est ind\('ependant de la m\('ethode de transport choisie\&. Voir
\fBapt-secure\fR(8)
pour plus de d\('etails\&.
.RE
.PP
\fBhttps\fR (\fBapt-transport-https\fR(1))
.RS 4
Le proc\('ed\('e https pr\('ecise un serveur HTTPS pour une archive et il est tr\(`es semblable au proc\('ed\('e http en termes d\*(Aqutilisation et d\*(Aqoptions disponibles\&. La principale diff\('erence est que les communications entre apt et le serveur (ou le mandataire) sont chiffr\('ees\&. Veuillez noter que le chiffrage n\*(Aqemp\(^eche pas un attaquant de savoir avec quel serveur (ou mandataire) apt est en communication et que des analyses approfondies peuvent encore potentiellement r\('ev\('eler quelles donn\('ees sont t\('el\('echarg\('ees\&. Si cela est une pr\('eoccupation, des proc\('ed\('es bas\('es sur Tor, mentionn\('es plus bas, pourraient \(^etre une alternative appropri\('ee\&.
.RE
.PP
\fBmirror\fR, \fBmirror+\fR\fB\fIscheme\fR\fR (\fBapt-transport-mirror\fR(1))
.RS 4
The mirror scheme specifies the location of a mirrorlist\&. By default the scheme used for the location is
http, but any other scheme can be used via
\fBmirror+\fR\fB\fIscheme\fR\fR\&. The mirrorlist itself can contain many different URIs for mirrors the APT client can transparently pick, choose and fallback between intended to help both with distributing the load over the available mirrors and ensuring that clients can acquire data even if some configured mirrors are not available\&.
.RE
.PP
\fBfile\fR
.RS 4
Le proc\('ed\('e
file
permet qu\*(Aqun r\('epertoire arbitraire au sein du syst\(`eme de fichiers soit consid\('er\('e comme une archive\&. Cela est utilis\('e avec les montages NFS, les miroirs et les archives locaux\&.
.RE
.PP
\fBcdrom\fR
.RS 4
Le proc\('ed\('e
cdrom
permet l\*(Aqutilisation d\*(Aqun lecteur de CD, de DVD ou USB, avec la possibilit\('e de changer de m\('edia\&. Utilisez le programme
\fBapt-cdrom\fR(8)
pour cr\('eer des entr\('ees
cdrom
dans la liste des sources\&.
.RE
.PP
\fBftp\fR
.RS 4
Le proc\('ed\('e
ftp
indique un serveur FTP comme archive\&. L\*(Aqutilisation de FTP d\('ecline en faveur de
http
et
https
et plusieurs archives soit n\*(Aqont jamais offert d\*(Aqacc\(`es FTP, soit le retirent\&. Si vous avez encore besoin de cette m\('ethode, plusieurs options de configuration sont disponibles dans le champ d\*(Aqaction
Acquire::ftp
et d\('etaill\('ees dans
\fBapt.conf\fR(5)\&.
.sp
Veuillez noter qu\*(Aqon peut sp\('ecifier un mandataire FTP en utilisant la variable d\*(Aqenvironnement
\fBftp_proxy\fR\&. On peut aussi sp\('ecifier un mandataire HTTP (les serveurs mandataires HTTP comprennent souvent les URL FTP) en utilisant cette m\('ethode et
\fIseulement\fR
cette m\('ethode\&. Les mandataires qui utilisent HTTP et qui sont sp\('ecifi\('es dans le fichier de configuration seront ignor\('es\&.
.RE
.PP
\fBcopy\fR
.RS 4
Le proc\('ed\('e
copy
est identique au proc\('ed\('e
file
except\('e que les paquets sont copi\('es dans le cache du r\('epertoire au lieu d\*(Aq\(^etre utilis\('es directement depuis leur emplacement\&. Ce r\('eglage peut servir aux utilisateurs qui se servent d\*(Aqun support amovible pour recopier des fichiers avec APT\&.
.RE
.PP
\fBrsh\fR, \fBssh\fR
.RS 4
Le proc\('ed\('e rsh/ssh utilise rsh/ssh pour se connecter \(`a une machine distante et pour acc\('eder aux fichiers en tant qu\*(Aqun certain utilisateur\&. Il est recommand\('e de r\('egler pr\('ealablement les h\(^otes distants (rhosts) ou les cl\('es RSA\&. Les commandes standard
\fBfind\fR
et
\fBdd\fR
sont utilis\('ees pour l\*(Aqacc\(`es aux fichiers de la machine distante\&.
.RE
.PP
ajout de types d\*(AqURI suppl\('ementaires reconnus
.RS 4
APT peut \(^etre compl\('et\('e avec des m\('ethodes suppl\('ementaires fournies par des paquets optionnels dont le sch\('ema de nommage est
apt\-transport\-\fIm\('ethode\fR\&. Ainsi, l\*(Aq\('equipe de maintenance d\*(AqAPT g\(`ere un paquet
apt\-transport\-tor
qui g\(`ere les m\('ethodes d\*(Aqacc\(`es par URI de type HTTP et HTTPS rout\('ees \(`a travers le r\('eseau Tor\&.
.RE
.SH "EXEMPLES"
.PP
Utiliser l\*(Aqarchive stock\('ee localement (ou mont\('ee via NFS) dans /home/apt/debian pour stable/main, stable/contrib et stable/non\-free\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/apt/debian stable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: file:/home/apt/debian
Suites: stable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Comme ci\-dessus, except\('e que cette ligne utilise la distribution \(Fo\ \&unstable\ \&\(Fc (d\('eveloppement)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb file:/home/apt/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: file:/home/apt/debian
Suites: unstable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
Indication des sources pour les lignes pr\('ec\('edentes\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb\-src file:/home/apt/debian unstable main contrib non\-free
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb\-src
URIs: file:/home/apt/debian
Suites: unstable
Components: main contrib non\-free
.fi
.if n \{\
.RE
.\}
.PP
La premi\(`ere ligne r\('ecup\(`ere l\*(Aqinformation des paquets pour les architectures de
APT::Architectures
alors que la deuxi\(`eme r\('ecup\(`ere
amd64
et
armel\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stretch main
deb [ arch=amd64,armel ] http://deb\&.debian\&.org/debian stretch main
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main

Types: deb
URIs: http://deb\&.debian\&.org/debian
Suites: stretch
Components: main
Architectures: amd64 armel
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour acc\('eder \(`a l\*(Aqarchive situ\('ee \(`a archive\&.debian\&.org, et n\*(Aqutiliser que la section hamm/main\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://archive\&.debian\&.org/debian\-archive hamm main
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://archive\&.debian\&.org/debian\-archive
Suites: hamm
Components: main
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour acc\('eder \(`a l\*(Aqarchive situ\('ee \(`a ftp\&.debian\&.org, dans le r\('epertoire debian, et n\*(Aqutiliser que la section stretch/contrib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian stretch contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: ftp://ftp\&.debian\&.org/debian
Suites: stretch
Components: contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser FTP pour acc\('eder \(`a l\*(Aqarchive situ\('ee \(`a ftp\&.debian\&.org, dans le r\('epertoire debian, et n\*(Aqutiliser que la section unstable/contrib\&. Si cette ligne et celle de l\*(Aqexemple pr\('ec\('edent dans
sources\&.list
apparaissent, une seule session FTP sera utilis\('ee pour les deux lignes\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb ftp://ftp\&.debian\&.org/debian unstable contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: ftp://ftp\&.debian\&.org/debian
Suites: unstable
Components: contrib
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour acc\('eder \(`a l\*(Aqarchive situ\('ee \(`a ftp\&.tlh\&.debian\&.org, dans le r\('epertoire universe, et n\*(Aqutiliser que les fichiers trouv\('es dans
unstable/binary\-i386
pour les machines i386, dans
unstable/binary\-amd64
pour les machines amd64 et ainsi de suite pour les autres architectures reconnues\&. [Notez que cet exemple montre seulement la mani\(`ere d\*(Aqutiliser la variable \(`a substituer, les archives Debian officielles n\*(Aq\('etant pas structur\('ees de cette mani\(`ere\&.]
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://ftp\&.tlh\&.debian\&.org/universe unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb
URIs: http://ftp\&.tlh\&.debian\&.org/universe
Suites: unstable/binary\-$(ARCH)/
.fi
.if n \{\
.RE
.\}
.PP
Utiliser HTTP pour pouvoir obtenir les paquets binaires ainsi que les sources des suites stable, testing et unstable et des composants main et contrib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
deb http://deb\&.debian\&.org/debian stable main contrib
deb\-src http://deb\&.debian\&.org/debian stable main contrib
deb http://deb\&.debian\&.org/debian testing main contrib
deb\-src http://deb\&.debian\&.org/debian testing main contrib
deb http://deb\&.debian\&.org/debian unstable main contrib
deb\-src http://deb\&.debian\&.org/debian unstable main contrib
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
Types: deb deb\-src
URIs: http://deb\&.debian\&.org/debian
Suites: stable testing unstable
Components: main contrib
.fi
.if n \{\
.RE
.\}
.SH "VOIR AUSSI"
.PP
\fBapt-get\fR(8),
\fBapt.conf\fR(5),
/usr/share/doc/apt\-doc/acquire\-additional\-files\&.md\&.gz
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous souhaitez signaler un bogue \(`a propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
J\('er\(^ome Marant, Philippe Batailler, Christian Perrier
<bubulle@debian\&.org>
(2000, 2005, 2009, 2010), \('Equipe de traduction francophone de Debian
<debian\-l10n\-french@lists\&.debian\&.org>
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites\&. Cela est volontaire, pour \('eviter de perdre du contenu quand la traduction est l\('eg\(`erement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fB\('Equipe de d\('eveloppement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
