'\" t
.\"     Title: apt-cache
.\"    Author: Gunthorpe Jason[FAMILY Given]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 16\ \&8 月\ \&2016
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Japanese
.\"
.TH "APT\-CACHE" "8" "16\ \&8 月\ \&2016" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
apt-cache \- APT キャッシュへの問い合わせ
.SH "概要"
.HP \w'\fBapt\-cache\fR\ 'u
\fBapt\-cache\fR [\fB\-agipns\fR] [\fB\-o=\fR\fB\fI設定文字列\fR\fR] [\fB\-c=\fR\fB\fI設定ファイル\fR\fR] {gencaches | showpkg\ \fIパッケージ\fR...  | showsrc\ \fIパッケージ\fR...  | stats | dump | dumpavail | unmet | search\ \fI正規表現\fR...  | show\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | depends\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | rdepends\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | pkgnames\ [\fIprefix\fR]  | dotty\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | xvcg\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | policy\ [\fIパッケージ\fR...]  | madison\ \fIパッケージ\fR...  | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "説明"
.PP
\fBapt\-cache\fR
は APT のパッケージキャッシュに対して、さまざまな操作を行います。\fBapt\-cache\fR
は、システム状態の操作は行いませんが、パッケージのメタデータを検索したり、興味深い出力を生成するといった操作を提供します。メタデータは、例えば
\fBapt\-get\fR
の \*(Aqupdate\*(Aq コマンドで取得して更新します。そのため、最後の更新が古すぎる場合は、時代遅れです。ただし、引き換えに
\fBapt\-cache\fR
は、設定された取得元の可用性とは独立して動作します (例えばオフライン)。
.PP
\fB\-h\fR
オプションや
\fB\-\-help\fR
オプションを除き、以下に挙げるコマンドが必要です。
.PP
\fBgencaches\fR
.RS 4
gencaches
は APT のパッケージキャッシュを作成します。このキャッシュが見つからない、または古くなっている場合、キャッシュを必要とするすべてのコマンドによって、暗黙で実行されます。
.RE
.PP
\fBshowpkg\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
showpkg
は、コマンドライン上に列挙したパッケージの情報を表示します。後に続く引数はパッケージ名となります。各パッケージについて、有効なバージョンと被依存関係を列挙し、さらにその各バージョンについて依存関係を表示します。(通常の) 依存関係とは、対象のパッケージが依存しているパッケージを指します。また、被依存関係とは、対象のパッケージに依存しているパッケージを指します。従って、パッケージの依存関係は満たさなければなりませんが、被依存関係は満たす必要はありません。実例として、以下に
\fBapt\-cache showpkg libreadline2\fR
の出力を掲げます。
.sp
.if n \{\
.RS 4
.\}
.nf
Package: libreadline2
Versions: 2\&.1\-12(/var/state/apt/lists/foo_Packages),
Reverse Depends: 
  libreadlineg2,libreadline2
  libreadline2\-altdev,libreadline2
Dependencies:
2\&.1\-12 \- libc5 (2 5\&.4\&.0\-0) ncurses3\&.0 (0 (null))
Provides:
2\&.1\-12 \- 
Reverse Provides: 
.fi
.if n \{\
.RE
.\}
つまり、libreadline2 の version 2\&.1\-12 は、libc5 と ncurses3\&.0 に依存していて、libreadline2 が動作するには、これらをインストールする必要があるということが判ります。一方、libreadlineg2 と libreadline2\-altdev は libreadline2 に依存しています。libreadline2 をインストールするためには、libc5, ncurses3\&.0, ldso をすべてインストールしなければなりませんが、libreadlineg2 と libreadline2\-altdev はインストールする必要はありません。出力の残りの部分の意味については、apt のソースコードを調べるのが最良でしょう。
.RE
.PP
\fBstats\fR
.RS 4
stats
はキャッシュについての統計情報を表示します。それ以上、引数は必要ありません。以下の統計情報を表示します。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
パッケージ名総数は、キャッシュに存在するパッケージ数を表します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
通常パッケージは、公式の普通のパッケージ数を表します。これは、他のパッケージの依存関係で使用された名称で、それが一対一に対応するパッケージです。大多数のパッケージはこのカテゴリに入ります。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
純粋仮想パッケージは、仮想パッケージ名としてのみ存在するパッケージ (仮想パッケージ名のみを「提供」し、実際にはいかなるパッケージもその名称を持たない) の数を表します。例えば、Debian システムでは "mail\-transport\-agent" は純粋仮想パッケージです。"mail\-transport\-agent" を提供するパッケージはいくつもありますが、"mail\-transport\-agent" という名前のパッケージはありません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
単一仮想パッケージは、特定の仮想パッケージ名を提供するパッケージが、ただ一つの場合の数を表します。例えば、Debian システムでは、"X11\-text\-viewer" は仮想パッケージですが、"X11\-text\-viewer" を提供するパッケージは、xless パッケージのみということです。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
複合仮想パッケージは、その仮想パッケージ名を提供するパッケージが複数あるか、またパッケージ名と同じ仮想パッケージ名を持つパッケージの数を表します。例えば、Debian システムでは、"debconf" は実際のパッケージ名でもありますが、debconf\-tiny によって提供もされています。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
欠落は、依存関係中には存在するのに、どのパッケージにも提供されていないパッケージ名の数を表します。欠落パッケージは、全ディストリビューションにアクセスできていないか、(実ないし仮想) パッケージがディストリビューションからはずされたという兆候かもしれません。通常、構文が競合や破損するとこのようになります。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
個別バージョン総数は、キャッシュに存在するパッケージのバージョンの数を表します。もし複数のディストリビューション (例えば "stable" と "unstable") にアクセスする場合、この値はパッケージ名総数よりもかなり大きい数になります。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
依存関係総数は、キャッシュにあるすべてのパッケージで要求された依存関係の数です。
.RE
.sp
.RE
.PP
\fBshowsrc\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
showsrc
は、指定したパッケージ名に一致するソースパッケージを、すべて表示します。バイナリパッケージになるときの名称を宣言したレコードとともに、すべてのバージョンについて表示します。ソースパッケージ名だけを表示するには、\fB\-\-only\-source\fR
を使用してください。
.RE
.PP
\fBdump\fR
.RS 4
dump
は、キャッシュ内のパッケージそれぞれについて、短い一覧を表示します。主にデバッグ用です。
.RE
.PP
\fBdumpavail\fR
.RS 4
dumpavail
は、標準出力に利用可能なものの一覧を出力します。
\fBdpkg\fR(1)
と共に使用すると便利ですし、\fBdselect\fR(1)
でも使用されます。
.RE
.PP
\fBunmet\fR
.RS 4
unmet
は、パッケージキャッシュ内にある、不適当な依存関係の概要を表示します。
.RE
.PP
\fBshow\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
show
は、\fBdpkg \-\-print\-avail\fR
と同様の機能を実行します。これは、指定したパッケージのパッケージレコードの表示です。
.RE
.PP
\fBsearch\fR \fB\fI正規表現\fR\fR\fB\&...\fR
.RS 4
search
は、与えられた POSIX の正規表現 (\fBregex\fR(7)
を参照) により、すべての利用可能なパッケージに対して全文検索を行います。パッケージ名と説明に対して正規表現で検索を行い、パッケージ名 (仮想パッケージ名を含む) と短い説明文を表示します。\fB\-\-full\fR
が与えられた場合、マッチしたパッケージに対し
show
と同じ情報を出力します。\fB\-\-names\-only\fR
が与えられた場合は、長い説明文に対して検索を行わず、パッケージ名と提供されたパッケージのみ対象とします。
.sp
空白で区切った引数で、複数の検索パターンの and をとることができます。
.RE
.PP
\fBdepends\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
depends
は、パッケージが持っている依存関係と、その依存関係を満たす他のパッケージの一覧を表示します。
.RE
.PP
\fBrdepends\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
rdepends
は、パッケージが持つ被依存関係を一覧表示します。
.RE
.PP
\fBpkgnames\fR [\fIprefix\fR]
.RS 4
このコマンドは、APT が知っている各パッケージの名前を表示します。オプション引数は、名前一覧から先頭一致で抽出します。この出力はシェルのタブによる補完機能で使いやすく、また非常に高速に生成されます。このコマンドは
\fB\-\-generate\fR
オプションと共に使用すると非常に便利です。
.sp
APT が知っているパッケージは、ダウンロード可能、インストール可能、インストール済みである必要がないことに注意してください。つまり、仮想パッケージも生成した一覧にあります。
.RE
.PP
\fBdotty\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
dotty
は、コマンドライン上のパッケージ名から、\m[blue]\fBGraphViz\fR\m[]\&\s-2\u[1]\d\s+2
パッケージの dotty コマンドで利用するのに便利な出力を生成します。結果はパッケージの関係を表わす、ノード・エッジのセットで表現されます。デフォルトでは、すべての依存パッケージをトレースするので、非常に大きい図が得られます。コマンドラインに列挙したパッケージだけを出力するように制限するには、APT::Cache::GivenOnly
をセットしてください。
.sp
結果のノードは数種の形状をとります。通常パッケージは四角、純粋仮想パッケージは三角、複合仮想パッケージは菱形、欠落パッケージは六角形で表します。オレンジの四角は再帰が終了した「リーフパッケージ」、青い線は先行依存、緑の線は競合を表します。
.sp
注意) dotty は、パッケージのより大きなセットのグラフは描けません。
.RE
.PP
\fBxvcg\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
dotty
と同様ですが、\m[blue]\fBVCG tool\fR\m[]\&\s-2\u[2]\d\s+2
の xvcg 専用です。
.RE
.PP
\fBpolicy\fR [\fIパッケージ\fR\&...]
.RS 4
policy
は、プリファレンスファイル関係の問題について、デバッグを支援します。引数を指定しなかった場合、取得元ごとの優先順位を表示します。一方、パッケージ名を指定した場合、優先順の詳細情報を表示します。
.RE
.PP
\fBmadison\fR \fB\fIパッケージ\fR\fR\fB\&...\fR
.RS 4
apt\-cache
の
madison
コマンドは、Debian アーカイブ管理ツール
madison
の機能のサブセットで、出力フォーマットを真似ようとします。パッケージの利用可能バージョンを表形式で表示します。オリジナルの
madison
と違い、APT がパッケージ一覧を検索したアーキテクチャ (APT::Architecture) の情報を表示するだけです。
.RE
.SH "オプション"
.PP
ここで設定オプションとして説明したコマンドラインオプションは、 すべて設定ファイルを使用して設定できます。 設定ファイルに書いた真偽値をとるオプションは
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
などのようにして上書きできます。
.PP
\fB\-p\fR, \fB\-\-pkg\-cache\fR
.RS 4
パッケージキャッシュを格納するファイルを選択します。パッケージキャッシュは、すべての操作で使用される一次キャッシュです。設定項目:
Dir::Cache::pkgcache
.RE
.PP
\fB\-s\fR, \fB\-\-src\-cache\fR
.RS 4
ソースキャッシュを格納するファイルを選択します。このソースキャッシュは
gencaches
でのみ使用され、ここに解析された取得元のパッケージ情報が格納されています。パッケージキャッシュを構築する際に、全パッケージファイルの再解析を避けるために、ソースキャッシュが使われます。設定項目:
Dir::Cache::srcpkgcache
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
静粛 \- 進捗表示を省略し、ログをとるのに便利な出力を行います。最大 2 つまで q を重ねることでさらに静粛にできます。また、\fB\-q=#\fR
のように静粛レベルを指定して、設定ファイルを上書きすることもできます。設定項目:
quiet
.RE
.PP
\fB\-i\fR, \fB\-\-important\fR
.RS 4
「重要」依存関係のみ表示 \-
unmet
や
depends
と共に使用し、「依存」関係と「先行依存」関係のみを表示します。設定項目:
APT::Cache::Important
.RE
.PP
\fB\-\-no\-pre\-depends\fR, \fB\-\-no\-depends\fR, \fB\-\-no\-recommends\fR, \fB\-\-no\-suggests\fR, \fB\-\-no\-conflicts\fR, \fB\-\-no\-breaks\fR, \fB\-\-no\-replaces\fR, \fB\-\-no\-enhances\fR
.RS 4
デフォルトでは
\fBdepends\fR
や
\fBrdepends\fR
は全依存関係を出力します。この挙動を、ここに挙げたフラグで指定した依存関係を省略できます。設定項目:
APT::Cache::Show\fI依存関係タイプ\fR
例:
APT::Cache::ShowRecommends
.RE
.PP
\fB\-\-implicit\fR
.RS 4
デフォルトでは
\fBdepends\fR
や
\fBrdepends\fR
はメタデータ中に明示的に表現された依存関係のみを出力します。このフラグを指定すると、遭遇したデータにもとづいて追加の依存関係を表示します。Conflicts: foo
は、例えば、このパッケージがほかのアーキテクチャからのパッケージ foo と競合していることを暗黙的に表現しています。設定項目:
APT::Cache::ShowImplicit
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
search 時に全パッケージレコードを表示します。設定項目:
APT::Cache::ShowFull
.RE
.PP
\fB\-a\fR, \fB\-\-all\-versions\fR
.RS 4
全利用可能バージョンのレコード全体を表示します。これはデフォルトの動作で、無効にするには
\fB\-\-no\-all\-versions\fR
を使用してください。\fB\-\-no\-all\-versions\fR
を指定すると、候補バージョン (インストールの際に選択されるもの) だけ表示します。このオプションは、show
コマンドでのみ適用できます。設定項目:
APT::Cache::AllVersions
.RE
.PP
\fB\-g\fR, \fB\-\-generate\fR
.RS 4
そのままキャッシュを使用するのではなく、自動的にパッケージキャッシュを再生成します。これはデフォルトの動作で、無効にするには
\fB\-\-no\-generate\fR
を使用してください。設定項目:
APT::Cache::Generate
.RE
.PP
\fB\-\-names\-only\fR, \fB\-n\fR
.RS 4
長い説明文ではなく、パッケージおよび提供されたパッケージ名のみ検索します。設定項目:
APT::Cache::NamesOnly
.RE
.PP
\fB\-\-all\-names\fR
.RS 4
pkgnames
で、仮想パッケージや欠落依存関係を含めた全名称を表示します。設定項目:
APT::Cache::AllNames
.RE
.PP
\fB\-\-recurse\fR
.RS 4
depends
や
rdepends
で、指定した全パッケージを再帰的に一度に表示します。設定項目:
APT::Cache::RecurseDepends
.RE
.PP
\fB\-\-installed\fR
.RS 4
depends
や
rdepends
の出力を、現在インストールされているパッケージに限定します。設定項目:
APT::Cache::Installed
.RE
.PP
\fB\-\-with\-source\fR \fB\fIファイル名\fR\fR
.RS 4
メタ情報のソースとして指定したファイルを追加します。指定を繰り返すと複数のファイルを追加できます。現在サポートしているのは
*\&.deb、*\&.dsc、*\&.changes、Sources、Packages
ファイル並びにソースパッケージのディレクトリです。ファイルとの照合はファイル名だけを基にして行い、ファイルの内容との照合は行いません!
.sp
Sources
及び
Packages
は正しい拡張子を付けていれば APT がサポートする任意の形式で圧縮できます。このファイルを同じディレクトリに複数置く必要がある場合は、自分が付ける名前の部分の最後尾にアンダースコア (「_」) を付加したものを先頭に付けます。例: my\&.example_Packages\&.xz
.sp
これによって指定したソースは信頼できるものとして扱われる (\fBapt-secure\fR(8)
参照) ことに注意してください。設定項目:
APT::Sources::With
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
使い方の短い要約を表示します。
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
プログラムのバージョンを表示します。
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
設定ファイル。 使用する設定ファイルを指定します。 このプログラムは、デフォルト設定ファイルを読んでから、この設定ファイルを読みます。 この設定をデフォルト設定ファイルよりも前に読む必要がある場合、
\fBAPT_CONFIG\fR
環境変数に指定してください。構文については
\fBapt.conf\fR(5)
をご覧ください。
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
設定オプションのセット。任意の設定オプションをセットします。 構文
\fB\-o Foo::Bar=bar\fR
となります。 異なるオプションを設定するため、\fB\-o\fR
と
\fB\-\-option\fR
は、 複数回使用できます。
.RE
.SH "ファイル"
.PP
/etc/apt/sources\&.list
.RS 4
パッケージ取得元の場所。 設定項目:
Dir::Etc::SourceList
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
パッケージ取得元の場所のファイル断片 設定項目:
Dir::Etc::SourceParts
.RE
.PP
/var/lib/apt/lists/
.RS 4
\fBsources.list\fR(5)
に指定した、パッケージリソースごとの状態情報格納エリア。 設定項目:
Dir::State::Lists
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
取得中状態情報格納エリア。 設定項目:
Dir::State::Lists
(暗黙で
partial
を追加)
.RE
.SH "関連項目"
.PP
\fBapt.conf\fR(5),
\fBsources.list\fR(5),
\fBapt-get\fR(8)
.SH "診断メッセージ"
.PP
\fBapt\-cache\fR
は正常終了時に 0 を返します。エラー時には十進の 100 を返します。
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[3]\d\s+2
をご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "翻訳"
.PP
倉澤 望
<nabetaro@debian\&.or\&.jp>
(2003\-2006,2009\-2012), Takuma Yamada
<tyamada@takumayamada\&.com>
(2016), Debian JP Documentation ML
<debian\-doc@debian\&.or\&.jp>
.PP
この翻訳文書には未訳部分が含まれている可能性があることに 注意してください。 翻訳がオリジナルに追従できていない場合、 内容を失わないようにこのようにしています。
.SH "著者"
.PP
\fBGunthorpe Jason[FAMILY Given]\fR
.RS 4
.RE
.PP
\fB[FAMILY Given]\fR
.RS 4
.RE
.SH "注記"
.IP " 1." 4
GraphViz
.RS 4
\%http://www.research.att.com/sw/tools/graphviz/
.RE
.IP " 2." 4
VCG tool
.RS 4
\%http://rw4.cs.uni-sb.de/users/sander/html/gsvcg1.html
.RE
.IP " 3." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
