'\" t
.\"     Title: apt
.\"    Author: [FAMILY Given]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 20\ \&10 月\ \&2015
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Japanese
.\"
.TH "APT" "8" "20\ \&10 月\ \&2015" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
apt \- コマンドラインインターフェイス
.SH "概要"
.HP \w'\fBapt\fR\ 'u
\fBapt\fR [\fB\-h\fR] [\fB\-o=\fR\fB\fI設定文字列\fR\fR] [\fB\-c=\fR\fB\fI設定ファイル\fR\fR] [\fB\-t=\fR\fB\fI対象リリース\fR\fR] [\fB\-a=\fR\fB\fIアーキテクチャ\fR\fR] {list | search | show | update | install\ \fIパッケージ\fR\ [{=\fIパッケージバージョン番号\fR\ |\ /\fI対象リリース\fR}]...  | remove\ \fIパッケージ\fR...  | upgrade | full\-upgrade | edit\-sources | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "説明"
.PP
\fBapt\fR
は、パッケージ管理システム用の高レベルのコマンドラインインターフェースを提供します。エンドユーザインターフェースとして設計されています。また
\fBapt-get\fR(8)
や
\fBapt-cache\fR(8)
のような専用の APT ツールと比べて、デフォルトでインタラクティブな使用に適したいくつかのオプションが有効になっています。
.PP
\fBapt\fR
自身と同じように、man ページはエンドユーザインターフェースとして意図されています。さらに、一部のオプションや詳細の豊富さで読者を圧倒することを避けるため、複数の場所で部分的に情報を複製しないよう、最も使用されるコマンドとオプションを言及するように意図されています。
.PP
\fBupdate\fR (\fBapt-get\fR(8))
.RS 4
\fBupdate\fR
は、設定されたすべての取得元からパッケージ情報をダウンロードするために使用されます。ほかのコマンドは、このデータを操作します。例えば、パッケージのアップグレードを実行したり、中を検索したり、インストール可能なすべてのパッケージに関する詳細情報を表示します。
.RE
.PP
\fBupgrade\fR (\fBapt-get\fR(8))
.RS 4
\fBupgrade\fR
は、\fBsources.list\fR(5)
で設定された取得元からシステムに現在インストール済みのすべてのパッケージで利用可能なアップグレードをインストールするために使用されます。依存関係を満たすために必要な場合は新しいパッケージがインストールされますが、既存のパッケージが削除されることはありません。パッケージのアップグレードにインストール済みパッケージの削除が必要な場合、そのパッケージのアップグレードは行われません。
.RE
.PP
\fBfull\-upgrade\fR (\fBapt-get\fR(8))
.RS 4
full\-upgrade
はアップグレードの機能を実行しますが、システム全体をアップグレードするために必要とされる場合には、現在インストール済みのパッケージを削除することができます。
.RE
.PP
\fBinstall\fR, \fBremove\fR, \fBpurge\fR (\fBapt-get\fR(8))
.RS 4
\fBregex\fR(7)、\fBglob\fR(7)
または 完全な一致で指定された 1 つ以上のパッケージに対して要求された処理を実行します。要求された処理は、特定のパッケージに対してパッケージ名にプラス (+) を追加してパッケージのインストールを、マイナス (\-) を追加してパッケージの削除を上書きすることができます。
.sp
パッケージ名にイコール (=) とパッケージのバージョンを続けることで、選択したバージョンのパッケージをインストールすることができます。代わりに、パッケージ名にスラッシュ (/) およびコード名 (stretch、buster、sid \&...) またはスイート名 (stable、testing、unstable) を続けることで、特定のリリースのバージョンをインストールすることができます。また、必要な場合には、パッケージの依存関係を満たすリリースからバージョンを選択します。
.sp
パッケージの削除はパッケージの全データを削除しますが、削除の事故に備えて、通常は隠れている小さな (修正された) ユーザ設定ファイルを残します。問題が発生したときは、誤って削除したパッケージのインストール要求を発行すると、以前のようにその機能を復元します。一方、\fBpurge\fR
を呼び出すことで、すでに削除したパッケージの残されたデータを削除することができます。これはあなたのホームディレクトリに保存しているデータや設定には影響を与えないことに注意してください。
.RE
.PP
\fBautoremove\fR (\fBapt-get\fR(8))
.RS 4
autoremove
は、ほかのパッケージの依存関係を満たすために自動的にインストールされた後に、依存関係の変更あるいは必要としていたパッケージが削除されたことでもう必要なくなったパッケージの削除に使用することができます。
.sp
別のパッケージの依存関係のため一度インストールされたなどで増えたアプリケーションがリストに含まれていないことを確認する必要があります。\fBapt-mark\fR(8)
を使って、手動でパッケージをインストール済にマークすることができます。\fBinstall\fR
経由で明示的にインストールしたパッケージは、自動削除のために提案されることはありません。
.RE
.PP
\fBsearch\fR (\fBapt-cache\fR(8))
.RS 4
\fBsearch\fR
は、利用可能なパッケージのリストを指定した
\fBregex\fR(7)
条件で検索してマッチした結果を表示するために使用することができます。これは、例えば特定の機能をもつパッケージを探している場合に有用です。特定のファイルを含むパッケージを探しているのなら、\fBapt-file\fR(1)
を試してください。
.RE
.PP
\fBshow\fR (\fBapt-cache\fR(8))
.RS 4
指定されたパッケージに関する情報を表示します。依存関係、インストールおよびダウンロードサイズ、パッケージが入手可能な取得元、パッケージの内容の説明などを含みます。例えば
\fBapt\fR(8)
にパッケージの削除をさせる前や、インストールする新しいパッケージを検索するときに、この情報を見て参考にすることができます。
.RE
.PP
\fBlist\fR (作業中)
.RS 4
\fBlist\fR
は、一定の基準を満たすパッケージのリストを表示することができるという点で、\fBdpkg\-query \-\-list\fR
に似ています。インストール済 (\fB\-\-installed\fR)、アップグレード可能 (\fB\-\-upgradeable\fR) または利用可能なすべてのバージョン (\fB\-\-all\-versions\fR) の一覧オプションでも、パッケージ名をマッチさせる
\fBglob\fR(7)
パターンをサポートしています。
.RE
.PP
\fBedit\-sources\fR (作業中)
.RS 4
edit\-sources
は、お好みのテキストエディタで
\fBsources.list\fR(5)
ファイルを編集することができます。また、基本的な健全性チェックを提供します。
.RE
.SH "スクリプトの使い方およびほかの APT ツールとの違い"
.PP
\fBapt\fR(8)
コマンドラインはエンドユーザ向けツールとして設計されています。動作はバージョン間で変更される可能性があります。後方互換性を損なうことのないようには努めますが、変更がインタラクティブな使用に有益と思われる場合には、その保証はありません。
.PP
\fBapt\fR(8)
のすべての機能は、\fBapt-get\fR(8)
や
\fBapt-cache\fR(8)
など専用の APT ツールで利用可能です。\fBapt\fR(8)
は、単にいくつかのオプションのデフォルト値を変更します (\fBapt.conf\fR(5)
の特にバイナリ範囲を参照)。可能な限り下位互換性を保つように、スクリプトでは (潜在的に有効になっているいくつかの追加オプションをつけて) コマンドを使うべきです。
.SH "関連項目"
.PP
\fBapt-get\fR(8)、\fBapt-cache\fR(8)、\fBsources.list\fR(5)、\fBapt.conf\fR(5)、\fBapt-config\fR(8)、/usr/share/doc/apt\-doc/ にある APT ユーザガイド、\fBapt_preferences\fR(5)、APT Howto\&.
.SH "診断メッセージ"
.PP
\fBapt\fR
は正常終了時に 0 を返します。エラー時には十進の 100 を返します。
.SH "バグ"
.PP
\m[blue]\fBAPT バグページ\fR\m[]\&\s-2\u[1]\d\s+2
をご覧ください。 APT のバグを報告する場合は、
/usr/share/doc/debian/bug\-reporting\&.txt
や
\fBreportbug\fR(1)
コマンドをご覧ください。
.SH "翻訳"
.PP
倉澤 望
<nabetaro@debian\&.or\&.jp>
(2003\-2006,2009\-2012), Takuma Yamada
<tyamada@takumayamada\&.com>
(2016), Debian JP Documentation ML
<debian\-doc@debian\&.or\&.jp>
.PP
この翻訳文書には未訳部分が含まれている可能性があることに 注意してください。 翻訳がオリジナルに追従できていない場合、 内容を失わないようにこのようにしています。
.SH "著者"
.PP
\fB[FAMILY Given]\fR
.RS 4
.RE
.SH "注記"
.IP " 1." 4
APT バグページ
.RS 4
\%http://bugs.debian.org/src:apt
.RE
