'\" t
.\"     Title: apt-sortpkgs
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 30\ \&novembre\ \&2013
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Italian
.\"
.TH "APT\-SORTPKGS" "1" "30\ \&novembre\ \&2013" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
apt-sortpkgs \- utilit\(`a per ordinare i file indice dei pacchetti
.SH "SINOSSI"
.HP \w'\fBapt\-sortpkgs\fR\ 'u
\fBapt\-sortpkgs\fR [\fB\-s\fR] [\fB\-o=\fR\fB\fIstringa_config\fR\fR] [\fB\-c=\fR\fB\fIfile_config\fR\fR] \fInomefile\fR... {\-v\ |\ \-\-version} {\-h\ |\ \-\-help}
.SH "DESCRIZIONE"
.PP
\fBapt\-sortpkgs\fR
accetta un file indice (indice di sorgenti o di pacchetti) e ordina i record in base al nome del pacchetto\&. Ordina anche i campi interni ad ogni record in base alle regole di ordinamento interne\&.
.PP
Tutto l\*(Aqoutput viene inviato sullo standard output; l\*(Aqinput deve essere un file leggibile con seek\&.
.SH "OPZIONI"
.PP
Tutte le opzioni a riga di comando si possono impostare usando il file di configurazione; le descrizioni indicano l\*(Aqopzione da impostare\&. Per le opzioni booleane si pu\(`o scavalcare il file di configurazione usando qualcosa come
\fB\-f\-\fR,
\fB\-\-no\-f\fR,
\fB\-f=no\fR
o diverse altre varianti\&.
.PP
\fB\-s\fR, \fB\-\-source\fR
.RS 4
Usa l\*(Aqordinamento dei campi dell\*(Aqindice dei sorgenti\&. Voce di configurazione:
APT::SortPkgs::Source\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra un breve riassunto sull\*(Aquso\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Mostra la versione del programma\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
File di configurazione; specifica un file di configurazione da usare\&. Il programma legge il file di configurazione predefinito e poi questo file di configurazione\&. Se \(`e necessario modificare le impostazioni di configurazione prima che vengano analizzati i file di configurazione predefiniti, specificare un file con la variabile d\*(Aqambiente
\fBAPT_CONFIG\fR\&. Vedere
\fBapt.conf\fR(5)
per informazioni sulla sintassi\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Imposta un\*(Aqopzione di configurazione; imposter\(`a una qualunque opzione di configurazione\&. La sintassi \(`e
\fB\-o Pinco::Pallo=pallo\fR\&.
\fB\-o\fR
e
\fB\-\-option\fR
si possono usare pi\(`u volte per impostare opzioni diverse\&.
.RE
.SH "VEDERE ANCHE"
.PP
\fBapt.conf\fR(5)
.SH "DIAGNOSTICA"
.PP
\fBapt\-sortpkgs\fR
restituisce zero in caso di funzionamento normale e il valore decimale 100 in caso di errore\&.
.SH "BUG"
.PP
\m[blue]\fBPagina dei bug di APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Se si desidera segnalare un bug in APT, vedere
/usr/share/doc/debian/bug\-reporting\&.txt
o il comando
\fBreportbug\fR(1)\&.
.SH "TRADUZIONE"
.PP
Traduzione in italiano a cura del Team italiano di localizzazione di Debian
<debian\-l10n\-italian@lists\&.debian\&.org>\&. In particolare hanno contribuito Eugenia Franzoni (2000), Hugh Hartmann (2000\-2012), Gabriele Stilli (2012), Beatrice Torracca (2012, 2014, 2015)\&.
.PP
Notare che questa versione tradotta del documento pu\(`o contenere parti non tradotte\&. Ci\(`o \(`e voluto, per evitare di perdere contenuti quando la traduzione non \(`e aggiornata rispetto all\*(Aqoriginale\&.
.SH "AUTORI"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBTeam APT\fR
.RS 4
.RE
.SH "NOTE"
.IP " 1." 4
Pagina dei bug di APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
