'\" t
.\"     Title: apt-secure
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06\ \&augustus\ \&2016
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT\-SECURE" "8" "06\ \&augustus\ \&2016" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-secure \- Ondersteuning in APT voor de authenticatie van archieven
.SH "OMSCHRIJVING"
.PP
Met ingang van versie 0\&.6 bevat
\fBAPT\fR
code die voor alle pakketbronnen de ondertekening controleert van het bestand Release\&. Dit geeft de garantie dat gegevens uit het archief, zoals pakketten, niet gewijzigd kunnen worden door mensen die geen toegang hebben tot de sleutel waarmee het bestand Release ondertekend wordt\&. Met ingang van versie 1\&.1 vereist
\fBAPT\fR
dat pakketbronnen recente authenticatie\-informatie verstrekken om die pakketbron ongehinderd te kunnen gebruiken\&. Met ingang van versie 1\&.5 moet gewijzigde informatie over de pakketbron in het bestand Release bevestigd worden, vooraleer APT voortgaat met het toepassen van updates die uit die pakketbron afkomstig zijn\&.
.PP
Opmerking: Alle op APT gebaseerde front\-ends voor pakketbeheer, zoals
\fBapt-get\fR(8),
\fBaptitude\fR(8)
en
\fBsynaptic\fR(8), ondersteunen deze authenticatiefunctionaliteit\&. Het is enkel om het eenvoudig te houden dat deze man\-pagina van
APT
gebruikt wordt om die functionaliteit aan ze allemaal toe te schrijven\&.
.SH "NIET\-ONDERTEKENDE PAKKETBRONNEN"
.PP
Indien een archief een niet\-ondertekend Release\-bestand of helemaal geen Release\-bestand heeft, zullen alle hedendaagse versies van APT bij
\fBupdate\fR\-operaties standaard weigeren om er gegevens van op te halen\&. En zelfs als ze tot ophalen verplicht worden, zullen frontends, zoals
\fBapt-get\fR(8), om een expliciete bevestiging vragen als bij een installatieverzoek een pakket uit een dergelijk niet\-geauthenticeerd archief betrokken is\&.
.PP
U kunt alle APT\-clients verplichten om enkel waarschuwingen te geven door de configuratie\-optie
\fBAcquire::AllowInsecureRepositories\fR
op
true
in te stellen\&. U kunt ook individuele pakketbronnen toelaten om onveilig te zijn via de optie
allow\-insecure=yes
in
\fBsources.list\fR(5)\&. Merk op dat onveilige pakketbronnen ten stelligste afgeraden worden en dat alle opties die apt verplichten om deze te blijven ondersteunen, uiteindelijk verwijderd zullen worden\&. Gebruikers beschikken ook over de optie
\fBTrusted\fR, waardoor zelfs de waarschuwingen onderdrukt worden, maar u moet zeker zijn dat u de implicaties ervan begrijpt die uitgelegd worden in
\fBsources.list\fR(5)\&.
.PP
Een pakketbron die zijn eerdere authenticatie\-status zou kwijt spelen zal in geval van een
\fBupdate\fR\-operatie bij alle APT\-clients een foutmelding opleveren, ongeacht het feit of een optie het gebruik van onveilige pakketbronnen toestaat of verbiedt\&. Een dergelijke fout kan voorkomen worden door bijkomend de optie
\fBAcquire::AllowDowngradeToInsecureRepositories\fR
op
true
in te stellen of voor individuele pakketbronnen door de optie
allow\-downgrade\-to\-insecure=yes
te gebruiken in
\fBsources.list\fR(5)\&.
.SH "ONDERTEKENDE PAKKETBRONNEN"
.PP
De vertrouwensketen vanaf een APT\-archief tot de eindgebruiker, bestaat uit verschillende schakels\&.
\fBapt\-secure\fR
is de laatste schakel in die keten\&. Een archief vertrouwen betekent niet dat u er op vertrouwt dat zijn pakketten geen kwaadwillige code bevatten, maar betekent wel dat u de beheerder van het archief vertrouwt\&. Het behoort tot de verantwoordelijkheid van de archiefbeheerder om er voor te zorgen dat de integriteit van het archief gevrijwaard blijft\&.
.PP
apt\-secure controleert geen handtekeningen op pakketniveau\&. Indien u gereedschap nodig heeft om dit te doen, moet u uitkijken naar
\fBdebsig\-verify\fR
en
\fBdebsign\fR
(die respectievelijk in de pakketten debsig\-verify en devscripts te vinden zijn)\&.
.PP
De vertrouwensketen in Debian begint (bijvoorbeeld) wanneer een pakketonderhouder een nieuw pakket of een nieuwe versie ervan naar het Debian archief uploadt\&. Om effectief te worden moet deze upload ondertekend worden met een sleutel uit de sleutelbos van de pakketonderhouders van Debian (te vinden in het pakket debian\-keyring)\&. De sleutels van onderhouders worden door andere onderhouders ondertekend\&. Daarbij worden vaststaande procedures gevolgd om de identiteit van de sleuteleigenaar te kunnen garanderen\&. Vergelijkbare procedures worden in alle op Debian gebaseerde distributies gehanteerd\&.
.PP
Nadat het ge\(:upload pakket geverifieerd werd en toegevoegd aan het archief, wordt de handtekening van de onderhouder verwijderd en wordt de controlesom voor dat pakket berekend en in het bestand Packages opgeslagen\&. Daarna wordt voor alle Packages\-bestanden de controlesom berekend en opgeslagen in het bestand Release\&. Daarna wordt het bestand Release ondertekend door de archiefsleutel voor deze Debian release en verdeeld met de pakketten en de Packages\-bestanden naar de Debian\-spiegelservers\&. De sleutels bevinden zich in de sleutelbos van het Debian\-archief die te vinden is in het pakket
debian\-archive\-keyring\&.
.PP
Eindgebruikers kunnen de ondertekening van het bestand Release controleren, er de controlesom voor een pakket uithalen en die vergelijken met de controlesom van het pakket dat ze handmatig gedownload hebben \- of vertrouwen op APT die dit automatisch doet\&.
.PP
Merk op dat dit niet hetzelfde is als een controle van handtekeningen op het niveau van individuele pakketten\&. Deze werkwijze is ontworpen om twee mogelijke aanvallen te voorkomen:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Netwerkaanval van het type "man\-in\-the\-middle"\&. Zonder de controle van de ondertekening kunnen kwaadwillige personen binnendringen in het proces van het downloaden van pakketten en kwaadaardige software verspreiden\&. Dit kunnen ze doen via het verwerven van controle over een element van het netwerk (router, switch, enz\&.) of via het omleiden van trafiek naar een kwaadaardige server (via ARP of aanvallen van DNS\-spoofing)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gecompromitteerd spiegelservernetwerk\&. Zonder de controle van handtekeningen kan een kwaadwillige persoon een spiegelserver binnendringen en de bestanden die er zich op bevinden wijzigen, om op die manier kwaadaardige software te verspreiden naar alle gebruikers die pakketten van die server downloaden\&.
.RE
.PP
Ze biedt evenwel geen bescherming tegen een aanval gericht tegen de hoofdserver van Debian (die de pakketten ondertekent) of tegen een aanval gericht tegen de sleutel die gebruikt wordt om de Release\-bestanden te ondertekenen\&. In elk geval biedt dit mechanisme wel een aanvulling op een ondertekening op pakketniveau\&.
.SH "INFORMATIEWIJZIGINGEN"
.PP
Het bestand Release bevat behalve de checksums voor de bestanden uit de pakketbron, ook algemene informatie over de pakketbron, zoals origine, codenaam en versienummer van de release\&.
.PP
Deze informatie wordt op verschillende plaatsen weergegeven en dus zou de eigenaar van een pakketbron altijd de juistheid ervan moeten garanderen\&. Daarenboven kan gebruikersconfiguratie, zoals
\fBapt_preferences\fR(5), van deze informatie gebruik maken en er afhankelijk van zijn\&. Daarom moet de gebruiker met ingang van versie 1\&.5 wijzigingen expliciet bevestigen, om te signaleren dat deze voldoende voorbereid is op bijvoorbeeld de nieuwe hoofdrelease van de distributie (bijvoorbeeld aangeduid met de codenaam) die door de pakketbron verdeeld wordt\&.
.SH "CONFIGURATIE OP GEBRUIKERSNIVEAU"
.PP
\fBapt\-key\fR
is het programma dat de sleutelcatalogus beheert die door APT gebruikt wordt om pakketbronnen te vertrouwen\&. Het kan gebruikt worden om sleutels toe te voegen en te verwijderen en de lijst met vertrouwde sleutels weer te geven\&. Het is mogelijk om te begrenzen welke sleutel(s) welk archief kunnen ondertekenen via de optie
\fBSigned\-By\fR
in
\fBsources.list\fR(5)\&.
.PP
Merk op dat een standaardinstallatie reeds alle nodige sleutels bevat om op een veilige manier pakketten op te halen uit de standaard pakketbronnen\&. Met
\fBapt\-key\fR
knoeien is dus enkel nodig als pakketbronnen van derden toegevoegd worden\&.
.PP
Om een nieuwe sleutel toe te voegen, moet u hem eerst downloaden (u moet zich ervan vergewissen dat u bij het ophalen ervan gebruik maakt van een betrouwbaar communicatiekanaal)\&. Daarna voegt u hem toe met
\fBapt\-key\fR
en vervolgens voert u de opdracht
\fBapt\-get update\fR
uit, zodat apt het bestand
InRelease
of
Release\&.gpg
uit de door u geconfigureerde archieven kan ophalen en verifi\(:eren\&.
.SH "CONFIGURATIE VAN DE PAKKETBRON"
.PP
Indien u voor een door u onderhouden archief in een ondertekening van het archief wilt voorzien, moet u het volgende doen:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMaak een Release\-bestand aan voor het hoofdniveau\fR
als dit nog niet bestaat\&. U kunt dit doen met de opdracht
\fBapt\-ftparchive release\fR
(uit het pakket apt\-utils)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIOnderteken het\fR\&. U doet dit door het uitvoeren van de commando\*(Aqs
\fBgpg \-\-clearsign \-o InRelease Release\fR
en
\fBgpg \-abs \-o Release\&.gpg Release\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMaak de vingerafdruk van de sleutel openbaar\fR, zodat uw gebruikers weten welke sleutel ze moeten importeren om de bestanden uit het archief te authenticeren\&. U doet er best aan uw sleutel te verspreiden via een eigen sleutelbospakket, zoals Debian doet met
debian\-archive\-keyring\&. Op die manier kunnen later updates en transities van sleutels automatisch gedistribueerd worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGeef de nodige instructies voor het toevoegen van uw archief en uw sleutel\fR\&. Indien uw gebruikers niet op een veilige manier uw sleutel kunnen bekomen, wordt de hierboven beschreven vertrouwensketen verbroken\&. Hoe u gebruikers kunt helpen om uw sleutel toe te voegen, hangt af van uw archief en het doelpubliek\&. Dit kan gaan van het toevoegen van uw sleutelbospakket aan een ander archief dat de gebruikers reeds geconfigureerd hebben (zoals de standaard pakketbronnen van hun distributie) tot het gebruik maken van het web van vertrouwen\&.
.RE
.PP
Telkens de inhoud van het archief wijzigt (als nieuwe pakketten toegevoegd of verwijderd worden) moet de archiefverantwoordelijke de hierboven beschreven eerste twee stappen hernemen\&.
.SH "ZIE OOK"
.PP
\fBapt.conf\fR(5),
\fBapt-get\fR(8),
\fBsources.list\fR(5),
\fBapt-key\fR(8),
\fBapt-ftparchive\fR(1),
\fBdebsign\fR(1),
\fBdebsig-verify\fR(1),
\fBgpg\fR(1)
.PP
Voor bijkomende achtergrondinformatie kunt u het hoofdstuk raadplegen over de beveiligingsinfrastructuur van Debian,
\m[blue]\fBDebian Security Infrastructure\fR\m[]\&\s-2\u[1]\d\s+2, uit de Securing Debian Manual (ook te vinden in het pakket harden\-doc), alsook de
\m[blue]\fBStrong Distribution HOWTO\fR\m[]\&\s-2\u[2]\d\s+2
door V\&. Alex Brennen\&.
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[3]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "AUTEUR"
.PP
APT werd geschreven door het APT\-team
<apt@packages\&.debian\&.org>\&.
.SH "AUTEURS VAN DE MAN\-PAGINA"
.PP
Deze man\-pagina is gebaseerd op het werk van Javier Fern\('andez\-Sanguino Pe\(~na, Isaac Jones, Colin Walters, Florian Weimer en Michael Vogt\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
Debian Security Infrastructure
.RS 4
\%https://www.debian.org/doc/manuals/securing-debian-howto/ch7
.RE
.IP " 2." 4
Strong Distribution HOWTO
.RS 4
\%http://www.cryptnet.net/fdp/crypto/strong_distro.html
.RE
.IP " 3." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
