'\" t
.\"     Title: apt-key
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 22\ \&november\ \&2016
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT\-KEY" "8" "22\ \&november\ \&2016" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-key \- Hulpprogramma voor het beheer van de sleutels van APT
.SH "SAMENVATTING"
.HP \w'\fBapt\-key\fR\ 'u
\fBapt\-key\fR [\fB\-\-keyring\ \fR\fB\fIbestandsnaam\fR\fR] {add\ \fIbestandsnaam\fR | del\ \fIsleutel\-ID\fR | export\ \fIsleutel\-ID\fR | exportall | list | finger | adv | update | net\-update | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "OMSCHRIJVING"
.PP
\fBapt\-key\fR
wordt gebruikt om de lijst van sleutels te beheren die door apt gebruikt worden om pakketten te authenticeren\&. Pakketten die met deze sleutels geauthenticeerd werden, worden als betrouwbaar beschouwd\&.
.PP
Merk op dat als het gebruik van het commando
\fBapt\-key\fR
gewenst is, dan ook de installatie van de GNU Privacy Guard suite (verpakt in het pakket
gnupg) vereist is\&. Enkel omwille daarvan al wordt het gebruik ervan in programma\*(Aqs (zeker in scripts voor pakketonderhoud) sterk afgeraden\&. Daarenboven wordt de indeling van de uitvoer van alle commando\*(Aqs onvoorspelbaar en kan die wijzigen telkens wanneer de achterliggende commando\*(Aqs wijzigen\&.
\fBapt\-key\fR
zal een dergelijk gebruik trachten te detecteren en geeft in dergelijke gevallen waarschuwingen op de standaard foutuitvoer\&.
.SH "ONDERSTEUNDE SLEUTELBOSBESTANDEN"
.PP
apt\-key ondersteunt enkel de binaire indeling van OpenPGP (ook gekend als "GPG key public ring") bij bestanden met de extensie "gpg" en niet de database\-indeling keybox (sleutelkistje) die in recentere
\fBgpg\fR(1)\-versies als standaard gebruikt wordt voor sleutelbosbestanden\&. Binaire sleutelbosbestanden die met om het even welke versie van apt gebruikt moeten kunnen worden, moeten daarom steeds aangemaakt worden met het commando
\fBgpg \-\-export\fR\&.
.PP
In het andere geval, als op alle systemen die de aangemaakte sleutelbos moeten gebruiken, minstens een versie van apt >= 1\&.4 ge\(:installeerd is, kunt u wel de ASCII\-armor indeling met de extensie "asc" gebruiken die met het commando
\fBgpg \-\-armor \-\-export\fR
gecre\(:eerd kan worden\&.
.SH "COMMANDO\*(AQS"
.PP
\fBadd\fR \fB\fIbestandsnaam\fR\fR
.RS 4
Een nieuwe sleutel toevoegen aan de lijst van betrouwbare sleutels\&. De sleutel wordt gelezen uit het bestand waarvan de naam met de parameter
\fIbestandsnaam\fR
opgegeven werd of uit de standaardinvoer als de bestandsnaam
\-
is\&.
.sp
Het is van cruciaal belang dat bij sleutels die handmatig toegevoegd worden via
\fBapt\-key\fR, geverifieerd wordt of de bewering dat ze toebehoren aan de eigenaar van de pakketbronnen, wel degelijk met de werkelijkheid overeenkomt, anders wordt de
\fBapt-secure\fR(8)\-infrastructuur volledig ondermijnd\&.
.sp
\fIOpmerking\fR: In plaats van dit commando te gebruiken zou u een sleutelbos rechtstreeks in de map
/etc/apt/trusted\&.gpg\&.d/
moeten plaatsen met een descriptieve naam en ofwel "gpg" of "asc" als bestandsextensie\&.
.RE
.PP
\fBdel\fR \fB\fIsleutel\-ID\fR\fR
.RS 4
Een sleutel verwijderen uit de lijst van betrouwbare sleutels\&.
.RE
.PP
\fBexport\fR \fB\fIsleutel\-ID\fR\fR
.RS 4
De sleutel
\fIsleutel\-ID\fR
via de standaarduitvoer weergeven\&.
.RE
.PP
\fBexportall\fR
.RS 4
Alle betrouwbare sleutels op de standaarduitvoer weergeven\&.
.RE
.PP
\fBlist\fR, \fBfinger\fR
.RS 4
Som betrouwbare sleutels op met hun vingerafdruk\&.
.RE
.PP
\fBadv\fR
.RS 4
Geef geavanceerde opties mee met gpg\&. Met
\fBadv \-\-recv\-key\fR
kunt u bijvoorbeeld een sleutel rechtstreeks van een sleutelserver naar de set van betrouwbare sleutels downloaden\&. Merk op dat er
\fIgeen\fR
controles uitgevoerd worden\&. Daarom kan dit gemakkelijk de
\fBapt-secure\fR(8)\-infrastructuur volledig ondermijnen als het onzorgvuldig gebruikt wordt\&.
.RE
.PP
\fBupdate\fR (verouderd)
.RS 4
De lokale sleutelbos bijwerken met de sleutelbos van het archief en de archiefsleutels die niet langer geldig zijn verwijderen uit de lokale sleutelbos\&. De sleutelbos van het archief bevindt zich in het pakket
archive\-keyring
van uw distributie, bijvoorbeeld het pakket
debian\-archive\-keyring
in Debian\&.
.sp
Merk op dat een distributie dit commando niet langer hoeft en ook niet zou mogen gebruiken\&. In plaats daarvan moeten rechtstreeks sleutelbosbestanden meegeleverd worden in de map
/etc/apt/trusted\&.gpg\&.d/\&. Dit voorkomt dat het pakket
gnupg
een vereiste is, en zowel voor pakketonderhouders als voor gebruikers is het makkelijker om sleutels te beheren door eenvoudigweg bestanden toe te voegen of te verwijderen\&.
.RE
.PP
\fBnet\-update\fR
.RS 4
Een bijwerking uitvoeren zoals hiervoor met het commando
\fBupdate\fR, maar in plaats daarvan de sleutelbos van het archief ophalen vanaf een URI en die valideren tegenover een hoofdsleutel\&. Dit veronderstelt dat
\fBwget\fR(1)
ge\(:installeerd is en vereist een versie van APT die gebouwd werd met de nodige instellingen om de sleutel van een server te kunnen ophalen en een hoofdsleutelbos om de validering te kunnen uitvoeren\&. APT in Debian ondersteunt dit commando niet en steunt in de plaats daarvan op
\fBupdate\fR, maar APT in Ubuntu wel\&.
.RE
.SH "OPTIES"
.PP
Merk op dat opties opgegeven moeten worden voor de commando\*(Aqs die in de vorige sectie behandeld werden\&.
.PP
\fB\-\-keyring\fR \fB\fIbestandsnaam\fR\fR
.RS 4
Met deze optie kunt u een specifiek sleutelbosbestand opgeven waarmee het commando moet werken\&. Standaard wordt een commando uitgevoerd op het bestand
trusted\&.gpg
en op alle onderdelen uit de map
trusted\&.gpg\&.d, hoewel
trusted\&.gpg
de primaire sleutelbos is, wat betekent dat bijvoorbeeld alle nieuwe sleutels daar toegevoegd worden\&.
.RE
.SH "BESTANDEN"
.PP
/etc/apt/trusted\&.gpg
.RS 4
Sleutelbos met lokaal vertrouwde sleutels\&. Nieuwe sleutels worden hier toegevoegd\&. Configuratie\-item:
Dir::Etc::Trusted\&.
.RE
.PP
/etc/apt/trusted\&.gpg\&.d/
.RS 4
Bestandsfragmenten met vertrouwde sleutels\&. Bijkomende sleutelbossen kunnen hier opgeslagen worden (door andere pakketten of de systeembeheerder)\&. Configuratie\-item
Dir::Etc::TrustedParts\&.
.RE
.SH "ZIE OOK"
.PP
\fBapt-get\fR(8),
\fBapt-secure\fR(8)
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[1]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "AUTEUR"
.PP
APT werd geschreven door het APT\-team
<apt@packages\&.debian\&.org>\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
