'\" t
.\"     Title: apt-get
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 14\ \&october\ \&2018
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT\-GET" "8" "14\ \&october\ \&2018" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-get \- APT gereedschap voor het behandelen van pakketten \-\- commandoregelinterface
.SH "SAMENVATTING"
.HP \w'\fBapt\-get\fR\ 'u
\fBapt\-get\fR [\fB\-asqdyfmubV\fR] [\fB\-o=\fR\fB\fIconfiguratietekenreeks\fR\fR] [\fB\-c=\fR\fB\fIconfiguratiebestand\fR\fR] [\fB\-t=\fR\fB\fIdoelrelease\fR\fR] [\fB\-a=\fR\fB\fIarchitectuur\fR\fR] {update | upgrade | dselect\-upgrade | dist\-upgrade | install\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | remove\ \fIpakket\fR...  | purge\ \fIpakket\fR...  | source\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | build\-dep\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | download\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | check | clean | autoclean | autoremove | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "OMSCHRIJVING"
.PP
\fBapt\-get\fR
is het gereedschap voor de commandoregel voor het behandelen van pakketten\&. Het kan door de gebruiker beschouwd worden als zijn "backend" (het basisinstrument) voor andere gereedschappen die gebruik maken van de bibliotheek van APT\&. Er bestaan verschillende "front\-end" interfaces, zoals
\fBaptitude\fR(8),
\fBsynaptic\fR(8)
en
\fBwajig\fR(1)\&.
.PP
Tenzij de optie
\fB\-h\fR, of
\fB\-\-help\fR
opgegeven werd, moet een van de onderstaande commando\*(Aqs gebruikt worden\&.
.PP
\fBupdate\fR
.RS 4
update
wordt gebruikt om de indexbestanden van beschikbare pakketten terug te synchroniseren met hun pakketbronnen\&. De indexen worden opgehaald van de locatie(s) die in
/etc/apt/sources\&.list
opgegeven werden\&. Indien bijvoorbeeld een Debian\-archief gebruikt wordt, zal dit commando de bestanden
Packages\&.gz
ophalen en doorzoeken zodat de informatie over nieuwe en bijgewerkte pakketten beschikbaar wordt\&. Een
update
moet altijd uitgevoerd worden voor een
upgrade
of een
dist\-upgrade\&. U moet er rekening mee houden dat de globale voortgangsindicator niet betrouwbaar is, aangezien de grootte van de pakketbestanden vooraf niet gekend is\&.
.RE
.PP
\fBupgrade\fR
.RS 4
upgrade
wordt gebruikt om vanaf de pakketbronnen die in het bestand
/etc/apt/sources\&.list
vermeld worden, de recentste versies te installeren van alle pakketten die momenteel op het systeem ge\(:installeerd zijn\&. Pakketten waarvan een recentere versie beschikbaar is, worden opgehaald en bijgewerkt\&. Onder geen beding worden pakketten die momenteel ge\(:installeerd zijn, verwijderd of worden pakketten die nog niet ge\(:installeerd zijn, opgehaald en ge\(:installeerd\&. Recentere versies van pakketten die momenteel ge\(:installeerd zijn en die niet bijgewerkt kunnen worden zonder de installatiestatus van een ander pakket te wijzigen, zullen op hun huidige versie behouden blijven\&. Vooraf moet een
update
uitgevoerd worden, zodat
\fBapt\-get\fR
weet dat er nieuwere versies van pakketten beschikbaar zijn\&.
.RE
.PP
\fBdist\-upgrade\fR
.RS 4
dist\-upgrade
vervult niet enkel de functie van
upgrade, maar handelt bovendien op een intelligente manier vereisten af die bij de nieuwere pakketversies veranderd zijn\&.
\fBapt\-get\fR
beschikt over een "slim" systeem van conflictoplossing en zal proberen om de belangrijkste pakketten op te waarderen, eventueel, mocht dat nodig blijken, ten koste van minder belangrijke\&. Het kan daarom gebeuren dat het commando
dist\-upgrade
sommige pakketten verwijdert\&. Het bestand
/etc/apt/sources\&.list
bevat een lijst met locaties waarvandaan de gewenste pakketten opgehaald kunnen worden\&. Zie ook
\fBapt_preferences\fR(5)
voor een mechanisme dat toelaat om voor individuele pakketten de algemene instellingen te overschrijven\&.
.RE
.PP
\fBdselect\-upgrade\fR
.RS 4
dselect\-upgrade
wordt gebruikt in combinatie met
\fBdselect\fR(1), het traditionele front\-end van Debian voor pakketbeheer\&.
dselect\-upgrade
volgt de veranderingen op die
\fBdselect\fR(1)
aanbrengt in het
Status\-veld van de beschikbare pakketten en voert de acties uit die nodig zijn om die status waar te maken (bijvoorbeeld het verwijderen van oude en het installeren van nieuwe pakketten)\&.
.RE
.PP
\fBinstall\fR
.RS 4
install
wordt gevolgd door een of meer pakketten die men wenst te installeren of op te waarderen\&. Elk pakket wordt aangeduid met de pakketnaam, niet met zijn volledige unieke bestandsnaam (in een Debian systeem bijvoorbeeld zal
apt\-utils
het argument zijn dat opgegeven wordt en niet
apt\-utils_1\&.8\&.0~alpha3_amd64\&.deb)\&. Alle pakketten die door het/de opgegeven te installeren pakket(ten) vereist worden, zullen eveneens opgehaald en ge\(:installeerd worden\&. Het bestand
/etc/apt/sources\&.list
wordt gebruikt om de gewenste pakketten te vinden\&. Indien aan het eind van een pakketnaam een koppelteken (zonder spatie ertussenin) geplaatst wordt, zal het opgegeven pakket verwijderd worden indien het ge\(:installeerd is\&. Net zo kan een plus\-teken gebruikt worden om op te geven dat een pakket ge\(:installeerd moet worden\&. Deze laatstgenoemde werkwijzen kunnen gebruikt worden om beslissingen te overschrijven die door het conflictoplossingssysteem van apt\-get genomen worden\&.
.sp
Een specifieke versie van een pakket kiezen voor installatie kan door de pakketnaam te laten volgen door een gelijkheidsteken en de te selecteren versie van het pakket\&. Dit zorgt ervoor dat die versie wordt opgezocht en voor installatie geselecteerd wordt\&. Eveneens kan een specifieke distributie geselecteerd worden door de pakketnaam te laten volgen door een slash en de versie van de distributie of de archiefnaam ervan (stable, testing, unstable)\&.
.sp
Beide versieselectiemechanismes kunnen pakketten degraderen en moeten met zorg gebruikt worden\&.
.sp
Dit is ook de aangewezen werkwijze indien u een of meer reeds ge\(:installeerde pakketten wilt opwaarderen zonder alle op het systeem aanwezige pakketten op te waarderen\&. In tegenstelling tot het commando "upgrade", dat de recentste versie installeert van alle op het systeem aanwezige pakketten, zal "install" enkel de recentste versie installeren van het/de opgegeven pakket(ten)\&. Geef gewoon de naam op van het/de pakket(ten) dat/die u wenst op te waarderen en, indien er een recentere versie beschikbaar is, zal die (samen met zijn vereisten, zoals hiervoor uitgelegd werd) gedownload en ge\(:installeerd worden\&.
.sp
Tot slot stelt het mechanisme
\fBapt_preferences\fR(5)
u in staat om voor individuele pakketten een ander installatiebeleid te cre\(:eren\&.
.sp
Indien geen enkel pakket overeenkomt met de opgegeven expressie en de expressie een \*(Aq\&.\*(Aq, \*(Aq?\*(Aq of \*(Aq*\*(Aq bevat, dan wordt aangenomen dat het om een POSIX reguliere expressie gaat en wordt die toegepast op alle pakketnamen uit de database\&. Elke overeenkomst wordt dan ge\(:installeerd (of verwijderd)\&. Merk op dat het zoeken naar een overeenkomst gebeurt per deeltekenreeks, zodat \*(Aqlo\&.*\*(Aq zowel met \*(Aqhow\-lo\*(Aq als met \*(Aqlowest\*(Aq een overeenkomst oplevert\&. Indien dit niet wenselijk is, veranker de reguliere expressie dan met behulp van het teken \*(Aq^\*(Aq of \*(Aq$\*(Aq of maak de reguliere expressie specifieker\&.
.RE
.PP
\fBremove\fR
.RS 4
remove
is identiek aan
install
behalve dat pakketten ermee verwijderd in plaats van ge\(:installeerd worden\&. Merk op dat het verwijderen van een pakket de configuratiebestanden ervan op het systeem laat staan\&. Indien een plus\-teken aan de pakketnaam toegevoegd wordt (zonder spatie ertussenin), zal het opgegeven pakket ge\(:installeerd in plaats van verwijderd worden\&.
.RE
.PP
\fBpurge\fR
.RS 4
purge
is identiek aan
remove
behalve dat pakketten verwijderd en gewist worden (ook eventuele configuratiebestanden worden verwijderd)\&.
.RE
.PP
\fBsource\fR
.RS 4
source
doet
\fBapt\-get\fR
bronpakketten ophalen\&. APT zal de beschikbare pakketten doorzoeken om uit te maken welk bronpakket opgehaald moet worden\&. Het zal de meest recente beschikbare versie van dat bronpakket opzoeken, ophalen en in de huidige map plaatsen\&. Het respecteert daarbij waar mogelijk de standaarduitgave, ingesteld met de optie
APT::Default\-Release, de optie
\fB\-t\fR
of opgegeven per pakket via de syntaxis
pkg/release\&.
.sp
The arguments are interpreted as binary and source package names\&. See the
\fB\-\-only\-source\fR
option if you want to change that\&.
.sp
De opvolging van bronpakketten gebeurt afzonderlijk, los van de binaire pakketten, via
deb\-src\-regels in het bestand
\fBsources.list\fR(5)\&. Dit betekent dat u een dergelijke regel moet toevoegen per pakketbron waarvan u bronpakketten wilt ophalen\&. Anders zult u wellicht de verkeerde versie (te oud/te recent) van het bronpakket krijgen of helemaal geen\&.
.sp
Indien de optie
\fB\-\-compile\fR
opgegeven werd, zal het pakket tot een binair \&.deb\-bestand gecompileerd worden met behulp van de opdracht
\fBdpkg\-buildpackage\fR
en dit voor de architectuur die met de optie
\fB\-\-host\-architecture\fR
opgegeven werd\&. Als de optie
\fB\-\-download\-only\fR
opgegeven werd, zal het bronpakket niet uitgepakt worden\&.
.sp
Een specifieke versie van de broncode kunt u ophalen door de naam van het bronpakket te laten volgen door een gelijkheidsteken en de op te halen versie\&. Dit mechanisme is gelijkaardig aan datgene wat voor pakketbestanden gebruikt wordt\&. Dit maakt het mogelijk een exacte overeenkomst met de naam en het versienummer van het bronpakket te gebruiken, wat neerkomt op het impliciet aanzetten van de optie
APT::Get::Only\-Source\&.
.sp
Merk op dat in tegenstelling tot binaire pakketten, bronpakketten niet opgenomen en opgevolgd worden in de database van
\fBdpkg\fR\&. Ze worden gewoon opgehaald en in de huidige map geplaatst, zoals tar\-archieven van broncode\&.
.RE
.PP
\fBbuild\-dep\fR
.RS 4
build\-dep
doet apt\-get pakketten installeren/verwijderen i een poging om te voldoen aan de vereisten voor het bouwen van een bronpakket\&. Standaard wordt voldaan aan de vereisten voor het bouwen van het pakket voor de architectuur van het systeem\&. In de plaats daarvan kan desgewenst een architectuur gespecificeerd worden met de optie
\fB\-\-host\-architecture\fR\&.
.sp
The arguments are interpreted as binary or source package names\&. See the
\fB\-\-only\-source\fR
option if you want to change that\&.
.RE
.PP
\fBcheck\fR
.RS 4
check
is een diagnostisch gereedschap; het werkt de pakketcache bij en controleert op defecte vereisten\&.
.RE
.PP
\fBdownload\fR
.RS 4
download
zal het opgegeven binaire pakket ophalen en in de huidige map plaatsen\&.
.RE
.PP
\fBclean\fR
.RS 4
clean
ruimt de lokale opslagplaats voor opgehaalde pakketbestanden op\&. Op het vergrendelingsbestand na ruimt het in
/var/cache/apt/archives/
en
/var/cache/apt/archives/partial/
alles op\&.
.RE
.PP
\fBautoclean\fR (en de \fBauto\-clean\fR alias sinds 1\&.1)
.RS 4
Net als
clean
ruimt
autoclean
de lokale opslagplaats voor opgehaalde pakketbestanden op\&. Het verschil is dat het enkel pakketbestanden opruimt die niet langer opgehaald kunnen worden en goeddeels waardeloos zijn\&. Dit laat toe om gedurende een lange tijd een cache bij te houden zonder dat die onbeheersbaar wordt\&. Door het uitzetten van de configuratieoptie
APT::Clean\-Installed
kan het opruimen van pakketbestanden van ge\(:installeerde pakketten verhinderd worden\&.
.RE
.PP
\fBautoremove\fR (en de \fBauto\-remove\fR alias sinds 1\&.1)
.RS 4
autoremove
wordt gebruikt om pakketten te verwijderen die automatisch ge\(:installeerd werden om te voldoen aan de vereisten van andere pakketten en nu niet langer nodig zijn\&.
.RE
.PP
\fBchangelog\fR
.RS 4
changelog
tracht het changelog\-bestand (logbestand met veranderingen) van een pakket op te halen en geeft dit weer via het commando
\fBsensible\-pager\fR\&. Standaard wordt het logbestand met wijzigingen weergegeven voor de ge\(:installeerde versie\&. U kunt evenwel dezelfde opties opgeven als bij het commando
\fBinstall\fR\&.
.RE
.PP
\fBindextargets\fR
.RS 4
Geeft standaard een volgens deb822 ingedeelde lijst weer met informatie over alle gegevensbestanden (ook soms indexbestanden of indexdoelen genoemd) die
\fBapt\-get update\fR
zou downloaden\&. Ondersteunt de optie
\fB\-\-format\fR
voor het aanpassen van de indeling van de uitvoer en accepteert ook regels uit de standaarduitvoer om er de gegevens mee te filteren\&. Het commando wordt hoofdzakelijk gebruikt als een interface voor extern gereedschap dat APT gebruikt om informatie te verkrijgen evenals de namen van opgehaalde bestanden, zodat ook dat gereedschap er gebruik van kan maken in plaats van ze ook zelf weer op te halen\&. Meer gedetailleerde documentatie wordt hier niet gegeven, maar is daarentegen wel te vinden in het bestand
/usr/share/doc/apt\-doc/acquire\-additional\-files\&.md\&.gz
dat te vinden is in het pakket
apt\-doc\&.
.RE
.SH "OPTIES"
.PP
Alle commandoregelopties kunnen via het configuratiebestand ingesteld worden\&. de omschrijving geeft de in te stellen configuratieoptie op\&. Bij booleaanse opties kunt u instellingen uit het configuratiebestand overschrijven door iets te gebruiken als
\fB\-f\-\fR,
\fB\-\-no\-f\fR,
\fB\-f=no\fR
en meerdere andere variaties\&.
.PP
\fB\-\-no\-install\-recommends\fR
.RS 4
Aanbevolen pakketten niet als te installeren vereisten beschouwen\&. Configuratie\-item:
APT::Install\-Recommends\&.
.RE
.PP
\fB\-\-install\-suggests\fR
.RS 4
Voorgestelde pakketten als te installeren vereisten beschouwen\&. Configuratie\-item:
APT::Install\-Suggests\&.
.RE
.PP
\fB\-d\fR, \fB\-\-download\-only\fR
.RS 4
Enkel downloaden; pakketbestanden worden enkel opgehaald, niet uitgepakt of ge\(:installeerd\&. Configuratie\-item:
APT::Get::Download\-Only\&.
.RE
.PP
\fB\-f\fR, \fB\-\-fix\-broken\fR
.RS 4
Herstellen; proberen een systeem met defecte vereisten te repareren\&. Als deze optie gebruikt wordt samen met install/remove, kan ze elk pakket overslaan om APT toe te laten tot een aannemelijke oplossing te komen\&. Indien pakketten opgegeven worden, moeten die het probleem volledig repareren\&. Soms is deze optie nodig wanneer APT voor de eerste keer uitgevoerd wordt\&. APT zelf laat niet toe dat op een systeem defecte pakketvereisten voorkomen\&. Het is mogelijk dat de vereistenstructuur van een systeem dermate defect is dat een manuele interventie noodzakelijk is (hetgeen meestal betekent dat
\fBdpkg \-\-remove\fR
moet gebruikt worden om sommige problematische pakketten uit de weg te ruimen)\&. Het gebruik van deze optie samen met
\fB\-m\fR
kan in sommige omstandigheden een fout opleveren\&. Configuratie\-item:
APT::Get::Fix\-Broken\&.
.RE
.PP
\fB\-m\fR, \fB\-\-ignore\-missing\fR, \fB\-\-fix\-missing\fR
.RS 4
Ontbrekende pakketten negeren; indien pakketten niet opgehaald kunnen worden of indien na het ophalen de integriteitstoets mislukt (beschadigde pakketbestanden), behoud dan de ge\(:installeerde versie van deze pakketten en ga om met het resultaat\&. Het gebruik van deze optie samen met
\fB\-f\fR
kan in sommige situaties tot een fout leiden\&. Indien een pakket voor installatie geselecteerd werd (in het bijzonder wanneer het aan de commandoregel vermeld werd) en het niet opgehaald kon worden, dan zal het stilzwijgend op zijn huidige versie behouden blijven\&. Configuratie\-item:
APT::Get::Fix\-Missing\&.
.RE
.PP
\fB\-\-no\-download\fR
.RS 4
Schakelt het downloaden van pakketten uit\&. Dit wordt best gebruikt samen met
\fB\-\-ignore\-missing\fR
om APT te verplichten enkel \&.debs te gebruiken die het al gedownload heeft\&. Configuratie\-item:
APT::Get::Download\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Stil; produceert uitvoer, geschikt voor een logboekbestand\&. Voortgangsindicatoren worden overgeslagen\&. Meer q\*(Aqs, met een maximum van 2, maken de uitvoer beknopter\&. U kunt ook
\fB\-q=#\fR
gebruiken om het niveau van beknopte uitvoer in te stellen en de waarde uit het configuratiebestand te overschrijven\&. Merk op dat beknopte uitvoer van het niveau 2 de optie
\fB\-y\fR
impliceert; u zou nooit \-qq zonder een optie van het type niets doen, zoals \-d, \-\-print\-uris of \-s, moeten gebruiken, omdat APT kan beslissen iets te gaan doen waaraan u zich niet verwachtte\&. Configuratie\-item:
quiet\&.
.RE
.PP
\fB\-s\fR, \fB\-\-simulate\fR, \fB\-\-just\-print\fR, \fB\-\-dry\-run\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 4
Geen actie; voer een simulatie uit van de gebeurtenissen die zich zouden voordoen op basis van de actuele toestand van het systeem, maar voer geen effectieve wijzigingen aan het systeem door\&. Vergrendeling wordt uitgeschakeld (\fBDebug::NoLocking\fR), zodat de toestand van het systeem eventueel zou kunnen wijzigen terwijl
\fBapt\-get\fR
bezig is\&. Ook een niet\-systeembeheerder (non\-root) kan simulaties uitvoeren en als die geen leestoegang heeft tot alle configuraties van apt, kan dit de simulatie vertekenen\&. Niet\-systeembeheerders krijgen standaard ook een opmerking te zien waarin deze waarschuwing gegeven wordt (\fBAPT::Get::Show\-User\-Simulation\-Note\fR)\&. Configuratie\-item:
APT::Get::Simulate\&.
.sp
Als men een simulatie uitvoert, worden een aantal regels weergegeven, waarbij elke regel een operatie van
\fBdpkg\fR
vertegenwoordigt: configureren (Conf), verwijderen (Remv) of uitpakken (Inst)\&. Rechte haakjes duiden op defecte pakketten en lege rechte haakjes duiden op defecten zonder gevolgen (komt zelden voor)\&.
.RE
.PP
\fB\-y\fR, \fB\-\-yes\fR, \fB\-\-assume\-yes\fR
.RS 4
Een automatisch ja op vragen; ga uit van een ja\-antwoord op alle vragen en voer de operatie niet\-interactief uit\&. Indien er zich een niet\-wenselijke situatie voordoet, zoals het wijzigen van een op zijn huidige versie vastgehouden pakket, een poging om een niet\-geauthenticeerd pakket te installeren of het verwijderen van een essentieel pakket, zal
apt\-get
afgebroken worden\&. Configuratie\-item:
APT::Get::Assume\-Yes\&.
.RE
.PP
\fB\-\-assume\-no\fR
.RS 4
Een automatisch "neen" op alle vragen\&. Configuratie\-item:
APT::Get::Assume\-No\&.
.RE
.PP
\fB\-\-no\-show\-upgraded\fR
.RS 4
Geef geen lijst weer van alle pakketten die opgewaardeerd zullen worden\&. Configuratie\-item:
APT::Get::Show\-Upgraded\&.
.RE
.PP
\fB\-V\fR, \fB\-\-verbose\-versions\fR
.RS 4
Geef het volledige versienummer weer van opgewaardeerde en ge\(:installeerde pakketten\&. Configuratie\-item:
APT::Get::Show\-Versions\&.
.RE
.PP
\fB\-a\fR, \fB\-\-host\-architecture\fR
.RS 4
Deze optie regelt voor welke architectuur pakketten gebouwd worden met de opdracht
\fBapt\-get source \-\-compile\fR
en hoe aan kruiselingse bouwvereisten voldaan wordt\&. Standaard staat dit niet ingesteld hetgeen betekent dat de computer waarop het pakket gebouwd wordt dezelfde architectuur heeft als die waarvoor het gebouwd wordt (hetgeen ingesteld wordt met
APT::Architecture)\&. Configuratie\-item:
APT::Get::Host\-Architecture\&.
.RE
.PP
\fB\-P\fR, \fB\-\-build\-profiles\fR
.RS 4
Deze optie regelt het activeren van bouwprofielen waarvoor een bronpakket gebouwd wordt met
\fBapt\-get source \-\-compile\fR\&. Ze regelt ook hoe voldaan wordt aan de bouwvereisten\&. Standaard is geen enkel bouwprofiel actief\&. Er kan meer dan een bouwprofiel tegelijk geactiveerd worden door ze gescheiden door en komma samen te voegen\&. Configuratie\-item:
APT::Build\-Profiles\&.
.RE
.PP
\fB\-b\fR, \fB\-\-compile\fR, \fB\-\-build\fR
.RS 4
Bronpakketten na het downloaden compileren\&. Configuratie\-item:
APT::Get::Compile\&.
.RE
.PP
\fB\-\-ignore\-hold\fR
.RS 4
Instructies dat pakketten op hun huidige versie behouden moeten blijven, negeren; dit zorgt ervoor dat
\fBapt\-get\fR
de bij een pakket horende instructie \*(Aqbehouden op de huidige versie\*(Aq negeert\&. Dit kan nuttig zijn in combinatie met
dist\-upgrade
om een groot aantal onwenselijke instructies van het type \*(Aqbehouden op de huidige versie\*(Aq te overschrijven\&. Configuratie\-item:
APT::Ignore\-Hold\&.
.RE
.PP
\fB\-\-with\-new\-pkgs\fR
.RS 4
Toelaten dat nieuwe pakketten ge\(:installeerd worden als dit gebruikt wordt in combinatie met
upgrade\&. Dit is nuttig als het voor het bijwerken van een ge\(:installeerd pakket nodig is om nieuwe vereisten te installeren\&. In plaats van het pakket op de huidige versie vast te houden, zal
upgrade
het pakket opwaarderen en de nieuwe vereisten installeren\&. Merk op dat
upgrade
met deze optie nooit pakketten zal verwijderen\&. Enkel nieuwe toevoegen is dan toegestaan\&. Configuratie\-item:
APT::Get::Upgrade\-Allow\-New\&.
.RE
.PP
\fB\-\-no\-upgrade\fR
.RS 4
Geen pakketten opwaarderen; als
no\-upgrade
aan de commandoregel gebruikt wordt in combinatie met
install, zal dat verhinderen dat reeds ge\(:installeerde pakketten opgewaardeerd worden\&. Configuratie\-item:
APT::Get::Upgrade\&.
.RE
.PP
\fB\-\-only\-upgrade\fR
.RS 4
Geen nieuwe pakketten installeren; wanneer
only\-upgrade
gebruikt wordt in combinatie met
install, zal het enkel voor reeds ge\(:installeerde pakketten opwaarderingen installeren en verzoeken om nieuwe pakketten te installeren negeren\&. Configuratie\-item:
APT::Get::Only\-Upgrade\&.
.RE
.PP
\fB\-\-allow\-downgrades\fR
.RS 4
Dit is een gevaarlijke optie die er voor zorgt dat apt zonder vragen voortgaat als het degradaties doorvoert\&. U zou dit niet moeten gebruiken behalve in zeer bijzondere situaties\&. Dit gebruiken kan mogelijkerwijs tot de vernietiging van uw systeem leiden! Configuratie\-item:
APT::Get::allow\-downgrades\&. Ge\(:introduceerd in APT 1\&.1\&.
.RE
.PP
\fB\-\-allow\-remove\-essential\fR
.RS 4
Een ja doordrukken; dit is een gevaarlijke optie die er voor zorgt dat apt zonder vragen voortgaat als het essenti\(:ele pakketten verwijdert\&. U zou dit niet moeten gebruiken behalve in zeer bijzondere situaties\&. Dit gebruiken kan mogelijkerwijs tot de vernietiging van uw systeem leiden! Configuratie\-item:
APT::Get::allow\-remove\-essential\&. Ge\(:introduceerd in APT 1\&.1\&.
.RE
.PP
\fB\-\-allow\-change\-held\-packages\fR
.RS 4
Een ja doordrukken; dit is een gevaarlijke optie die er voor zorgt dat apt zonder vragen voortgaat als het te handhaven pakketten wijzigt\&. U zou dit niet moeten gebruiken behalve in zeer bijzondere situaties\&. Dit gebruiken kan mogelijkerwijs tot de vernietiging van uw systeem leiden! Configuratie\-item:
APT::Get::allow\-change\-held\-packages\&. Ge\(:introduceerd in APT 1\&.1\&.
.RE
.PP
\fB\-\-force\-yes\fR
.RS 4
Een ja doordrukken; dit is een gevaarlijke optie die er voor zorgt dat apt zonder vragen voortgaat als het iets doet dat schadelijk kan zijn\&. U zou dit niet moeten gebruiken behalve in zeer bijzondere situaties\&. Het gebruik van
force\-yes
kan mogelijkerwijs tot de vernietiging van uw systeem leiden! Configuratie\-item:
APT::Get::force\-yes\&. Deze optie is verouderd en werd in 1\&.1 vervangen door
\fB\-\-allow\-unauthenticated\fR
,
\fB\-\-allow\-downgrades\fR
,
\fB\-\-allow\-remove\-essential\fR
,
\fB\-\-allow\-change\-held\-packages\fR\&.
.RE
.PP
\fB\-\-print\-uris\fR
.RS 4
In plaats van pakketten op te halen om ze te installeren wordt hun URI weergegeven\&. Elke URI bevat het pad en de naam van het doelbestand, zijn grootte en de verwachte MD5\-frommel\&. Merk op dat de naam van het bestand waarnaartoe geschreven wordt niet steeds overeenkomt met de bestandsnaam op de externe site! Dit werkt ook met de commando\*(Aqs
source
en
update\&. Bij gebruik in combinatie met het commando
update
zijn de MD5\-frommel en de grootte niet inbegrepen en het is aan de gebruiker om eventuele gecomprimeerde bestanden uit te pakken\&. Configuratie\-item:
APT::Get::Print\-URIs\&.
.RE
.PP
\fB\-\-purge\fR
.RS 4
Purge gebruiken in plaats van remove voor alles wat verwijderd zou worden\&. Er zal een sterretje ("*") staan naast de pakketten die ingepland staan om opgeruimd te worden\&.
\fBremove \-\-purge\fR
is het equivalent van het commando
\fBpurge\fR\&. Configuratie\-item:
APT::Get::Purge\&.
.RE
.PP
\fB\-\-reinstall\fR
.RS 4
Pakketten die reeds met hun nieuwste versie ge\(:installeerd zijn opnieuw installeren\&. Configuratie\-item:
APT::Get::ReInstall\&.
.RE
.PP
\fB\-\-list\-cleanup\fR
.RS 4
Deze optie is standaard aangezet; gebruik
\-\-no\-list\-cleanup
om ze uit te zetten\&. Indien ze geactiveerd is, zal
\fBapt\-get\fR
automatisch de inhoud van
/var/lib/apt/lists
beheren om te garanderen dat in onbruik geraakte bestanden verwijderd worden\&. De enige reden waarom u dit zou uitzetten is wanneer u vaak het bestand sources\&.list wijzigt\&. Configuratie\-item:
APT::Get::List\-Cleanup\&.
.RE
.PP
\fB\-t\fR, \fB\-\-target\-release\fR, \fB\-\-default\-release\fR
.RS 4
Deze optie regelt de standaard invoer voor het aansturen van de beleidsvoering; ze stelt een standaard pinwaarde in op 990 voor de opgegeven release\&. Dit overschrijft de algemene instellingen uit
/etc/apt/preferences\&. De waarde van deze optie heeft geen invloed op pakketten met een eigen pinwaarde\&. Kort samengevat laat deze optie u toe om op een eenvoudige wijze controle te houden over uit welke distributie pakketten opgehaald worden\&. Enkele gebruikelijke voorbeelden zijn
\fB\-t \*(Aq2\&.1*\*(Aq\fR,
\fB\-t unstable\fR
en
\fB\-t sid\fR\&. Configuratie\-item:
APT::Default\-Release; raadpleeg ook de man\-pagina van
\fBapt_preferences\fR(5)\&.
.RE
.PP
\fB\-\-trivial\-only\fR
.RS 4
Voer enkel \*(Aqbanale\*(Aq operaties uit\&. Logisch gezien kan men dit beschouwen als gerelateerd aan
\fB\-\-assume\-yes\fR\&. Waar
\fB\-\-assume\-yes\fR
op elke vraag ja antwoordt, zal
\fB\-\-trivial\-only\fR
nee antwoorden\&. Configuratie\-item:
APT::Get::Trivial\-Only\&.
.RE
.PP
\fB\-\-no\-remove\fR
.RS 4
Indien een of ander pakket verwijderd zou moeten worden, zal apt\-get onmiddellijk afgebroken worden zonder een vraag te stellen\&. Configuratie\-item:
APT::Get::Remove\&.
.RE
.PP
\fB\-\-auto\-remove\fR, \fB\-\-autoremove\fR
.RS 4
Indien het gegeven commando
install
of
remove
is, dan zal deze optie functioneren zoals wanneer de opdracht
autoremove
wordt uitgevoerd en zullen pakketten die niet langer door andere vereist worden, verwijderd worden\&. Configuratie\-item:
APT::Get::AutomaticRemove\&.
.RE
.PP
\fB\-\-only\-source\fR
.RS 4
Is enkel betekenisvol voor de commando\*(Aqs
source
en
build\-dep\&. Geeft aan dat voor de opgegeven namen van bronpakketten niet naar een overeenkomst gezocht moet worden via de tabel met binaire pakketten\&. Dit houdt in dat indien deze optie opgegeven werd, deze commando\*(Aqs enkel de naam van bronpakketten als argument zullen aanvaarden en niet de naam van een binair pakket om nadien het overeenkomstige bronpakket te gaan opzoeken\&. Configuratie\-item:
APT::Get::Only\-Source\&.
.RE
.PP
\fB\-\-diff\-only\fR, \fB\-\-dsc\-only\fR, \fB\-\-tar\-only\fR
.RS 4
Enkel het diff\-, dsc\- of tar\-bestand van een bronarchief downloaden\&. Configuratie\-item:
APT::Get::Diff\-Only,
APT::Get::Dsc\-Only, en
APT::Get::Tar\-Only\&.
.RE
.PP
\fB\-\-arch\-only\fR
.RS 4
Enkel architectuurafhankelijke bouwvereisten verwerken\&. Configuratie\-item:
APT::Get::Arch\-Only\&.
.RE
.PP
\fB\-\-indep\-only\fR
.RS 4
Enkel architectuur\-onafhankelijke bouwvereisten verwerken\&. Configuratie\-item:
APT::Get::Indep\-Only\&.
.RE
.PP
\fB\-\-allow\-unauthenticated\fR
.RS 4
Negeer dat pakketten niet geauthenticeerd kunnen worden en stel er geen vragen over\&. Dit kan nuttig zijn als met lokale pakketbronnen gewerkt wordt, maar het houdt een enorm veiligheidsrisico in als de authenticiteit van de gegevens niet op een andere manier door de gebruiker zelf verzekerd wordt\&. Het gebruik van de optie
\fBTrusted\fR
voor regels uit
\fBsources.list\fR(5)
valt gewoonlijk te verkiezen boven deze globale vervanging\&. Configuratie\-item:
APT::Get::AllowUnauthenticated\&.
.RE
.PP
\fB\-\-no\-allow\-insecure\-repositories\fR
.RS 4
Sta het commando update niet toe om niet\-verifieerbare gegevens op te halen uit geconfigureerde pakketbronnen\&. Het commando update van APT zal mislukken bij pakketbronnen zonder geldige cryptografische ondertekening\&. Zie ook
\fBapt-secure\fR(8)
voor meer informatie over het concept en de implicaties\&. Configuratie\-item:
Acquire::AllowInsecureRepositories\&.
.RE
.PP
\fB\-\-allow\-releaseinfo\-change\fR
.RS 4
Sta het commando update toe om gegevens te blijven downloaden van een pakketbron waarvan de informatie over welke release die pakketbron bevat, gewijzigd is en bijvoorbeeld een nieuwe hoofdrelease aangeeft\&. Voor dergelijke pakketbronnen zal APT er niet in slagen het update\-commando uit te voeren, totdat de verandering bevestigd is, om er zeker van te zijn dat de gebruiker voorbereid is op die verandering\&. Zie ook
\fBapt-secure\fR(8)
voor informatie over concept en configuratie\&.
.sp
Er bestaan specialistische opties (\-\-allow\-releaseinfo\-change\-\fIveld\fR) om enkel veranderingen toe te staan voor bepaalde velden, zoals
origin,
label,
codename,
suite,
version
en
defaultpin\&. Zie ook
\fBapt_preferences\fR(5)\&. Configuratie\-item:
Acquire::AllowReleaseInfoChange\&.
.RE
.PP
\fB\-\-show\-progress\fR
.RS 4
Bij het installeren, opwaarderen of verwijderen van pakketten gebruikersvriendelijke voortgangsinformatie in het terminalvenster weergeven\&. Voor een door een machine te lezen versie van deze gegevens kunt u README\&.progress\-reporting raadplegen in apt\*(Aqs doc\-map\&. Configuratie\-item:
Dpkg::Progress
en
Dpkg::Progress\-Fancy\&.
.RE
.PP
\fB\-\-with\-source\fR \fB\fIbestandsnaam\fR\fR
.RS 4
Voegt het opgegeven bestand toe als een metadatabron\&. Kan herhaald worden om meerdere bestanden toe te voegen\&. Zie voor verdere details de beschrijving van de optie
\fB\-\-with\-source\fR
in
\fBapt-cache\fR(8)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Een korte samenvatting van het gebruik weergeven\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Het versienummer van het programma weergeven\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Configuratiebestand; Een te gebruiken configuratiebestand opgeven\&. Het programma zal het standaard configuratiebestand inlezen en nadien dit configuratiebestand\&. Als configuratie\-instellingen opgegeven moeten worden vooraleer de standaard configuratiebestanden verwerkt worden, geef dan een bestand op met de omgevingsvariabele
\fBAPT_CONFIG\fR\&. Raadpleeg
\fBapt.conf\fR(5)
voor informatie over de syntaxis\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Een configuratieoptie instellen; Dit stelt een willekeurige configuratieoptie in\&. De syntaxis is
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
en
\fB\-\-option\fR
kunnen meermaals gebruikt worden om verschillende opties in te stellen\&.
.RE
.SH "BESTANDEN"
.PP
/etc/apt/sources\&.list
.RS 4
Locaties waarvandaan pakketten opgehaald moeten worden\&. Configuratie\-item:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
Bestandsfragmenten met locaties waarvandaan pakketten opgehaald moeten worden\&. Configuratie\-item:
Dir::Etc::SourceParts\&.
.RE
.PP
/etc/apt/apt\&.conf
.RS 4
Configuratiebestand voor APT\&. Configuratie\-item:
Dir::Etc::Main\&.
.RE
.PP
/etc/apt/apt\&.conf\&.d/
.RS 4
Configuratiebestandsfragmenten voor APT\&. Configuratie\-item:
Dir::Etc::Parts\&.
.RE
.PP
/etc/apt/preferences
.RS 4
Bestand met versievoorkeuren\&. Dit is waar u "pinning" kunt opgeven\&. Dit is een voorkeur voor het ophalen van bepaalde pakketten uit een aparte pakketbron of uit een andere versie van een distributie\&. Configuratie\-item:
Dir::Etc::Preferences\&.
.RE
.PP
/etc/apt/preferences\&.d/
.RS 4
Bestandsfragmenten met versievoorkeuren\&. Configuratie\-item:
Dir::Etc::PreferencesParts\&.
.RE
.PP
/var/cache/apt/archives/
.RS 4
Opslaggebied voor opgehaalde pakketbestanden\&. Configuratie\-item:
Dir::Cache::Archives\&.
.RE
.PP
/var/cache/apt/archives/partial/
.RS 4
Opslaggebied voor pakketbestanden tijdens het ophalen\&. Configuratie\-item:
Dir::Cache::Archives
(partial
zal impliciet toegevoegd worden)
.RE
.PP
/var/lib/apt/lists/
.RS 4
Opslaggebied voor statusinformatie over elke pakketbron vermeld in
\fBsources.list\fR(5)
Configuratie\-item:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Opslaggebied voor statusinformatie tijdens het ophalen\&. Configuratie\-item:
Dir::State::Lists
(partial
zal impliciet toegevoegd worden)
.RE
.SH "ZIE OOK"
.PP
\fBapt-cache\fR(8),
\fBapt-cdrom\fR(8),
\fBdpkg\fR(1),
\fBsources.list\fR(5),
\fBapt.conf\fR(5),
\fBapt-config\fR(8),
\fBapt-secure\fR(8), De gebruikershandleiding voor APT in /usr/share/doc/apt\-doc/,
\fBapt_preferences\fR(5), de Howto voor APT\&.
.SH "DIAGNOSTIEK"
.PP
\fBapt\-get\fR
geeft de terugkeerwaarde nul bij een normaal verlopen operatie, het decimaal getal 100 in geval van een fout\&.
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[1]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
