'\" t
.\"     Title: apt-cache
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 16\ \&augustus\ \&2016
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Dutch
.\"
.TH "APT\-CACHE" "8" "16\ \&augustus\ \&2016" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-cache \- zoeken in de cache van APT
.SH "SAMENVATTING"
.HP \w'\fBapt\-cache\fR\ 'u
\fBapt\-cache\fR [\fB\-agipns\fR] [\fB\-o=\fR\fB\fIconfiguratietekenreeks\fR\fR] [\fB\-c=\fR\fB\fIconfiguratiebestand\fR\fR] {gencaches | showpkg\ \fIpakket\fR...  | showsrc\ \fIpakket\fR...  | stats | dump | dumpavail | unmet | search\ \fIreguliere_expressie\fR...  | show\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | depends\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | rdepends\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | pkgnames\ [\fIprefix\fR]  | dotty\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | xvcg\ \fIpakket\fR\ [{=\fIpakketversienummer\fR\ |\ /\fIdoelrelease\fR}]...  | policy\ [\fIpakket\fR...]  | madison\ \fIpakket\fR...  | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "OMSCHRIJVING"
.PP
\fBapt\-cache\fR
voert verschillende operaties uit op de pakketcache van APT\&.
\fBapt\-cache\fR
wijzigt de toestand van het systeem niet, maar voorziet in operaties die de metadata van een pakket doorzoeken en er interessante uitvoer mee genereren\&. De metadata worden verkregen en bijgewerkt via het commando \*(Aqupdate\*(Aq van bijvoorbeeld
\fBapt\-get\fR, waardoor ze verouderd kunnen zijn als de laatste update te lang geleden is\&. Maar daartegenover staat dat de werking van
\fBapt\-cache\fR
niet afhankelijk is van de beschikbaarheid van de geconfigureerde pakketbronnen (bijv\&. offline)\&.
.PP
Tenzij de optie
\fB\-h\fR, of
\fB\-\-help\fR
opgegeven werd, moet een van de onderstaande commando\*(Aqs gebruikt worden\&.
.PP
\fBgencaches\fR
.RS 4
gencaches
maakt de pakketcache van APT aan\&. Als die ontbreekt of verouderd is, wordt dit commando impliciet uitgevoerd door alle commando\*(Aqs die deze cache nodig hebben\&.
.RE
.PP
\fBshowpkg\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
showpkg
geeft informatie weer over de aan de commandoregel opgesomde pakketten\&. De overige argumenten zijn pakketnamen\&. De beschikbare versies en achterwaartse vereisten van ieder opgesomd pakket worden weergegeven, evenals de voorwaartse vereisten voor elke versie\&. Voorwaartse (normaal) vereisten zijn die pakketten waarvan het pakket in kwestie afhankelijk is\&. Achterwaartse vereisten zijn die pakketten die afhankelijk zijn van het pakket in kwestie\&. Dus, aan de voorwaartse vereisten van een pakket moet voldaan worden, aan de achterwaartse vereisten niet\&. Bijvoorbeeld,
\fBapt\-cache showpkg libreadline2\fR
zal uitvoer genereren in de zin van:
.sp
.if n \{\
.RS 4
.\}
.nf
Package: libreadline2
Versions: 2\&.1\-12(/var/state/apt/lists/foo_Packages),
Reverse Depends: 
  libreadlineg2,libreadline2
  libreadline2\-altdev,libreadline2
Dependencies:
2\&.1\-12 \- libc5 (2 5\&.4\&.0\-0) ncurses3\&.0 (0 (null))
Provides:
2\&.1\-12 \- 
Reverse Provides: 
.fi
.if n \{\
.RE
.\}
Hier is dus te zien dat libreadline2, versie 2\&.1\-12, afhankelijk is van libc5 en ncurses3\&.0 die ge\(:installeerd moeten zijn opdat libreadline2 zou werken\&. Op hun beurt zijn libreadlineg2 en libreadline2\-altdev afhankelijk van libreadline2\&. Indien libreadline2 ge\(:installeerd wordt, moeten ook libc5 en ncurses3\&.0 (en ldso) ge\(:installeerd zijn; libreadlineg2 en libreadline2\-altdev moeten niet ge\(:installeerd worden\&. Om de exacte betekenis van de rest van de uitvoer te kennen, raadpleegt u best de broncode van apt\&.
.RE
.PP
\fBstats\fR
.RS 4
stats
geeft enkele statistieken weer over de cache\&. Er worden geen andere argumenten verwacht\&. De weergegeven statistieken zijn:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total package names
is het aantal pakketnamen dat in de cache gevonden werd\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Normal packages
is het aantal reguliere, gewone pakketnamen; dit zijn pakketten met een \('e\('en\-op\-\('e\('en relatie tussen hun naam en de naam waarmee andere pakketten naar hen verwijzen om een vereiste aan te geven\&. De meerderheid van de pakketten valt in deze categorie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pure virtual packages
is het aantal pakketten dat enkel bestaat als een virtuele pakketnaam\&. Dit houdt in dat pakketten enkel "voorzien in" de virtuele pakketnaam en dat geen enkel pakket echt die naam gebruikt\&. Bijvoorbeeld, "mail\-transport\-agent" is in het Debian systeem een zuiver virtueel pakket\&. Verschillende pakketten voorzien in "mail\-transport\-agent", maar er is geen enkel pakket dat de naam "mail\-transport\-agent" draagt\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Single virtual packages
is het aantal virtuele pakketten waarvoor slechts een pakket in dat specifieke virtuele pakket voorziet\&. In het Debian systeem is bijvoorbeeld "X11\-text\-viewer" een virtueel pakket, maar slechts een pakket, xless, voorziet in "X11\-text\-viewer"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mixed virtual packages
is het aantal pakketten dat ofwel voorziet in een specifiek virtueel pakket of als pakketnaam de naam van het virtueel pakket draagt\&. In het Debian systeem is "debconf" bijvoorbeeld tegelijk een echt pakket en tevens wordt er in voorzien door het pakket debconf\-tiny\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Missing
is het aantal pakketnamen waarnaar verwezen wordt in een vereiste, maar waarin door geen enkel pakket voorzien wordt\&. Ontbrekende pakketten kunnen opduiken wanneer men geen toegang heeft tot een volledige distributie of indien een pakket (re\(:eel of virtueel) verwijderd werd uit de distributie\&. Gewoonlijk wordt ernaar verwezen in een Conflicts of een Breaks declaratie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total distinct
versies is het aantal pakketversies dat in de cache aangetroffen wordt\&. Indien er gebruik gemaakt wordt van meer dan een distributie (bijvoorbeeld "stable" en "unstable"), dan kan deze waarde aanzienlijk groter zijn dan het totale aantal pakketnamen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total dependencies
is het totaal aantal vereistenrelaties die alle pakketten die zich in de cache bevinden, samen opvragen\&.
.RE
.sp
.RE
.PP
\fBshowsrc\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
showsrc
geeft alle fiches van bronpakketten weer die overeenkomen met de opgegeven pakketnamen\&. Alle versies worden weergegeven evenals alle fiches van binaire pakketten die met de naam overeenkomen\&. Gebruik
\fB\-\-only\-source\fR
om louter bronpakketten weer te geven\&.
.RE
.PP
\fBdump\fR
.RS 4
dump
geeft een beknopte lijst weer van alle pakketten uit de cache\&. Dit is in de eerste plaats bedoeld om te debuggen\&.
.RE
.PP
\fBdumpavail\fR
.RS 4
dumpavail
geeft op stdout een lijst van beschikbare pakketten weer\&. Dit is geschikt om gebruikt te worden met
\fBdpkg\fR(1)
en ook de meethode
\fBdselect\fR(1)
maakt er gebruik van\&.
.RE
.PP
\fBunmet\fR
.RS 4
unmet
geeft een samenvatting van alle vereisten waaraan in de pakketcache niet voldaan wordt\&.
.RE
.PP
\fBshow\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
show
vervult een functie die vergelijkbaar is met
\fBdpkg \-\-print\-avail\fR\&. Het geeft de pakketsteekkaarten weer van de genoemde pakketten\&.
.RE
.PP
\fBsearch\fR \fB\fIreguliere_expressie\fR\fR\fB\&...\fR
.RS 4
search
doorzoekt de volledige inhoud van alle beschikbare pakketlijsten aan de hand van de opgegeven POSIX reguliere expressie; zie
\fBregex\fR(7)\&. Het zoekt in de pakketnamen en de beschrijvingen of de reguliere expressie erin aangetroffen wordt en geeft de pakketnaam en de beknopte beschrijving weer, met inbegrip van de pakketnamen van virtuele pakketten\&. Indien
\fB\-\-full\fR
opgegeven werd, dan wordt voor elk overeenkomstig pakket een uitvoer geproduceerd die identiek is aan die van
show\&. En indien
\fB\-\-names\-only\fR
werd opgegeven, dan wordt niet in de uitgebreide omschrijving gezocht, maar wordt enkel de pakketnaam en de pakketten waarin voorzien wordt doorzocht\&.
.sp
Men kan afzonderlijke argumenten opgeven om verschillende zoekpatronen te specificeren, waarop dan een logische en toegepast wordt\&.
.RE
.PP
\fBdepends\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
depends
geeft een lijst weer van alle vereisten van een pakket en alle mogelijke andere pakketten die aan deze vereisten tegemoet kunnen komen\&.
.RE
.PP
\fBrdepends\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
rdepends
geeft de lijst van alle achterwaartse vereisten van een pakket weer\&.
.RE
.PP
\fBpkgnames\fR [\fIprefix\fR]
.RS 4
Dit commando geeft de naam weer van elk pakket dat door APT gekend is\&. Een prefix om de lijst van pakketnamen te filteren kan als optioneel argument gegeven worden\&. De uitvoer is geschikt om gebruikt te worden met de shell\-functie Tab\-aanvulling en ze wordt extreem snel gegenereerd\&. Dit commando wordt best gebruikt met de optie
\fB\-\-generate\fR\&.
.sp
Merk op dat een pakket waarvan APT weet heeft niet noodzakelijk gedownload of ge\(:installeerd kan worden of ge\(:installeerd is\&. Virtuele pakketten worden bijvoorbeeld ook opgenomen in de gegenereerde lijst\&.
.RE
.PP
\fBdotty\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
dotty
pikt op de commandoregel een lijst pakketten op en genereert uitvoer die geschikt is om gebruikt te worden door dotty uit het pakket
\m[blue]\fBGraphViz\fR\m[]\&\s-2\u[1]\d\s+2\&. Het resultaat is een geheel van knooppunten en gebogen lijnen die de relaties tussen pakketten voorstellen\&. Standaard trekken de als argument opgegeven pakketten al hun vereisten na, hetgeen een zeer uitgebreide grafiek kan opleveren\&. Om de uitvoer te beperken tot die pakketten die expliciet opgegeven werden aan de commandoregel, stelt men de optie
APT::Cache::GivenOnly
in\&.
.sp
De knooppunten in het weergegeven resultaat kunnen verschillende vormen aannemen: gewone pakketten worden als een vierkant voorgesteld, zuivere virtuele pakketten als een driehoek, gemengde virtuele pakketten als diamanten en ontbrekende pakketten als een zeshoek\&. Een vierkant met een oranje kleur stelt het einde van een recursiviteit voor (leaf package \- eindpakket)\&. Blauwe lijnen stellen een voorafgaandelijke vereiste voor en groene lijnen symboliseren conflicten\&.
.sp
Opgelet, dotty kan geen grafiek maken van een uitgebreide set pakketten\&.
.RE
.PP
\fBxvcg\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
Hetzelfde als
dotty, maar dan voor xvcg uit het
\m[blue]\fBVCG gereedschap\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE
.PP
\fBpolicy\fR [\fIpakket\fR\&...]
.RS 4
policy
is bedoeld om te helpen bij het debuggen van problemen die verband houden met het bestand preferences\&. Zonder argumenten zal het de prioriteiten van elke pakketbron weergeven\&. Anders zal het voor het opgegeven pakket gedetailleerde informatie over de prioriteitskeuze weergeven\&.
.RE
.PP
\fBmadison\fR \fB\fIpakket\fR\fR\fB\&...\fR
.RS 4
Het commando
madison
van
apt\-cache
tracht het uitvoerformaat en een deel van de functionaliteit na te bootsen van
madison, het Debian gereedschap voor archiefbeheer\&. Het geeft de beschikbare versies van een pakket weer in een tabelformaat\&. In tegenstelling tot het originele
madison, kan het enkel informatie weergeven betreffende de architectuur waarvoor APT pakketlijsten opgehaald heeft (APT::Architecture)\&.
.RE
.SH "OPTIES"
.PP
Alle commandoregelopties kunnen via het configuratiebestand ingesteld worden\&. de omschrijving geeft de in te stellen configuratieoptie op\&. Bij booleaanse opties kunt u instellingen uit het configuratiebestand overschrijven door iets te gebruiken als
\fB\-f\-\fR,
\fB\-\-no\-f\fR,
\fB\-f=no\fR
en meerdere andere variaties\&.
.PP
\fB\-p\fR, \fB\-\-pkg\-cache\fR
.RS 4
Het bestand waarin de pakketcache opgeslagen wordt kiezen\&. De pakketcache is de primaire cache die door alle operaties aangesproken wordt\&. Configuratie\-item:
Dir::Cache::pkgcache\&.
.RE
.PP
\fB\-s\fR, \fB\-\-src\-cache\fR
.RS 4
Het bestand kiezen waarin de broncache opgeslagen wordt\&. Deze broncache wordt enkel door
gencaches
gebruikt en het bevat een verwerkte versie van de pakketinformatie afkomstig van externe bronnen\&. Wanneer de pakketcache opgebouwd wordt, wordt gebruik gemaakt van de broncache om te vermijden dat alle pakketbestanden opnieuw verwerkt moeten worden\&. Configuratie\-item:
Dir::Cache::srcpkgcache\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Stille modus\&. Door het weglaten van voortgangsindicatoren genereert het uitvoer die geschikt is voor logbestanden\&. Meer q\*(Aqs, met een maximum van 2, leveren een hogere mate van beknopte uitvoer op\&. U kunt ook
\fB\-q=#\fR
gebruiken om de mate van gereduceerde uitvoer in te stellen en zo de instelling uit het configuratiebestand overschrijven\&. Configuratie\-item:
quiet\&.
.RE
.PP
\fB\-i\fR, \fB\-\-important\fR
.RS 4
Enkel belangrijke vereisten weergeven\&. Is bedoeld voor gebruik met
unmet
en
depends\&. Maakt dat enkel de relaties Depends en Pre\-Depends weergegeven worden\&. Configuratie\-item:
APT::Cache::Important\&.
.RE
.PP
\fB\-\-no\-pre\-depends\fR, \fB\-\-no\-depends\fR, \fB\-\-no\-recommends\fR, \fB\-\-no\-suggests\fR, \fB\-\-no\-conflicts\fR, \fB\-\-no\-breaks\fR, \fB\-\-no\-replaces\fR, \fB\-\-no\-enhances\fR
.RS 4
Standaard geven de opdrachten
depends
en
rdepends
alle vereisten weer\&. Met deze opties kan dit aangepast worden, waardoor het opgegeven vereistentype weggelaten wordt\&. Configuratie\-item:
APT::Cache::Show\fIDependencyType\fR, bijvoorbeeld
APT::Cache::ShowRecommends\&.
.RE
.PP
\fB\-\-implicit\fR
.RS 4
Standaard geven
depends
en
rdepends
enkel die vereisten weer die expliciet in de metadata vermeld worden\&. Met deze optie worden ook vereisten getoond die impliciet toegevoegd worden op basis van de gevonden gegevens\&. Bijvoorbeeld een
Conflicts: foo
houdt impliciet in dat dit pakket ook tegenstrijdig is met het pakket foo uit om het even welke andere architectuur\&. Configuratie\-item:
APT::Cache::ShowImplicit\&.
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
Bij zoekbewerkingen de volledige steekkaart van pakketten weergeven\&. Configuratie\-item:
APT::Cache::ShowFull\&.
.RE
.PP
\fB\-a\fR, \fB\-\-all\-versions\fR
.RS 4
De volledige steekkaart van alle beschikbare versies weergeven\&. Dit is de standaard\&. Om dit uit te schakelen moet u
\fB\-\-no\-all\-versions\fR
gebruiken\&. Indien
\fB\-\-no\-all\-versions\fR
werd opgegeven, zal enkel de informatie over het pakket dat kandidaat voor installatie is, getoond worden\&. Deze optie is enkel op het commando
show
van toepassing\&. Configuratie\-item:
APT::Cache::AllVersions\&.
.RE
.PP
\fB\-g\fR, \fB\-\-generate\fR
.RS 4
Automatisch een nieuwe pakketcache genereren, eerder dan de bestaande pakketcache te gebruiken\&. Dit is de standaard\&. Om dit uit te schakelen moet u
\fB\-\-no\-generate\fR
gebruiken\&. Configuratie\-item:
APT::Cache::Generate\&.
.RE
.PP
\fB\-\-names\-only\fR, \fB\-n\fR
.RS 4
Enkel zoeken in de pakketnamen en in de pakketnamen waarin voorzien wordt en niet in de uitgebreide beschrijvingen\&. Configuratie\-item:
APT::Cache::NamesOnly\&.
.RE
.PP
\fB\-\-all\-names\fR
.RS 4
pkgnames
alle namen laten weergeven, inclusief virtuele pakketten en ontbrekende vereisten\&. Configuratie\-item:
APT::Cache::AllNames\&.
.RE
.PP
\fB\-\-recurse\fR
.RS 4
depends
en
rdepends
recursief laten werken, zodat alle vermelde pakketten eenmaal weergegeven worden\&. Configuratie\-item:
APT::Cache::RecurseDepends\&.
.RE
.PP
\fB\-\-installed\fR
.RS 4
De uitvoer van
depends
en
rdepends
beperken tot pakketten die momenteel ge\(:installeerd zijn\&. Configuratie\-item:
APT::Cache::Installed\&.
.RE
.PP
\fB\-\-with\-source\fR \fB\fIbestandsnaam\fR\fR
.RS 4
Voegt het opgegeven bestand toe als een bron voor metadata\&. Kan herhaald worden om meerdere bestanden toe te voegen\&. Momenteel worden de bestanden
*\&.deb,
*\&.dsc,
*\&.changes,
Sources
en
Packages
ondersteund evenals mappen van broncodepakketten\&. Overeenstemmende bestanden worden enkel op basis van hun naam gevonden, niet op basis van hun inhoud!
.sp
Bestanden
Sources
en
Packages
mogen gecomprimeerd worden in elk formaat dat door apt ondersteund wordt, zolang ze de correcte extensie hebben\&. Indien u in \('e\('en map meerdere van deze bestanden moet opslaan, kunt u aan de naam een voorvoegsel naar keuze toevoegen met als laatste letter een liggend streepje ("_")\&. Bijvoorbeeld: mijn\&.voorbeeld_Packages\&.xz
.sp
Merk op dat deze bronnen beschouwd worden als te vertrouwen (zie
\fBapt-secure\fR(8))\&. Configuratie\-item:
APT::Sources::With\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Een korte samenvatting van het gebruik weergeven\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Het versienummer van het programma weergeven\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Configuratiebestand; Een te gebruiken configuratiebestand opgeven\&. Het programma zal het standaard configuratiebestand inlezen en nadien dit configuratiebestand\&. Als configuratie\-instellingen opgegeven moeten worden vooraleer de standaard configuratiebestanden verwerkt worden, geef dan een bestand op met de omgevingsvariabele
\fBAPT_CONFIG\fR\&. Raadpleeg
\fBapt.conf\fR(5)
voor informatie over de syntaxis\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Een configuratieoptie instellen; Dit stelt een willekeurige configuratieoptie in\&. De syntaxis is
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
en
\fB\-\-option\fR
kunnen meermaals gebruikt worden om verschillende opties in te stellen\&.
.RE
.SH "BESTANDEN"
.PP
/etc/apt/sources\&.list
.RS 4
Locaties waarvandaan pakketten opgehaald moeten worden\&. Configuratie\-item:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
Bestandsfragmenten met locaties waarvandaan pakketten opgehaald moeten worden\&. Configuratie\-item:
Dir::Etc::SourceParts\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
Opslaggebied voor statusinformatie over elke pakketbron vermeld in
\fBsources.list\fR(5)
Configuratie\-item:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
Opslaggebied voor statusinformatie tijdens het ophalen\&. Configuratie\-item:
Dir::State::Lists
(partial
zal impliciet toegevoegd worden)
.RE
.SH "ZIE OOK"
.PP
\fBapt.conf\fR(5),
\fBsources.list\fR(5),
\fBapt-get\fR(8)
.SH "DIAGNOSTIEK"
.PP
\fBapt\-cache\fR
geeft de terugkeerwaarde nul bij een normaal verlopen operatie, het decimaal getal 100 in geval van een fout\&.
.SH "BUGS"
.PP
\m[blue]\fBAPT bugpagina\fR\m[]\&\s-2\u[3]\d\s+2\&. Indien u een bug in APT wilt rapporteren, raadpleeg dan
/usr/share/doc/debian/bug\-reporting\&.txt
of het
\fBreportbug\fR(1)
commando\&.
.SH "VERTALING"
.PP
De Nederlandse vertaling werd in 2015 gemaakt door Frans Spiesschaert
<Frans\&.Spiesschaert@yucom\&.be>, in samenwerking met het Debian Dutch l10n Team
<debian\-l10n\-dutch@lists\&.debian\&.org>\&.
.PP
Merk op dat de vertaling van dit document nog onvertaalde delen kan bevatten\&. Dit is intentioneel om te vermijden dat inhoud verloren zou gaan door een vertaling die achterop loopt op het origineel\&.
.SH "AUTEURS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT\-team\fR
.RS 4
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
GraphViz
.RS 4
\%http://www.research.att.com/sw/tools/graphviz/
.RE
.IP " 2." 4
VCG gereedschap
.RS 4
\%http://rw4.cs.uni-sb.de/users/sander/html/gsvcg1.html
.RE
.IP " 3." 4
APT bugpagina
.RS 4
\%http://bugs.debian.org/src:apt
.RE
