'\" t
.\"     Title: apt-extracttemplates
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 27\ \&Mar\(,co\ \&2014
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Portuguese
.\"
.TH "APT\-EXTRACTTEMPLATE" "1" "27\ \&Mar\(,co\ \&2014" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
apt-extracttemplates \- Utilit\('ario para extrair configura\(,c\(~oes e modelos \fBdebconf\fR a partir de pacotes Debian
.SH "SINOPSE"
.HP \w'\fBapt\-extracttemplates\fR\ 'u
\fBapt\-extracttemplates\fR [\fB\-t=\fR\fB\fIdirect\('orio_tempor\('ario\fR\fR] \fInome_do_ficheiro\fR... {\-v\ |\ \-\-version} {\-h\ |\ \-\-help}
.SH "DESCRI\(,C\(~AO"
.PP
\fBapt\-extracttemplates\fR
ir\('a receber um ou mais ficheiros de pacotes Debian na sua entrada e escrever (para um direct\('orio tempor\('ario) todos os scripts de configura\(,c\(~ao associados e ficheiros de modelo\&. Por cada pacote passado por ele que contenha scripts de configura\(,c\(~ao e modelos, ser\('a gerada uma linha no formato:
.PP
pacote vers\(~ao ficheiro\-modelo script\-de\-configura\(,c\(~ao
.PP
ficheiro\-modelo e script\-de\-configura\(,c\(~ao s\(~ao escritos num direct\('orio tempor\('ario especificado por
\fB\-t\fR
ou
\fB\-\-tempdir\fR
(APT::ExtractTemplates::TempDir) direct\('orio, com nomes de ficheiros no formato
pacote\&.modelo\&.XXXXXX
e
pacote\&.configura\(,c\(~ao\&.XXXXXX
.SH "OP\(,C\(~OES"
.PP
Todas as op\(,c\(~oes de linha de comandos podem ser definidas usando o ficheiro de configura\(,c\(~ao, as descri\(,c\(~oes indicam a op\(,c\(~ao de configura\(,c\(~ao a definir\&. Para op\(,c\(~oes booleanas voc\(^e pode sobre por o ficheiro de configura\(,c\(~ao usando algo como
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou v\('arias outras variantes\&.
.PP
\fB\-t\fR, \fB\-\-tempdir\fR
.RS 4
Direct\('orio tempor\('ario para onde escrever ficheiros
\fBdebconf\fR
modelo extra\('idos e scripts de configura\(,c\(~ao\&. Item de Configura\(,c\(~ao:
APT::ExtractTemplates::TempDir
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra um sum\('ario curto da utiliza\(,c\(~ao\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Mostra a vers\(~ao do programa\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Ficheiro de Configura\(,c\(~ao; Especifica o ficheiro de configura\(,c\(~ao a usar\&. O programa ir\('a ler o ficheiro de configura\(,c\(~ao predefinido e depois este ficheiro de configura\(,c\(~ao\&. Se as defini\(,c\(~oes de configura\(,c\(~ao precisarem de ser definidas antes, os ficheiros de configura\(,c\(~ao predefinidos s\(~ao analisados especificando um ficheiro com a vari\('avel de ambiente
\fBAPT_CONFIG\fR\&. Veja
\fBapt.conf\fR(5)
para informa\(,c\(~ao de sintaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Define uma Op\(,c\(~ao de Configura\(,c\(~ao; Isto ir\('a definir uma op\(,c\(~ao de configura\(,c\(~ao arbitr\('aria\&. A sintaxe \('e
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
e
\fB\-\-option\fR
podem ser usadas v\('arias vezes para definir op\(,c\(~oes diferentes\&.
.RE
.SH "VEJA TAMB\('EM"
.PP
\fBapt.conf\fR(5)
.SH "DIAGN\('OSTICO"
.PP
\fBapt\-extracttemplates\fR
devolve zero na opera\(,c\(~ao normal, 100 decimal em erro\&.
.SH "BUGS"
.PP
\m[blue]\fBp\('agina de bugs do APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Se deseja reportar um bug no APT, por favor veja
/usr/share/doc/debian/bug\-reporting\&.txt
ou o comando
\fBreportbug\fR(1)\&.
.SH "TRADU\(,C\(^AO"
.PP
A tradu\(,c\(~ao Portuguesa foi feita por Am\('erico Monteiro
<a_monteiro@netcabo\&.pt>
de 2009 a 2012\&. A tradu\(,c\(~ao foi revista pela equipa de tradu\(,c\(~oes portuguesas da Debian
<traduz@debianpt\&.org>\&.
.PP
Note que este documento traduzido pode conter partes n\(~ao traduzidas\&. Isto \('e feito propositadamente, para evitar perdas de conte\('udo quando a tradu\(,c\(~ao est\('a atrasada relativamente ao conte\('udo original\&.
.SH "AUTORES"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBEquipa do APT\fR
.RS 4
.RE
.SH "NOTAS"
.IP " 1." 4
p\('agina de bugs do APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
