'\" t
.\"     Title: apt-cache
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 16\ \&Agosto\ \&2016
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: Portuguese
.\"
.TH "APT\-CACHE" "8" "16\ \&Agosto\ \&2016" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
apt-cache \- pesquisa a cache do APT
.SH "SINOPSE"
.HP \w'\fBapt\-cache\fR\ 'u
\fBapt\-cache\fR [\fB\-agipns\fR] [\fB\-o=\fR\fB\fIconfig_string\fR\fR] [\fB\-c=\fR\fB\fIficheiro_de_configura\(,c\(~ao\fR\fR] {gencaches | showpkg\ \fIpkg\fR...  | showsrc\ \fIpkg\fR...  | stats | dump | dumpavail | unmet | search\ \fIregex\fR...  | show\ \fIpkg\fR\ [{=\fIn\('umero_de_vers\(~ao_do_pacote\fR\ |\ /\fIlan\(,camento\-alvo\fR}]...  | depends\ \fIpkg\fR\ [{=\fIn\('umero_de_vers\(~ao_do_pacote\fR\ |\ /\fIlan\(,camento\-alvo\fR}]...  | rdepends\ \fIpkg\fR\ [{=\fIn\('umero_de_vers\(~ao_do_pacote\fR\ |\ /\fIlan\(,camento\-alvo\fR}]...  | pkgnames\ [\fIprefixo\fR]  | dotty\ \fIpkg\fR\ [{=\fIn\('umero_de_vers\(~ao_do_pacote\fR\ |\ /\fIlan\(,camento\-alvo\fR}]...  | xvcg\ \fIpkg\fR\ [{=\fIn\('umero_de_vers\(~ao_do_pacote\fR\ |\ /\fIlan\(,camento\-alvo\fR}]...  | policy\ [\fIpkg\fR...]  | madison\ \fIpkg\fR...  | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "DESCRI\(,C\(~AO"
.PP
\fBapt\-cache\fR
performs a variety of operations on APT\*(Aqs package cache\&.
\fBapt\-cache\fR
does not manipulate the state of the system but does provide operations to search and generate interesting output from the package metadata\&. The metadata is acquired and updated via the \*(Aqupdate\*(Aq command of e\&.g\&.
\fBapt\-get\fR, so that it can be outdated if the last update is too long ago, but in exchange
\fBapt\-cache\fR
works independently of the availability of the configured sources (e\&.g\&. offline)\&.
.PP
A menos que a op\(,c\(~ao
\fB\-h\fR, ou
\fB\-\-help\fR
seja fornecida, um dos comandos abaixo t\(^em que estar presentes\&.
.PP
\fBgencaches\fR
.RS 4
gencaches
cria a cache de pacotes do APT\&. Isto \('e feito implicitamente por todos os comandos que precisam desta cache se esta estiver em falta ou desactualizada\&.
.RE
.PP
\fBshowpkg\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
showpkg
mostra informa\(,c\(~ao acerca dos pacotes listados na linha de comandos\&. Os argumentos restantes s\(~ao nomes de pacotes\&. S\(~ao listadas as vers\(~oes dispon\('iveis e depend\(^encias reversas de cada pacote listado, assim como as depend\(^encias dianteiras de cada vers\(~ao\&. Depend\(^encias dianteiras (normais) s\(~ao aqueles pacotes de que o pacote em quest\(~ao depende; depend\(^encias reversas s\(~ao aqueles pacotes que dependem do pacote em quest\(~ao\&. Assim, as depend\(^encias dianteiras de um pacote t\(^em de ser satisfeitas, mas as depend\(^encias reversas n\(~ao precisam de ser\&. Por exemplo,
\fBapt\-cache showpkg libreadline2\fR
dever\('a produzir resultados semelhantes ao seguinte:
.sp
.if n \{\
.RS 4
.\}
.nf
Pacote: libreadline2
Vers\(~oes: 2\&.1\-12(/var/state/apt/lists/foo_Packages),
Depend\(^encias Reversas Depends: 
  libreadlineg2,libreadline2
  libreadline2\-altdev,libreadline2
Depend\(^encias:
2\&.1\-12 \- libc5 (2 5\&.4\&.0\-0) ncurses3\&.0 (0 (null))
Fornecimentos:
2\&.1\-12 \- 
Fornecimentos Reversos: 
.fi
.if n \{\
.RE
.\}
Assim pode\-se ver que libreadline2, vers\(~ao 2\&.1\-12, depende de libc5 e ncurses3\&.0 que t\(^em que ser instalados para que libreadline2 funcione\&. Por sua vez, libreadlineg2 e libreadline2\-altdev dependem de libreadline2\&. Se libreadline2 for instalado, libc5 e ncurses3\&.0 (e ldso) tamb\('em t\(^em que ser instalados; libreadlineg2 e libreadline2\-altdev n\(~ao precisam de ser instalados\&. Para o significado espec\('ifico do lembrete da sa\('ida \('e melhor consultar o c\('odigo fonte do apt\&.
.RE
.PP
\fBstats\fR
.RS 4
stats
mostra algumas estat\('isticas acerca da cache\&. N\(~ao s\(~ao esperados mais argumentos\&. As estat\('isticas reportadas s\(~ao:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total package names
\('e o n\('umero de nomes de pacotes encontrados na cache\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Normal packages
\('e o n\('umero de nomes de pacotes regulares e ordin\('arios; estes s\(~ao pacotes que t\(^em uma correspond\(^encia de um\-para\-um entre os seus nomes e os nomes usados por outros pacotes para eles nas depend\(^encias\&. A maioria dos pacotes caem nesta categoria\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pure virtual packages
\('e o n\('umero de pacotes que existem apenas como nome de pacote virtual; isto \('e, os pacotes apenas "disponibilizam" o nome do pacote virtual, e nenhum pacote usa realmente o nome\&. Por exemplo, "mail\-transport\-agent" no sistema Debian \('e um pacote puramente virtual; v\('arios pacotes disponibilizam "mail\-transport\-agent", mas n\(~ao existe um existe um pacote chamado "mail\-transport\-agent"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Single virtual packages
\('e o n\('umero de pacotes com apenas um pacote a disponibilizar um pacote virtual particular\&. Por exemplo, no sistema Debian, "X11\-text\-viewer" \('e um pacote virtual, mas apenas um pacote, xless, disponibiliza "X11\-text\-viewer"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mixed virtual packages
\('e o n\('umero de pacotes que ou disponibilizam um pacote virtual particular ou t\(^em o nome de pacote virtual como o nome de pacote\&. Por exemplo, no sistema Debian, "debconf" \('e tanto um pacote real, como tamb\('em disponibilizado pelo pacote debconf\-tiny\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Missing
\('e o n\('umero de nomes de pacotes que s\(~ao referenciados numa depend\(^encia mas n\(~ao foram disponibilizados por nenhum pacote\&. Os pacotes em falta podem ser uma evid\(^encia de que n\(~ao se est\('a a aceder ao total de uma distribui\(,c\(~ao, ou que um pacote (real ou virtual) foi removido da distribui\(,c\(~ao\&. Normalmente s\(~ao referenciados a partir de declara\(,c\(~oes de Conflitos ou Breaks\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total distinct
versions is the number of package versions found in the cache\&. If more than one distribution is being accessed (for instance, "stable" and "unstable"), this value can be considerably larger than the number of total package names\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Total dependencies
\('e o n\('umero de relacionamentos com depend\(^encias reivindicadas por todos os pacotes na cache\&.
.RE
.sp
.RE
.PP
\fBshowsrc\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
showsrc
displays all the source package records that match the given package names\&. All versions are shown, as well as all records that declare the name to be a binary package\&. Use
\fB\-\-only\-source\fR
to display only source package names\&.
.RE
.PP
\fBdump\fR
.RS 4
dump
mostra uma listagem curta de todos os pacotes na cache\&. \('E principalmente para depura\(,c\(~ao\&.
.RE
.PP
\fBdumpavail\fR
.RS 4
dumpavail
escreve uma lista de disponibilidades no stdout\&. Isto \('e apropriado para usar com o
\fBdpkg\fR(1)
e \('e usado pelo m\('etodo
\fBdselect\fR(1)\&.
.RE
.PP
\fBunmet\fR
.RS 4
unmet
mostra um sum\('ario de todas as depend\(^encias insatisfeitas na cache do pacote\&.
.RE
.PP
\fBshow\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
show
executa uma fun\(,c\(~ao semelhante ao
\fBdpkg \-\-print\-avail\fR; mostra os registos do pacote para os pacotes nomeados\&.
.RE
.PP
\fBsearch\fR \fB\fIregex\fR\fR\fB\&...\fR
.RS 4
search
performs a full text search on all available package lists for the POSIX regex pattern given, see
\fBregex\fR(7)\&. It searches the package names and the descriptions for an occurrence of the regular expression and prints out the package name and the short description, including virtual package names\&. If
\fB\-\-full\fR
is given then output identical to
show
is produced for each matched package, and if
\fB\-\-names\-only\fR
is given then the long description is not searched, only the package name and provided packages are\&.
.sp
Podem ser usados argumentos separados para especificar m\('ultiplos padr\(~oes de busca os quais s\(~ao lidados em conjunto\&.
.RE
.PP
\fBdepends\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
depends
mostra uma listagem de cada depend\(^encia que um pacote tem e todos os outros pacotes poss\('iveis que podem satisfazer essa depend\(^encia\&.
.RE
.PP
\fBrdepends\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
rdepends
mostra uma listagem de cada depend\(^encia reversa que um pacote tem\&.
.RE
.PP
\fBpkgnames\fR [\fIprefixo\fR]
.RS 4
Este comando escreve o nome de cada pacote que o APT conhece\&. O argumento opcional \('e um prefixo de correspond\(^encia para filtrar a lista de nomes\&. O resultado \('e apropriado para usar numa fun\(,c\(~ao completa de consola e o resultado \('e gerado com extrema rapidez\&. Este comando fica melhor usado com a op\(,c\(~ao
\fB\-\-generate\fR\&.
.sp
Note que um pacote que o APT conhe\(,ca n\(~ao est\('a necessariamente dispon\('ivel para download, instal\('avel ou instalado, por exemplo, os pacotes virtuais tamb\('em s\(~ao listados na lista gerada\&.
.RE
.PP
\fBdotty\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
dotty
recebe uma lista de pacotes na linha de comandos e gera resultados apropriados para uso pelo dotty do pacote
\m[blue]\fBGraphViz\fR\m[]\&\s-2\u[1]\d\s+2\&. O resultado ser\('a um conjunto de n\('os e orlas que representam os relacionamentos entre os pacotes\&. Por predefini\(,c\(~ao, os pacotes fornecidos ir\(~ao seguir todos os pacotes dependentes; isto pode produzir um gr\('afico muito grande\&. Para limitar os resultados apenas aos pacotes listados na linha de comandos, defina a op\(,c\(~ao
APT::Cache::GivenOnly\&.
.sp
Os n\('os resultantes ir\(~ao ter v\('arias formas; pacotes normais s\(~ao caixas, pacotes virtuais puros s\(~ao tri\(^angulos, pacotes virtuais de mistura s\(~ao diamantes, pacotes desaparecidos s\(~ao hex\('agonos\&. Caixas cor de laranja significam que a recurs\(~ao parou (pacotes leaf), linhas azuis s\(~ao pr\('e\-depend\(^encias, linhas verdes s\(~ao conflitos\&.
.sp
Aten\(,c\(~ao, o dotty n\(~ao consegue fazer gr\('aficos com grandes conjuntos de pacotes\&.
.RE
.PP
\fBxvcg\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
O mesmo que
dotty, apenas para xvcg a partir de
\m[blue]\fBFerramenta VCG\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE
.PP
\fBpolicy\fR [\fIpkg\fR\&...]
.RS 4
policy
destina\-se a ajudar a depurar problemas relacionados com o ficheiro de prefer\(^encias\&. Sem argumentos ir\('a escrever as propriedades de cada fonte\&. Caso contr\('ario escreve informa\(,c\(~ao detalhada acerca da selec\(,c\(~ao de prioridade do pacote nomeado\&.
.RE
.PP
\fBmadison\fR \fB\fIpkg\fR\fR\fB\&...\fR
.RS 4
O comando
madison
do
apt\-cache
tenta imitar o formato de sa\('ida e um subconjunto das funcionalidades da ferramenta
madison
de gest\(~ao de pacotes da Debian\&. Mostra vers\(~oes dispon\('iveis de um pacote num formato tabular\&. Ao contr\('ario do
madison
original, apenas pode mostrar informa\(,c\(~ao para a arquitectura que o APT recolheu listas de pacotes (APT::Architecture)\&.
.RE
.SH "OP\(,C\(~OES"
.PP
Todas as op\(,c\(~oes de linha de comandos podem ser definidas usando o ficheiro de configura\(,c\(~ao, as descri\(,c\(~oes indicam a op\(,c\(~ao de configura\(,c\(~ao a definir\&. Para op\(,c\(~oes booleanas voc\(^e pode sobre por o ficheiro de configura\(,c\(~ao usando algo como
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou v\('arias outras variantes\&.
.PP
\fB\-p\fR, \fB\-\-pkg\-cache\fR
.RS 4
Selecciona o ficheiro para armazenar a cache do pacote\&. A cache do pacote \('e a cache principal usada por todas as opera\(,c\(~oes\&. Item de Configura\(,c\(~ao:
Dir::Cache::pkgcache\&.
.RE
.PP
\fB\-s\fR, \fB\-\-src\-cache\fR
.RS 4
Selecciona o ficheiro para armazenar a cache de fonte\&. A fonte \('e usada apenas pelo
gencaches
e armazena uma vers\(~ao analisada da informa\(,c\(~ao do pacote a partir de fontes remotas\&. Ao construir a cache de pacote \('e usada a cache fonte para evitar reanalisar todos os ficheiros do pacote\&. Item de Configura\(,c\(~ao:
Dir::Cache::srcpkgcache\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Quiet; produz resultados apropriados para registar em logs, omitindo os indicadores de progresso\&. Mais q\*(Aqs ir\(~ao produzir mais serenidade at\('e um m\('aximo de 2\&. Voc\(^e tamb\('em pode usar
\fB\-q=#\fR
para definir o n\('ivel de serenidade, sobrepondo o ficheiro de configura\(,c\(~ao\&. Item de Configura\(,c\(~ao:
quiet\&.
.RE
.PP
\fB\-i\fR, \fB\-\-important\fR
.RS 4
Escreve apenas depend\(^encias importantes; para usar com
unmet
e
depends\&. Separa apenas rela\(,c\(~oes de Depends e Pre\-Depends para serem escritas\&. Item de Configura\(,c\(~ao:
APT::Cache::Important\&.
.RE
.PP
\fB\-\-no\-pre\-depends\fR, \fB\-\-no\-depends\fR, \fB\-\-no\-recommends\fR, \fB\-\-no\-suggests\fR, \fB\-\-no\-conflicts\fR, \fB\-\-no\-breaks\fR, \fB\-\-no\-replaces\fR, \fB\-\-no\-enhances\fR
.RS 4
Per default the
\fBdepends\fR
and
\fBrdepends\fR
print all dependencies\&. This can be tweaked with these flags which will omit the specified dependency type\&. Configuration Item:
APT::Cache::Show\fIDependencyType\fR
e\&.g\&.
APT::Cache::ShowRecommends\&.
.RE
.PP
\fB\-\-implicit\fR
.RS 4
Per default
\fBdepends\fR
and
\fBrdepends\fR
print only dependencies explicitly expressed in the metadata\&. With this flag it will also show dependencies implicitly added based on the encountered data\&. A
Conflicts: foo
e\&.g\&. expresses implicitly that this package also conflicts with the package foo from any other architecture\&. Configuration Item:
APT::Cache::ShowImplicit\&.
.RE
.PP
\fB\-f\fR, \fB\-\-full\fR
.RS 4
Escreve registos de pacote completos quando procura\&. Item de Configura\(,c\(~ao:
APT::Cache::ShowFull\&.
.RE
.PP
\fB\-a\fR, \fB\-\-all\-versions\fR
.RS 4
Escreve registos completos para todas as vers\(~oes dispon\('iveis\&. Isto \('e a predefini\(,c\(~ao; para a desligar, use
\fB\-\-no\-all\-versions\fR\&. Se
\fB\-\-no\-all\-versions\fR
for especificada, apenas a vers\(~ao candidata ser\('a mostrada (aquela que seria seleccionada para instala\(,c\(~ao)\&. Esta op\(,c\(~ao \('e aplic\('avel apenas ao comando
show\&. Item de Configura\(,c\(~ao:
APT::Cache::AllVersions\&.
.RE
.PP
\fB\-g\fR, \fB\-\-generate\fR
.RS 4
Executa regenera\(,c\(~ao autom\('atica da cache de pacote, em vez de usar a cache como est\('a\&. Isto \('e a predefini\(,c\(~ao; para a desligar, use
\fB\-\-no\-generate\fR\&. Item de Configura\(,c\(~ao:
APT::Cache::Generate\&.
.RE
.PP
\fB\-\-names\-only\fR, \fB\-n\fR
.RS 4
Only search on the package and provided package names, not the long descriptions\&. Configuration Item:
APT::Cache::NamesOnly\&.
.RE
.PP
\fB\-\-all\-names\fR
.RS 4
Faz com que o
pkgnames
escreva todos os nomes, incluindo pacotes virtuais e depend\(^encias em falta\&. Item de configura\(,c\(~ao:
APT::Cache::AllNames\&.
.RE
.PP
\fB\-\-recurse\fR
.RS 4
Torna
depends
e
rdepends
recursivo para que todos os pacotes mencionados sejam escritos uma vez\&. Item de Configura\(,c\(~ao
APT::Cache::RecurseDepends\&.
.RE
.PP
\fB\-\-installed\fR
.RS 4
Limita a sa\('ida de
depends
e
rdepends
aos pacotes que est\(~ao actualmente instalados\&. Item de Configura\(,c\(~ao:
APT::Cache::Installed\&.
.RE
.PP
\fB\-\-with\-source\fR \fB\fInome_do_ficheiro\fR\fR
.RS 4
Adds the given file as a source for metadata\&. Can be repeated to add multiple files\&. Supported are currently
*\&.deb,
*\&.dsc,
*\&.changes,
Sources
and
Packages
files as well as source package directories\&. Files are matched based on their name only, not their content!
.sp
Sources
and
Packages
can be compressed in any format apt supports as long as they have the correct extension\&. If you need to store multiple of these files in one directory you can prefix a name of your choice with the last character being an underscore ("_")\&. Example: my\&.example_Packages\&.xz
.sp
Note that these sources are treated as trusted (see
\fBapt-secure\fR(8))\&. Configuration Item:
APT::Sources::With\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra um sum\('ario curto da utiliza\(,c\(~ao\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Mostra a vers\(~ao do programa\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Ficheiro de Configura\(,c\(~ao; Especifica o ficheiro de configura\(,c\(~ao a usar\&. O programa ir\('a ler o ficheiro de configura\(,c\(~ao predefinido e depois este ficheiro de configura\(,c\(~ao\&. Se as defini\(,c\(~oes de configura\(,c\(~ao precisarem de ser definidas antes, os ficheiros de configura\(,c\(~ao predefinidos s\(~ao analisados especificando um ficheiro com a vari\('avel de ambiente
\fBAPT_CONFIG\fR\&. Veja
\fBapt.conf\fR(5)
para informa\(,c\(~ao de sintaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Define uma Op\(,c\(~ao de Configura\(,c\(~ao; Isto ir\('a definir uma op\(,c\(~ao de configura\(,c\(~ao arbitr\('aria\&. A sintaxe \('e
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
e
\fB\-\-option\fR
podem ser usadas v\('arias vezes para definir op\(,c\(~oes diferentes\&.
.RE
.SH "FICHEIROS"
.PP
/etc/apt/sources\&.list
.RS 4
Localiza\(,c\(~oes de onde obter pacotes\&. Item de Configura\(,c\(~ao:
Dir::Etc::SourceList\&.
.RE
.PP
/etc/apt/sources\&.list\&.d/
.RS 4
Ficheiros fragmentados para localiza\(,c\(~oes de onde obter pacotes\&. Item de Configura\(,c\(~ao:
Dir::Etc::SourceParts\&.
.RE
.PP
/var/lib/apt/lists/
.RS 4
\('Area de armazenamento para informa\(,c\(~ao de estado para cada recurso de pacote especificado em
\fBsources.list\fR(5)
Tem de Configura\(,c\(~ao:
Dir::State::Lists\&.
.RE
.PP
/var/lib/apt/lists/partial/
.RS 4
\('Area de armazenamento para informa\(,c\(~ao de estado em tr\(^ansito\&. Item de Configura\(,c\(~ao:
Dir::State::Lists
ser\('a implicitamente acrescentado (partial)
.RE
.SH "VEJA TAMB\('EM"
.PP
\fBapt.conf\fR(5),
\fBsources.list\fR(5),
\fBapt-get\fR(8)
.SH "DIAGN\('OSTICO"
.PP
\fBapt\-cache\fR
devolve zero em opera\(,c\(~ao normal, 100 decimal em erro\&.
.SH "BUGS"
.PP
\m[blue]\fBp\('agina de bugs do APT\fR\m[]\&\s-2\u[3]\d\s+2\&. Se deseja reportar um bug no APT, por favor veja
/usr/share/doc/debian/bug\-reporting\&.txt
ou o comando
\fBreportbug\fR(1)\&.
.SH "TRADU\(,C\(^AO"
.PP
A tradu\(,c\(~ao Portuguesa foi feita por Am\('erico Monteiro
<a_monteiro@netcabo\&.pt>
de 2009 a 2012\&. A tradu\(,c\(~ao foi revista pela equipa de tradu\(,c\(~oes portuguesas da Debian
<traduz@debianpt\&.org>\&.
.PP
Note que este documento traduzido pode conter partes n\(~ao traduzidas\&. Isto \('e feito propositadamente, para evitar perdas de conte\('udo quando a tradu\(,c\(~ao est\('a atrasada relativamente ao conte\('udo original\&.
.SH "AUTORES"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBEquipa do APT\fR
.RS 4
.RE
.SH "NOTAS"
.IP " 1." 4
GraphViz
.RS 4
\%http://www.research.att.com/sw/tools/graphviz/
.RE
.IP " 2." 4
Ferramenta VCG
.RS 4
\%http://rw4.cs.uni-sb.de/users/sander/html/gsvcg1.html
.RE
.IP " 3." 4
p\('agina de bugs do APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
