'\" t
.\"     Title: apt-transport-mirror
.\"    Author: APT-Team
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09\ \&Dezember\ \&2017
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: German
.\"
.TH "APT\-TRANSPORT\-MIRR" "1" "09\ \&Dezember\ \&2017" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-transport-mirror \- APT\-Transportmethode f\(:ur st\(:arker automatisierte Spiegelserverauswahl
.SH "BESCHREIBUNG"
.PP
Diese APT\-Transportmethode implementiert kein Protokoll, um auf lokale oder ferne Depots selbst zuzugreifen, beschafft jedoch eine Spiegelserverliste und leitet alle Anfragen an den/die Spiegel, der/die aus der Liste herausgegriffen wurde(n)\&. Der Zugriff erfolgt \(:uber andere Transportprotokolle wie
\fBapt-transport-http\fR(1)\&. Die Grundfunktionalit\(:at ist seit APT 0\&.7\&.24 verf\(:ugbar, war jedoch bis APT 1\&.6 nicht dokumentiert\&. APT 1\&.6 enth\(:alt eine komplette Neuentwicklung der Transportmethode und der unterst\(:utzten Funktionalit\(:aten\&. Beachten Sie, dass eine Transportmethode niemals durch einen Benutzer direkt aufgerufen wird, jedoch von APT\-Werkzeugen basierend auf der Konfiguration des Benutzers\&.
.PP
Falls das Beschaffen einer Datei mittels eines Spiegelservers fehlschl\(:agt, stellt die Methode sicher, dass automatisch ein anderer m\(:oglicher Spiegelserver der Liste ausprobiert wird, entweder bis die Datei geholt wurde oder bis kein Spiegelserver auf der Liste mehr \(:ubrig ist\&. Damit werden transparent Serverausfallzeiten und \(:ahnliche Probleme gehandhabt\&.
.PP
Die Konsequenzen f\(:ur die Sicherheit aufgrund der Transportmethode basieren auf Sicherheitserw\(:agungen, die mit der Transportmethode verbunden sind, die zum Holen der Spiegelserverliste verwendet wird, und welche Transportmethoden beim Zugriff auf den/die ausgew\(:ahlten Spiegelserver durch die Transportmethode beteiligt sind\&.
.SH "OPTIONEN"
.PP
Diese Transportmethode hat derzeit keine Konfigurationsoptionen\&. Die Auswahl des Spiegelservers basiert ganz auf den angebotenene Spiegelservern auf der Spiegelserverliste und den Dateien, die APT holen m\(:ochte\&.
.SS "Spiegelserverlistenformat"
.PP
Eine Spiegelserverliste enth\(:alt mindestens eine Zeile\&. Jede Zeile gibt einen URI f\(:ur einen Spiegelserver an\&. Leere Zeilen und die, die mit einem Rautezeichen (#) beginnen, werden ignoriert\&. Ein URI beginnt immer mit einem URI\-Schema, das angibt, welche Transportmethode f\(:ur diesen Spiegelserver benutzt wird\&. Falls der URI beispielsweise mit
http:
anf\(:angt, ist die zust\(:andige Transportmethode
\fBapt-transport-http\fR(1), was spezielle Anforderungen an das Format des verbleibenden Teils des URI stellen kann\&.
.PP
Metadaten \(:uber einen Spiegelserver k\(:onnen in derselben Zeile angegeben werden, vom URI durch einen Tabulator getrennt\&. Mehrere Elemente der Metadaten k\(:onnen ihrerseits durch Leerzeichen oder Tabulatoren getrennt werden\&. (Dies ist eine fortschrittliche Funktionalit\(:at, die erst seit APT 1\&.6 verf\(:ugbar ist\&. \(:Altere APT\-Versionen scheitern bei der Auswertung von Spiegelserverlisten, die diese Funktionalit\(:at verwenden\&.)
.PP
Seit APT 1\&.6 wird auch die Verwendung komprimierter Spiegelserverlisten unterst\(:utzt\&. Beachten Sie, dass der Dateiname der Spiegelserverliste den verwendeten Komprimierungsalgorithmus angeben muss; es wird keine automatische Bestimmung anhand des Dateiinhalts durchgef\(:uhrt\&.
.SS "Spiegelserverauswahl anhand von Metadaten"
.PP
Wie im Format angegeben, k\(:onnen an einen Spiegelserver zus\(:atzliche Metadaten angeh\(:angt werden, um zu verhindern, dass ein Spiegelserver ausgew\(:ahlt wird, um eine Datei zu beschaffen, die diesen Metadaten nicht entspricht\&. Auf diese Weise kann die Spiegelserverliste z\&.B\&. Teilspiegelserver enthalten, die nur bestimmte Architekturen bereitstellen, und APT wird f\(:ur Dateien, die eine nicht aufgef\(:uhrte Architektur ben\(:otigen, automatisch einen anderen Spiegelserver ausw\(:ahlen\&. Unterst\(:utzt werden Beschr\(:ankungen f\(:ur die Architektur (arch), den Codenamen der Ver\(:offentlichung (codename), Bestandteil des Depots, in dem sich die Datei befindet (component), die zur Datei passende Sprache (lang), Suite\-Name der Ver\(:offentlichung (suite) und Typ der Datei (type)\&.
.SS "Reihenfolge der Ersatzspiegel"
.PP
Falls f\(:ur einen Spiegel keine Priorit\(:at \(:uber den Metadatenschl\(:ussel
priority
angegeben wurde, ist die Reihenfolge, in der die Spiegelserver ausgew\(:ahlt werden, zuf\(:allig\&. Falls eine bestimmte Zusammenstellung von Spiegelservern zuerst vor anderen Zusammenstellungen ausprobiert werden soll, kann die Priorit\(:at explizit gesetzt werden\&. Die Spiegelserver mit der niedrigsten Nummer werden zuerst ausprobiert\&. Spiegelserver, die keine explizit gesetzte Priorit\(:at haben, werden standardm\(:a\(ssig auf die h\(:ochstm\(:ogliche Nummer gesetzt und daher zuletzt ausprobiert\&. Die Auswahl zwischen Spiegelservern mit derselben Priorit\(:at erfolgt wiederum zuf\(:allig\&.
.SS "Erlaubte Transportmethoden in einer Spiegelserverliste"
.PP
Die Verf\(:ugbarkeit und Auswahl von Transportmethoden in einer Spiegelserverliste wird durch die Zugriffsart von APT auf die Spiegelserverliste beschr\(:ankt\&. Falls eine lokale Transportmethode wie
file
oder
copy
benutzt wird, kann die Spiegelserverliste auch lokale Ressourcen enthalten, w\(:ahrend eine Spiegelserverliste, auf die per
http
zugegriffen wird, dies nicht kann\&. Eine Spiegelserverliste kann nicht zus\(:atzlich eine weitere Spiegelserverliste oder andere verpackte Transportmethoden (wie
apt\-transport\-tor) enthalten\&. Sie finden in der Dokumentation dieser Transportmethoden, wie sie mit der Spiegelservermethode benutzt werden\&.
.PP
Beachten Sie, dass APT\-Versionen vor 1\&.6 keine andere Transportmethode als
http
unterst\(:utzten\&.
.SH "BEISPIELE"
.SS "Einfaches Beispiel"
.PP
Eine einfache Beispielspiegelserverliste, die von allen APT\-Versionen mit einer Spiegelservermethode (>= 0\&.7\&.24) unterst\(:utzt wird, in der der Client einen von drei Spiegelservern aussuchen kann:
.sp
.if n \{\
.RS 4
.\}
.nf
http://ftp\&.de\&.debian\&.org/debian/
http://ftp\&.us\&.debian\&.org/debian/
http://deb\&.debian\&.org/debian/
.fi
.if n \{\
.RE
.\}
.PP
Angenommen, eine Datei mit diesem Inhalt w\(:are als
/etc/apt/mirrorlist\&.txt
auf Ihrem Rechner gespeichert\&. Sie kann (seit APT 1\&.6) wie folgt in
\fBsources.list\fR(5)
benutzt werden:
.sp
.if n \{\
.RS 4
.\}
.nf
deb mirror+file:/etc/apt/mirrorlist\&.txt stretch main
.fi
.if n \{\
.RE
.\}
.PP
Alle Versionen der Spiegelservermethode unterst\(:utzen eine Spiegelserverliste, auf die mittels HTTP zugegriffen werden kann\&. Wird davon ausgegangen, dass sie unter
http://apt\&.example\&.org/mirror\&.lst
verf\(:ugbar ist, kann obiger Sources\&.list\-Eintrag kann stattdessen auch wie folgt geschrieben werden:
.sp
.if n \{\
.RS 4
.\}
.nf
deb mirror://apt\&.example\&.org/mirror\&.lst stretch main
.fi
.if n \{\
.RE
.\}
.PP
Beachten Sie, das seit APT 1\&.6 die Verwendung von
mirror+http
der Einheitlichkeit wegen
mirror
vorgezogen werden sollte\&. Die Funktionalit\(:at ist dieselbe\&.
.SS "Beispiel mit verbesserter Spiegelserverauswahl anhand von Metadaten"
.PP
Wie in der Formatdefinition erkl\(:art, unterst\(:utzen dies APT\-Versionen vor 1\&.6 nicht und das Auswerten der Spiegelserverliste wird scheitern\&. Die Beispielspiegelserverliste ist absichtlich komplex, um einige Aspekte der Auswahl zu zeigen\&. Die folgende Einstellung wird angenommen: Der erste Spiegelserver ist ein lokaler Spiegelserver, auf den mit der File\-Methode zugegriffen wird, aber m\(:oglicherweise unvollst\(:andig\&. Der zweite Spiegelserver hat eine gute Verbindung, ist aber ein Teilspiegelserver in sofern, dass er nur Dateien der Architekturen
amd64
und
all
enth\(:alt\&. Die verbleibenden Spiegelserver sind Durchschnittsserver, die nur kontaktiert werden sollen, wenn die vorherigen nicht funktionieren\&.
.sp
.if n \{\
.RS 4
.\}
.nf
file:/srv/local/debian/mirror/	priority:1 type:index
http://partial\&.example\&.org/mirror/	priority:2 arch:amd64 arch:all type:deb
http://ftp\&.us\&.debian\&.org/debian/	type:deb
http://ftp\&.de\&.debian\&.org/debian/	type:deb
https://deb\&.debian\&.org/debian/
.fi
.if n \{\
.RE
.\}
.PP
In dieser Einstellung mit dieser Spiegelserverliste wird der erste Spiegelserver benutzt, um alle Indexdateien herunterzuladen, unter der Annahme, dass auf die Spiegelserverliste selbst \(:uber eine lokale Transportmethode wie
file
zugegriffen wird\&. Falls dies nicht so ist, auf den Spiegelserver aus einem anderen Grund nicht zugegriffen werden kann oder er die angeforderte Datei nicht enth\(:alt, wird ein anderer Spiegelserver benutzt, um die Datei zu beschaffen, was vom Typ der Datei abh\(:angt: Eine Indexdatei wird durch den letzten Spiegelserver auf der Liste bereitgestellt, w\(:ahrend ein Paket der Architektur
amd64
durch den zweiten und z\&.B\&. der Architektur
i386
durch einen der letzten drei\&.
.SH "FEHLER"
.PP
\m[blue]\fBAPT\-Fehlerseite\fR\m[]\&\s-2\u[1]\d\s+2\&. Wenn Sie einen Fehler in APT berichten m\(:ochten, lesen Sie bitte
/usr/share/doc/debian/bug\-reporting\&.txt
oder den
\fBreportbug\fR(1)\-Befehl\&. Verfassen Sie Fehlerberichte bitte auf Englisch\&.
.SH "\(:UBERSETZUNG"
.PP
Die deutsche \(:Ubersetzung wurde 2009 von Chris Leick
<c\&.leick@vollbio\&.de>
in Zusammenarbeit mit dem deutschen l10n\-Team von Debian
<debian\-l10n\-german@lists\&.debian\&.org>
angefertigt\&.
.PP
Beachten Sie, dass diese \(:Ubersetzung Teile enthalten kann, die nicht \(:ubersetzt wurden\&. Dies ist so, damit kein Inhalt verloren geht, wenn die \(:Ubersetzung hinter dem Originalinhalt hinterherh\(:angt\&.
.SH "AUTOR"
.PP
\fBAPT\-Team\fR
.RS 4
.RE
.SH "FU\(ssNOTEN"
.IP " 1." 4
APT-Fehlerseite
.RS 4
\%http://bugs.debian.org/src:apt
.RE
