'\" t
.\"     Title: apt-transport-https
.\"    Author: \('Equipe de d\('eveloppement d\*(AqAPT
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11\ \&mai\ \&2018
.\"    Manual: APT
.\"    Source: APT 1.8.0~alpha3
.\"  Language: French
.\"
.TH "APT\-TRANSPORT\-HTTP" "1" "11\ \&mai\ \&2018" "APT 1.8.0~alpha3" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apt-transport-https \- Le transport d\*(AqAPT pour t\('el\('echarger par HTTPS (protocole de transfert hypertexte s\('ecuris\('e)
.SH "DESCRIPTION"
.PP
Ce transport d\*(AqAPT permet d\*(Aqutiliser les d\('ep\(^ots auxquels on acc\(`ede au moyen de HTTPS (protocole HTTP Secure), aussi appel\('e HTTP sur TLS\&. Il est disponible par d\('efaut depuis apt\ \&1\&.5 et \('etait disponible auparavant dans lepaquet
apt\-transport\-https\&. Veuillez noter qu\*(Aqun transport n\*(Aqest jamais appel\('e directement par l\*(Aqutilisateur, maisutilis\('e par les outils d\*(AqAPT s\*(Aqappuyant sur la configuration de l\*(Aqutilisateur\&.
.PP
HTTP est un protocole de transport non chiffr\('e (comparez avec
\fBapt-transport-http\fR(1)), qui, comme l\*(Aqindique le S ajout\('e, est envelopp\('e dans une couche chiffr\('ee, connue sous le nom de \(Fo\ \&Transport Layer Security\ \&\(Fc (TLS), pour fournir un chiffrement de bout en bout\&. Un attaquant suffisamment comp\('etent peut encore observer les partenaires de la communication et une analyse approfondie de la communication chiffr\('ee pourrait toujours r\('ev\('eler des d\('etails importants\&. Un aper\(,cu des m\('ethodes de transport alternatives disponibles est donn\('e dans
\fBsources.list\fR(5)\&.
.SH "OPTIONS"
.PP
Le protocole HTTPS est bas\('e sur le protocole HTTP, aussi toutes les options prises en charge par
\fBapt-transport-http\fR(1)
sont aussi disponibles au moyen de
Acquire::https
et ont par d\('efaut les m\(^eme valeurs que celles sp\('ecifi\('ees pour
Acquire::http\&. Cette page de manuel ne documentera que les options
\fIpropres \(`a https\fR\&.
.SS "Accr\('editations du serveur"
.PP
Par d\('efaut, tous les certificats de confiance du syst\(`eme (voir le paquet
ca\-certificates
sont utilis\('es pour la v\('erification du certificat du serveur\&. Une autre autorit\('e de certification (CA) peut \(^etre configur\('ee avec l\*(Aqoption
Acquire::https::CAInfo
et son option sp\('ecifique de l\*(Aqh\(^ote
Acquire::https::CAInfo::\fIh\(^ote\fR\&. L\*(Aqoption CAInfo sp\('ecifie un fichier compos\('e des certificats de CA (au format PEM) concat\('en\('es pour cr\('eer la cha\(^ine qu\*(AqAPT peut utiliser pour v\('erifier le chemin \(`a partir du certificat racine auto\-sign\('ee\&. Si le serveur distant fournit toute la cha\(^ine pendant l\*(Aq\('echange, le fichier ne doit contenir que le certificat racine\&. Autrement, toute la cha\(^ine est requise\&. Si la gestion de plusieurs autorit\('es est n\('ecessaire, le seul moyen est de tout concat\('ener\&.
.PP
Une liste de r\('evocation de certificats (CRL) personnalis\('ee peut \(^etre configur\('ee avec l\*(Aqoption
Acquire::https::CRLFile
et
Acquire::https::CRLFile::\fIh\(^ote\fR\&. Comme avec l\*(Aqoption pr\('ec\('edente, il faut sp\('ecifier un fichier au format PEM\&.
.SS "D\('esactiver la s\('ecurit\('e"
.PP
Durant l\*(Aqauthentification du serveur, si la v\('erification du certificat \('echoue pour une raison quelconque (expir\('e, r\('evoqu\('e, homme du milieu,\ \&etc\&.), la connexion \('echoue\&. C\*(Aqest certainement ce que vous souhaitez dans tous les cas et ce que fournit la valeur par d\('efaut (\(Fo\ \&true\ \&\(Fc) de l\*(Aqoption
Acquire::https::Verify\-Peer
et de ses variantes sp\('ecifiques \(`a l\*(Aqh\(^ote\&. Si vous savez
\fIexactement\fR
ce que vous faites, la configuration de cette option \(`a \(Fo\ \&false\ \&\(Fc vous permet d\*(Aqignorer la v\('erification du certificat du pair et de faire r\('eussir l\*(Aq\('echange\&. Une fois de plus, cette option est seulement destin\('ee au test ou au d\('ebogage dans la mesure o\(`u elle supprime toute la s\('ecurit\('e apport\('ee par l\*(Aqutilisation de HTTPS\&.
.PP
De la m\(^eme fa\(,con, l\*(Aqoption
Acquire::https::Verify\-Host
et sa variante sp\('ecifique \(`a l\*(Aqh\(^ote peuvent \(^etre utilis\('ees pour d\('esactiver la fonction de s\('ecurit\('e\&. Le certificat fourni par le serveur comprend l\*(Aqidentit\('e du serveur qui devrait correspondre au nom de DNS utilis\('e pour y acc\('eder\&. Par d\('efaut, comme cela est requis par la RFC\ \&2818, le nom du miroir est v\('erifi\('e par rapport \(`a l\*(Aqidentit\('e trouv\('ee dans le certificat\&. Ce comportement par d\('efaut est s\(^ur et ne devrait pas \(^etre modifi\('e, mais si vous savez que le serveur que vous utilisez \(`a un nom de DNS qui ne correspond pas \(`a l\*(Aqidentit\('e de son certificat, il est possible de r\('egler l\*(Aqoption \(`a "false", ce qui emp\(^echera la r\('ealisation de la comparaison\&.
.SS "Authentification du client"
.PP
Outre la gestion de l\*(Aqauthentification bas\('ee sur les mots de passe (voir
\fBapt_auth.conf\fR(5)) HTTPS prend aussi en charge l\*(Aqauthentification bas\('ee sur les certificats du client avec
Acquire::https::SSLCert
et
Acquire::https::SSLKey\&. Leurs valeurs doivent \(^etre respectivement celle du nom de fichier du certificat X\&.509 du client et celle de la cl\('e priv\('ee (non chiffr\('ee) associ\('ee, toutes les deux au format PEM\&. En pratique, l\*(Aqutilisation des variantes sp\('ecifiques \(`a l\*(Aqh\(^ote des deux options est fortement recommand\('ee\&.
.SH "EXEMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
Acquire::https {
	Proxy::example\&.org "DIRECT";
	Proxy "socks5h://apt:pass@127\&.0\&.0\&.1:9050";
	Proxy\-Auto\-Detect "/usr/local/bin/apt\-https\-proxy\-auto\-detect";
	No\-Cache "true";
	Max\-Age "3600";
	No\-Store "true";
	Timeout "10";
	Dl\-Limit "42";
	Pipeline\-Depth "0";
	AllowRedirect "false";
	User\-Agent "My APT\-HTTPS";
	SendAccept "false";

	CAInfo "/path/to/ca/certs\&.pem";
	CRLFile "/path/to/all/crl\&.pem";
	Verify\-Peer "true";
	Verify\-Host::broken\&.example\&.org "false";
	SSLCert::example\&.org "/path/to/client/cert\&.pem";
	SSLKey::example\&.org "/path/to/client/key\&.pem"
};
.fi
.if n \{\
.RE
.\}
.SH "VOIR AUSSI"
.PP
\fBapt-transport-http\fR(1)
\fBapt.conf\fR(5)
\fBapt_auth.conf\fR(5)
\fBsources.list\fR(5)
.SH "BOGUES"
.PP
\m[blue]\fBPage des bogues d\*(AqAPT\fR\m[]\&\s-2\u[1]\d\s+2\&. Si vous souhaitez signaler un bogue \(`a propos d\*(AqAPT, veuillez lire
/usr/share/doc/debian/bug\-reporting\&.txt
ou utiliser la commande
\fBreportbug\fR(1)\&.
.SH "TRADUCTEURS"
.PP
J\('er\(^ome Marant, Philippe Batailler, Christian Perrier
<bubulle@debian\&.org>
(2000, 2005, 2009, 2010), \('Equipe de traduction francophone de Debian
<debian\-l10n\-french@lists\&.debian\&.org>
.PP
Veuillez noter que cette traduction peut contenir des parties non traduites\&. Cela est volontaire, pour \('eviter de perdre du contenu quand la traduction est l\('eg\(`erement en retard sur le contenu d\*(Aqorigine\&.
.SH "AUTEUR"
.PP
\fB\('Equipe de d\('eveloppement d\*(AqAPT\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
Page des bogues d'APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
